// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: b60939a5a59438931b81b47e98b0059dde5e06e67c79bfb3cd5c8efe55162344
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
package all

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth2-client/api/v1/bellatrix"
	"github.com/ethpandaops/go-eth2-client/api/v1/capella"
	"github.com/ethpandaops/go-eth2-client/api/v1/deneb"
	"github.com/ethpandaops/go-eth2-client/api/v1/electra"
	"github.com/ethpandaops/go-eth2-client/spec/phase0"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[*bellatrix.BlindedBeaconBlock](`ssz-static:"false"`)
var _ = sszutils.Annotate[*capella.BlindedBeaconBlock](`ssz-static:"false"`)
var _ = sszutils.Annotate[*deneb.BlindedBeaconBlock](`ssz-static:"false"`)
var _ = sszutils.Annotate[*electra.BlindedBeaconBlock](`ssz-static:"false"`)

func (t *BlindedBeaconBlock) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *bellatrix.BlindedBeaconBlock:
		return t.marshalSSZView_BlindedBeaconBlock
	case *capella.BlindedBeaconBlock:
		return t.marshalSSZView_BlindedBeaconBlock_0
	case *deneb.BlindedBeaconBlock:
		return t.marshalSSZView_BlindedBeaconBlock_1
	case *electra.BlindedBeaconBlock:
		return t.marshalSSZView_BlindedBeaconBlock_2
	}
	return nil
}
func (t *BlindedBeaconBlock) marshalSSZView_BlindedBeaconBlock(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BlindedBeaconBlock)
	}
	dstlen := len(dst)
	{ // Static Field #0 'Slot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Slot))
	}
	{ // Static Field #1 'ProposerIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ProposerIndex))
	}
	{ // Static Field #2 'ParentRoot'
		dst = append(dst, t.ParentRoot[:32]...)
	}
	{ // Static Field #3 'StateRoot'
		dst = append(dst, t.StateRoot[:32]...)
	}
	// Offset Field #4 'Body'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #4 'Body'
		binary.LittleEndian.PutUint32(dst[dstlen+80:], uint32(len(dst)-dstlen))
		t := t.Body
		if t == nil {
			t = new(BlindedBeaconBlockBody)
		}
		if viewFn := t.MarshalSSZDynView((*bellatrix.BlindedBeaconBlockBody)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *BlindedBeaconBlock) marshalSSZView_BlindedBeaconBlock_0(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BlindedBeaconBlock)
	}
	dstlen := len(dst)
	{ // Static Field #0 'Slot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Slot))
	}
	{ // Static Field #1 'ProposerIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ProposerIndex))
	}
	{ // Static Field #2 'ParentRoot'
		dst = append(dst, t.ParentRoot[:32]...)
	}
	{ // Static Field #3 'StateRoot'
		dst = append(dst, t.StateRoot[:32]...)
	}
	// Offset Field #4 'Body'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #4 'Body'
		binary.LittleEndian.PutUint32(dst[dstlen+80:], uint32(len(dst)-dstlen))
		t := t.Body
		if t == nil {
			t = new(BlindedBeaconBlockBody)
		}
		if viewFn := t.MarshalSSZDynView((*capella.BlindedBeaconBlockBody)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *BlindedBeaconBlock) marshalSSZView_BlindedBeaconBlock_1(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BlindedBeaconBlock)
	}
	dstlen := len(dst)
	{ // Static Field #0 'Slot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Slot))
	}
	{ // Static Field #1 'ProposerIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ProposerIndex))
	}
	{ // Static Field #2 'ParentRoot'
		dst = append(dst, t.ParentRoot[:32]...)
	}
	{ // Static Field #3 'StateRoot'
		dst = append(dst, t.StateRoot[:32]...)
	}
	// Offset Field #4 'Body'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #4 'Body'
		binary.LittleEndian.PutUint32(dst[dstlen+80:], uint32(len(dst)-dstlen))
		t := t.Body
		if t == nil {
			t = new(BlindedBeaconBlockBody)
		}
		if viewFn := t.MarshalSSZDynView((*deneb.BlindedBeaconBlockBody)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *BlindedBeaconBlock) marshalSSZView_BlindedBeaconBlock_2(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(BlindedBeaconBlock)
	}
	dstlen := len(dst)
	{ // Static Field #0 'Slot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Slot))
	}
	{ // Static Field #1 'ProposerIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ProposerIndex))
	}
	{ // Static Field #2 'ParentRoot'
		dst = append(dst, t.ParentRoot[:32]...)
	}
	{ // Static Field #3 'StateRoot'
		dst = append(dst, t.StateRoot[:32]...)
	}
	// Offset Field #4 'Body'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #4 'Body'
		binary.LittleEndian.PutUint32(dst[dstlen+80:], uint32(len(dst)-dstlen))
		t := t.Body
		if t == nil {
			t = new(BlindedBeaconBlockBody)
		}
		if viewFn := t.MarshalSSZDynView((*electra.BlindedBeaconBlockBody)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *BlindedBeaconBlock) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *bellatrix.BlindedBeaconBlock:
		return t.unmarshalSSZView_BlindedBeaconBlock
	case *capella.BlindedBeaconBlock:
		return t.unmarshalSSZView_BlindedBeaconBlock_0
	case *deneb.BlindedBeaconBlock:
		return t.unmarshalSSZView_BlindedBeaconBlock_1
	case *electra.BlindedBeaconBlock:
		return t.unmarshalSSZView_BlindedBeaconBlock_2
	}
	return nil
}
func (t *BlindedBeaconBlock) unmarshalSSZView_BlindedBeaconBlock(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 84 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 84)
	}
	{ // Field #0 'Slot' (static)
		buf := buf[0:8]
		t.Slot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #1 'ProposerIndex' (static)
		buf := buf[8:16]
		t.ProposerIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #2 'ParentRoot' (static)
		buf := buf[16:48]
		copy(t.ParentRoot[:], buf)
	}
	{ // Field #3 'StateRoot' (static)
		buf := buf[48:80]
		copy(t.StateRoot[:], buf)
	}
	// Field #4 'Body' (offset)
	offset4 := int(binary.LittleEndian.Uint32(buf[80:84]))
	if offset4 != 84 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset4, 84), "Body:o")
	}
	{ // Field #4 'Body' (dynamic)
		buf := buf[offset4:]
		if t.Body == nil {
			t.Body = new(BlindedBeaconBlockBody)
		}
		if viewFn := t.Body.UnmarshalSSZDynView((*bellatrix.BlindedBeaconBlockBody)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *BlindedBeaconBlock) unmarshalSSZView_BlindedBeaconBlock_0(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 84 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 84)
	}
	{ // Field #0 'Slot' (static)
		buf := buf[0:8]
		t.Slot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #1 'ProposerIndex' (static)
		buf := buf[8:16]
		t.ProposerIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #2 'ParentRoot' (static)
		buf := buf[16:48]
		copy(t.ParentRoot[:], buf)
	}
	{ // Field #3 'StateRoot' (static)
		buf := buf[48:80]
		copy(t.StateRoot[:], buf)
	}
	// Field #4 'Body' (offset)
	offset4 := int(binary.LittleEndian.Uint32(buf[80:84]))
	if offset4 != 84 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset4, 84), "Body:o")
	}
	{ // Field #4 'Body' (dynamic)
		buf := buf[offset4:]
		if t.Body == nil {
			t.Body = new(BlindedBeaconBlockBody)
		}
		if viewFn := t.Body.UnmarshalSSZDynView((*capella.BlindedBeaconBlockBody)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *BlindedBeaconBlock) unmarshalSSZView_BlindedBeaconBlock_1(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 84 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 84)
	}
	{ // Field #0 'Slot' (static)
		buf := buf[0:8]
		t.Slot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #1 'ProposerIndex' (static)
		buf := buf[8:16]
		t.ProposerIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #2 'ParentRoot' (static)
		buf := buf[16:48]
		copy(t.ParentRoot[:], buf)
	}
	{ // Field #3 'StateRoot' (static)
		buf := buf[48:80]
		copy(t.StateRoot[:], buf)
	}
	// Field #4 'Body' (offset)
	offset4 := int(binary.LittleEndian.Uint32(buf[80:84]))
	if offset4 != 84 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset4, 84), "Body:o")
	}
	{ // Field #4 'Body' (dynamic)
		buf := buf[offset4:]
		if t.Body == nil {
			t.Body = new(BlindedBeaconBlockBody)
		}
		if viewFn := t.Body.UnmarshalSSZDynView((*deneb.BlindedBeaconBlockBody)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *BlindedBeaconBlock) unmarshalSSZView_BlindedBeaconBlock_2(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 84 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 84)
	}
	{ // Field #0 'Slot' (static)
		buf := buf[0:8]
		t.Slot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #1 'ProposerIndex' (static)
		buf := buf[8:16]
		t.ProposerIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #2 'ParentRoot' (static)
		buf := buf[16:48]
		copy(t.ParentRoot[:], buf)
	}
	{ // Field #3 'StateRoot' (static)
		buf := buf[48:80]
		copy(t.StateRoot[:], buf)
	}
	// Field #4 'Body' (offset)
	offset4 := int(binary.LittleEndian.Uint32(buf[80:84]))
	if offset4 != 84 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset4, 84), "Body:o")
	}
	{ // Field #4 'Body' (dynamic)
		buf := buf[offset4:]
		if t.Body == nil {
			t.Body = new(BlindedBeaconBlockBody)
		}
		if viewFn := t.Body.UnmarshalSSZDynView((*electra.BlindedBeaconBlockBody)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *BlindedBeaconBlock) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *bellatrix.BlindedBeaconBlock:
		return t.sizeSSZView_BlindedBeaconBlock
	case *capella.BlindedBeaconBlock:
		return t.sizeSSZView_BlindedBeaconBlock_0
	case *deneb.BlindedBeaconBlock:
		return t.sizeSSZView_BlindedBeaconBlock_1
	case *electra.BlindedBeaconBlock:
		return t.sizeSSZView_BlindedBeaconBlock_2
	}
	return nil
}
func (t *BlindedBeaconBlock) sizeSSZView_BlindedBeaconBlock(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(BlindedBeaconBlock)
	}
	// Field #0 'Slot' static (8 bytes)
	// Field #1 'ProposerIndex' static (8 bytes)
	// Field #2 'ParentRoot' static (32 bytes)
	// Field #3 'StateRoot' static (32 bytes)
	// Field #4 'Body' offset (4 bytes)
	size += 84
	{ // Dynamic field #4 'Body'
		if viewFn := t.Body.SizeSSZDynView((*bellatrix.BlindedBeaconBlockBody)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *BlindedBeaconBlock) sizeSSZView_BlindedBeaconBlock_0(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(BlindedBeaconBlock)
	}
	// Field #0 'Slot' static (8 bytes)
	// Field #1 'ProposerIndex' static (8 bytes)
	// Field #2 'ParentRoot' static (32 bytes)
	// Field #3 'StateRoot' static (32 bytes)
	// Field #4 'Body' offset (4 bytes)
	size += 84
	{ // Dynamic field #4 'Body'
		if viewFn := t.Body.SizeSSZDynView((*capella.BlindedBeaconBlockBody)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *BlindedBeaconBlock) sizeSSZView_BlindedBeaconBlock_1(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(BlindedBeaconBlock)
	}
	// Field #0 'Slot' static (8 bytes)
	// Field #1 'ProposerIndex' static (8 bytes)
	// Field #2 'ParentRoot' static (32 bytes)
	// Field #3 'StateRoot' static (32 bytes)
	// Field #4 'Body' offset (4 bytes)
	size += 84
	{ // Dynamic field #4 'Body'
		if viewFn := t.Body.SizeSSZDynView((*deneb.BlindedBeaconBlockBody)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *BlindedBeaconBlock) sizeSSZView_BlindedBeaconBlock_2(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(BlindedBeaconBlock)
	}
	// Field #0 'Slot' static (8 bytes)
	// Field #1 'ProposerIndex' static (8 bytes)
	// Field #2 'ParentRoot' static (32 bytes)
	// Field #3 'StateRoot' static (32 bytes)
	// Field #4 'Body' offset (4 bytes)
	size += 84
	{ // Dynamic field #4 'Body'
		if viewFn := t.Body.SizeSSZDynView((*electra.BlindedBeaconBlockBody)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *BlindedBeaconBlock) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *bellatrix.BlindedBeaconBlock:
		return t.hashTreeRootView_BlindedBeaconBlock
	case *capella.BlindedBeaconBlock:
		return t.hashTreeRootView_BlindedBeaconBlock_0
	case *deneb.BlindedBeaconBlock:
		return t.hashTreeRootView_BlindedBeaconBlock_1
	case *electra.BlindedBeaconBlock:
		return t.hashTreeRootView_BlindedBeaconBlock_2
	}
	return nil
}
func (t *BlindedBeaconBlock) hashTreeRootView_BlindedBeaconBlock(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BlindedBeaconBlock)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Slot'
		hh.PutUint64(uint64(t.Slot))
	}
	{ // Field #1 'ProposerIndex'
		hh.PutUint64(uint64(t.ProposerIndex))
	}
	{ // Field #2 'ParentRoot'
		hh.PutBytes(t.ParentRoot[:32])
	}
	{ // Field #3 'StateRoot'
		hh.PutBytes(t.StateRoot[:32])
	}
	{ // Field #4 'Body'
		t := t.Body
		if t == nil {
			t = new(BlindedBeaconBlockBody)
		}
		if viewFn := t.HashTreeRootWithDynView((*bellatrix.BlindedBeaconBlockBody)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	hh.Merkleize(idx)
	return nil
}

func (t *BlindedBeaconBlock) hashTreeRootView_BlindedBeaconBlock_0(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BlindedBeaconBlock)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Slot'
		hh.PutUint64(uint64(t.Slot))
	}
	{ // Field #1 'ProposerIndex'
		hh.PutUint64(uint64(t.ProposerIndex))
	}
	{ // Field #2 'ParentRoot'
		hh.PutBytes(t.ParentRoot[:32])
	}
	{ // Field #3 'StateRoot'
		hh.PutBytes(t.StateRoot[:32])
	}
	{ // Field #4 'Body'
		t := t.Body
		if t == nil {
			t = new(BlindedBeaconBlockBody)
		}
		if viewFn := t.HashTreeRootWithDynView((*capella.BlindedBeaconBlockBody)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	hh.Merkleize(idx)
	return nil
}

func (t *BlindedBeaconBlock) hashTreeRootView_BlindedBeaconBlock_1(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BlindedBeaconBlock)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Slot'
		hh.PutUint64(uint64(t.Slot))
	}
	{ // Field #1 'ProposerIndex'
		hh.PutUint64(uint64(t.ProposerIndex))
	}
	{ // Field #2 'ParentRoot'
		hh.PutBytes(t.ParentRoot[:32])
	}
	{ // Field #3 'StateRoot'
		hh.PutBytes(t.StateRoot[:32])
	}
	{ // Field #4 'Body'
		t := t.Body
		if t == nil {
			t = new(BlindedBeaconBlockBody)
		}
		if viewFn := t.HashTreeRootWithDynView((*deneb.BlindedBeaconBlockBody)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	hh.Merkleize(idx)
	return nil
}

func (t *BlindedBeaconBlock) hashTreeRootView_BlindedBeaconBlock_2(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BlindedBeaconBlock)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Slot'
		hh.PutUint64(uint64(t.Slot))
	}
	{ // Field #1 'ProposerIndex'
		hh.PutUint64(uint64(t.ProposerIndex))
	}
	{ // Field #2 'ParentRoot'
		hh.PutBytes(t.ParentRoot[:32])
	}
	{ // Field #3 'StateRoot'
		hh.PutBytes(t.StateRoot[:32])
	}
	{ // Field #4 'Body'
		t := t.Body
		if t == nil {
			t = new(BlindedBeaconBlockBody)
		}
		if viewFn := t.HashTreeRootWithDynView((*electra.BlindedBeaconBlockBody)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	hh.Merkleize(idx)
	return nil
}
