// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 9c092585480f8f22894396492dade86b4529ce8fdb89f47e624d7dfeae5506c5
// Version: v1.4.0-pre.3 (https://github.com/pk910/dynamic-ssz)

package all

import (
	"encoding/binary"
	"math"

	"github.com/ethpandaops/go-eth2-client/api/v1/deneb"
	"github.com/ethpandaops/go-eth2-client/api/v1/electra"
	"github.com/ethpandaops/go-eth2-client/api/v1/fulu"
	"github.com/ethpandaops/go-eth2-client/spec/all"
	deneb1 "github.com/ethpandaops/go-eth2-client/spec/deneb"
	electra1 "github.com/ethpandaops/go-eth2-client/spec/electra"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[*deneb.BlockContents](`ssz-static:"false"`)
var _ = sszutils.Annotate[*electra.BlockContents](`ssz-static:"false"`)
var _ = sszutils.Annotate[*fulu.BlockContents](`ssz-static:"false"`)

func (t *BlockContents) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *deneb.BlockContents:
		return t.marshalSSZView_BlockContents
	case *electra.BlockContents:
		return t.marshalSSZView_BlockContents_0
	case *fulu.BlockContents:
		return t.marshalSSZView_BlockContents_1
	}
	return nil
}
func (t *BlockContents) marshalSSZView_BlockContents(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return dst, err
	}
	zeroBytes := sszutils.ZeroBytes()
	if t == nil {
		t = new(BlockContents)
	}
	dstlen := len(dst)
	// Offset Field #0 'Block'
	// Offset Field #1 'KZGProofs'
	// Offset Field #2 'Blobs'
	dst = append(dst, zeroBytes[:12]...)
	{ // Dynamic Field #0 'Block'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen:], uint32(off))
		}
		t := t.Block
		if t == nil {
			t = new(all.BeaconBlock)
		}
		if viewFn := t.MarshalSSZDynView((*deneb1.BeaconBlock)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	{ // Dynamic Field #1 'KZGProofs'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(off))
		}
		t := t.KZGProofs
		vlen := len(t)
		if uint64(vlen) > expr0 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "KZGProofs")
		}
		dst = sszutils.MarshalFixedBytesSlice(dst, t[:vlen])
	}
	{ // Dynamic Field #2 'Blobs'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+8:], uint32(off))
		}
		t := t.Blobs
		vlen := len(t)
		if uint64(vlen) > expr0 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "Blobs")
		}
		dst = sszutils.MarshalFixedBytesSlice(dst, t[:vlen])
	}
	return dst, nil
}

func (t *BlockContents) marshalSSZView_BlockContents_0(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return dst, err
	}
	zeroBytes := sszutils.ZeroBytes()
	if t == nil {
		t = new(BlockContents)
	}
	dstlen := len(dst)
	// Offset Field #0 'Block'
	// Offset Field #1 'KZGProofs'
	// Offset Field #2 'Blobs'
	dst = append(dst, zeroBytes[:12]...)
	{ // Dynamic Field #0 'Block'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen:], uint32(off))
		}
		t := t.Block
		if t == nil {
			t = new(all.BeaconBlock)
		}
		if viewFn := t.MarshalSSZDynView((*electra1.BeaconBlock)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	{ // Dynamic Field #1 'KZGProofs'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(off))
		}
		t := t.KZGProofs
		vlen := len(t)
		if uint64(vlen) > expr0 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "KZGProofs")
		}
		dst = sszutils.MarshalFixedBytesSlice(dst, t[:vlen])
	}
	{ // Dynamic Field #2 'Blobs'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+8:], uint32(off))
		}
		t := t.Blobs
		vlen := len(t)
		if uint64(vlen) > expr0 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "Blobs")
		}
		dst = sszutils.MarshalFixedBytesSlice(dst, t[:vlen])
	}
	return dst, nil
}

func (t *BlockContents) marshalSSZView_BlockContents_1(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	zeroBytes := sszutils.ZeroBytes()
	if t == nil {
		t = new(BlockContents)
	}
	dstlen := len(dst)
	// Offset Field #0 'Block'
	// Offset Field #1 'KZGProofs'
	// Offset Field #2 'Blobs'
	dst = append(dst, zeroBytes[:12]...)
	{ // Dynamic Field #0 'Block'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen:], uint32(off))
		}
		t := t.Block
		if t == nil {
			t = new(all.BeaconBlock)
		}
		if viewFn := t.MarshalSSZDynView((*electra1.BeaconBlock)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	{ // Dynamic Field #1 'KZGProofs'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(off))
		}
		t := t.KZGProofs
		vlen := len(t)
		if vlen > 33554432 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 33554432), "KZGProofs")
		}
		dst = sszutils.MarshalFixedBytesSlice(dst, t[:vlen])
	}
	{ // Dynamic Field #2 'Blobs'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+8:], uint32(off))
		}
		t := t.Blobs
		vlen := len(t)
		if vlen > 4096 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 4096), "Blobs")
		}
		dst = sszutils.MarshalFixedBytesSlice(dst, t[:vlen])
	}
	return dst, nil
}

func (t *BlockContents) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *deneb.BlockContents:
		return t.unmarshalSSZView_BlockContents
	case *electra.BlockContents:
		return t.unmarshalSSZView_BlockContents_0
	case *fulu.BlockContents:
		return t.unmarshalSSZView_BlockContents_1
	}
	return nil
}
func (t *BlockContents) unmarshalSSZView_BlockContents(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return err
	}
	buflen := uint64(len(buf))
	if buflen < 12 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 12)
	}
	maxOffset := uint32(sszutils.Min(buflen, math.MaxUint32))
	// Field #0 'Block' (offset)
	offset0 := binary.LittleEndian.Uint32(buf[0:4])
	if offset0 != 12 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 12), "Block:o")
	}
	// Field #1 'KZGProofs' (offset)
	offset1 := binary.LittleEndian.Uint32(buf[4:8])
	if offset1 < offset0 || offset1 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "KZGProofs:o")
	}
	// Field #2 'Blobs' (offset)
	offset2 := binary.LittleEndian.Uint32(buf[8:12])
	if offset2 < offset1 || offset2 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset2, offset1, buflen), "Blobs:o")
	}
	{ // Field #0 'Block' (dynamic)
		buf := buf[offset0:offset1]
		if t.Block == nil {
			t.Block = new(all.BeaconBlock)
		}
		if viewFn := t.Block.UnmarshalSSZDynView((*deneb1.BeaconBlock)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'KZGProofs' (dynamic)
		buf := buf[offset1:offset2]
		val1 := t.KZGProofs
		itemCount := len(buf) / 48
		if len(buf)%48 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 48), "KZGProofs")
		}
		if uint64(itemCount) > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, expr0), "KZGProofs")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		sszutils.UnmarshalFixedBytesSlice(val1[:itemCount], buf)
		t.KZGProofs = val1
	}
	{ // Field #2 'Blobs' (dynamic)
		buf := buf[offset2:]
		val2 := t.Blobs
		itemCount := len(buf) / 131072
		if len(buf)%131072 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 131072), "Blobs")
		}
		if uint64(itemCount) > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, expr0), "Blobs")
		}
		val2 = sszutils.ExpandSlice(val2, itemCount)
		sszutils.UnmarshalFixedBytesSlice(val2[:itemCount], buf)
		t.Blobs = val2
	}
	return nil
}

func (t *BlockContents) unmarshalSSZView_BlockContents_0(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return err
	}
	buflen := uint64(len(buf))
	if buflen < 12 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 12)
	}
	maxOffset := uint32(sszutils.Min(buflen, math.MaxUint32))
	// Field #0 'Block' (offset)
	offset0 := binary.LittleEndian.Uint32(buf[0:4])
	if offset0 != 12 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 12), "Block:o")
	}
	// Field #1 'KZGProofs' (offset)
	offset1 := binary.LittleEndian.Uint32(buf[4:8])
	if offset1 < offset0 || offset1 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "KZGProofs:o")
	}
	// Field #2 'Blobs' (offset)
	offset2 := binary.LittleEndian.Uint32(buf[8:12])
	if offset2 < offset1 || offset2 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset2, offset1, buflen), "Blobs:o")
	}
	{ // Field #0 'Block' (dynamic)
		buf := buf[offset0:offset1]
		if t.Block == nil {
			t.Block = new(all.BeaconBlock)
		}
		if viewFn := t.Block.UnmarshalSSZDynView((*electra1.BeaconBlock)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'KZGProofs' (dynamic)
		buf := buf[offset1:offset2]
		val1 := t.KZGProofs
		itemCount := len(buf) / 48
		if len(buf)%48 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 48), "KZGProofs")
		}
		if uint64(itemCount) > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, expr0), "KZGProofs")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		sszutils.UnmarshalFixedBytesSlice(val1[:itemCount], buf)
		t.KZGProofs = val1
	}
	{ // Field #2 'Blobs' (dynamic)
		buf := buf[offset2:]
		val2 := t.Blobs
		itemCount := len(buf) / 131072
		if len(buf)%131072 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 131072), "Blobs")
		}
		if uint64(itemCount) > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, expr0), "Blobs")
		}
		val2 = sszutils.ExpandSlice(val2, itemCount)
		sszutils.UnmarshalFixedBytesSlice(val2[:itemCount], buf)
		t.Blobs = val2
	}
	return nil
}

func (t *BlockContents) unmarshalSSZView_BlockContents_1(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := uint64(len(buf))
	if buflen < 12 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 12)
	}
	maxOffset := uint32(sszutils.Min(buflen, math.MaxUint32))
	// Field #0 'Block' (offset)
	offset0 := binary.LittleEndian.Uint32(buf[0:4])
	if offset0 != 12 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 12), "Block:o")
	}
	// Field #1 'KZGProofs' (offset)
	offset1 := binary.LittleEndian.Uint32(buf[4:8])
	if offset1 < offset0 || offset1 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "KZGProofs:o")
	}
	// Field #2 'Blobs' (offset)
	offset2 := binary.LittleEndian.Uint32(buf[8:12])
	if offset2 < offset1 || offset2 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset2, offset1, buflen), "Blobs:o")
	}
	{ // Field #0 'Block' (dynamic)
		buf := buf[offset0:offset1]
		if t.Block == nil {
			t.Block = new(all.BeaconBlock)
		}
		if viewFn := t.Block.UnmarshalSSZDynView((*electra1.BeaconBlock)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'KZGProofs' (dynamic)
		buf := buf[offset1:offset2]
		val1 := t.KZGProofs
		itemCount := len(buf) / 48
		if len(buf)%48 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 48), "KZGProofs")
		}
		if itemCount > 33554432 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 33554432), "KZGProofs")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		sszutils.UnmarshalFixedBytesSlice(val1[:itemCount], buf)
		t.KZGProofs = val1
	}
	{ // Field #2 'Blobs' (dynamic)
		buf := buf[offset2:]
		val2 := t.Blobs
		itemCount := len(buf) / 131072
		if len(buf)%131072 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 131072), "Blobs")
		}
		if itemCount > 4096 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 4096), "Blobs")
		}
		val2 = sszutils.ExpandSlice(val2, itemCount)
		sszutils.UnmarshalFixedBytesSlice(val2[:itemCount], buf)
		t.Blobs = val2
	}
	return nil
}

func (t *BlockContents) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *deneb.BlockContents:
		return t.sizeSSZView_BlockContents
	case *electra.BlockContents:
		return t.sizeSSZView_BlockContents_0
	case *fulu.BlockContents:
		return t.sizeSSZView_BlockContents_1
	}
	return nil
}
func (t *BlockContents) sizeSSZView_BlockContents(ds sszutils.DynamicSpecs) int {
	var size int64
	if t == nil {
		t = new(BlockContents)
	}
	// Field #0 'Block' offset (4 bytes)
	// Field #1 'KZGProofs' offset (4 bytes)
	// Field #2 'Blobs' offset (4 bytes)
	size += 12
	{ // Dynamic field #0 'Block'
		if viewFn := t.Block.SizeSSZDynView((*deneb1.BeaconBlock)(nil)); viewFn != nil {
			s1 := int64(viewFn(ds))
			if s1 < 0 {
				return -1
			}
			size += s1
		}
	}
	{ // Dynamic field #1 'KZGProofs'
		size += int64(len(t.KZGProofs)) * 48
	}
	{ // Dynamic field #2 'Blobs'
		size += int64(len(t.Blobs)) * 131072
	}
	if uint64(size) > sszutils.MaxSszSize {
		return -1
	}
	return int(size)
}

func (t *BlockContents) sizeSSZView_BlockContents_0(ds sszutils.DynamicSpecs) int {
	var size int64
	if t == nil {
		t = new(BlockContents)
	}
	// Field #0 'Block' offset (4 bytes)
	// Field #1 'KZGProofs' offset (4 bytes)
	// Field #2 'Blobs' offset (4 bytes)
	size += 12
	{ // Dynamic field #0 'Block'
		if viewFn := t.Block.SizeSSZDynView((*electra1.BeaconBlock)(nil)); viewFn != nil {
			s1 := int64(viewFn(ds))
			if s1 < 0 {
				return -1
			}
			size += s1
		}
	}
	{ // Dynamic field #1 'KZGProofs'
		size += int64(len(t.KZGProofs)) * 48
	}
	{ // Dynamic field #2 'Blobs'
		size += int64(len(t.Blobs)) * 131072
	}
	if uint64(size) > sszutils.MaxSszSize {
		return -1
	}
	return int(size)
}

func (t *BlockContents) sizeSSZView_BlockContents_1(ds sszutils.DynamicSpecs) int {
	var size int64
	if t == nil {
		t = new(BlockContents)
	}
	// Field #0 'Block' offset (4 bytes)
	// Field #1 'KZGProofs' offset (4 bytes)
	// Field #2 'Blobs' offset (4 bytes)
	size += 12
	{ // Dynamic field #0 'Block'
		if viewFn := t.Block.SizeSSZDynView((*electra1.BeaconBlock)(nil)); viewFn != nil {
			s1 := int64(viewFn(ds))
			if s1 < 0 {
				return -1
			}
			size += s1
		}
	}
	{ // Dynamic field #1 'KZGProofs'
		size += int64(len(t.KZGProofs)) * 48
	}
	{ // Dynamic field #2 'Blobs'
		size += int64(len(t.Blobs)) * 131072
	}
	if uint64(size) > sszutils.MaxSszSize {
		return -1
	}
	return int(size)
}

func (t *BlockContents) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *deneb.BlockContents:
		return t.hashTreeRootView_BlockContents
	case *electra.BlockContents:
		return t.hashTreeRootView_BlockContents_0
	case *fulu.BlockContents:
		return t.hashTreeRootView_BlockContents_1
	}
	return nil
}
func (t *BlockContents) hashTreeRootView_BlockContents(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(BlockContents)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Block'
		t := t.Block
		if t == nil {
			t = new(all.BeaconBlock)
		}
		if viewFn := t.HashTreeRootWithDynView((*deneb1.BeaconBlock)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'KZGProofs'
		t := t.KZGProofs
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "KZGProofs")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range len(t) {
			hh.PutBytes(t[idx1][:48])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	{ // Field #2 'Blobs'
		t := t.Blobs
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "Blobs")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range len(t) {
			hh.PutBytes(t[idx1][:131072])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}

func (t *BlockContents) hashTreeRootView_BlockContents_0(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(BlockContents)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Block'
		t := t.Block
		if t == nil {
			t = new(all.BeaconBlock)
		}
		if viewFn := t.HashTreeRootWithDynView((*electra1.BeaconBlock)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'KZGProofs'
		t := t.KZGProofs
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "KZGProofs")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range len(t) {
			hh.PutBytes(t[idx1][:48])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	{ // Field #2 'Blobs'
		t := t.Blobs
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "Blobs")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range len(t) {
			hh.PutBytes(t[idx1][:131072])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}

func (t *BlockContents) hashTreeRootView_BlockContents_1(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BlockContents)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Block'
		t := t.Block
		if t == nil {
			t = new(all.BeaconBlock)
		}
		if viewFn := t.HashTreeRootWithDynView((*electra1.BeaconBlock)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'KZGProofs'
		t := t.KZGProofs
		vlen := uint64(len(t))
		if vlen > 33554432 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 33554432), "KZGProofs")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range len(t) {
			hh.PutBytes(t[idx1][:48])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(33554432, vlen, 32))
	}
	{ // Field #2 'Blobs'
		t := t.Blobs
		vlen := uint64(len(t))
		if vlen > 4096 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 4096), "Blobs")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range len(t) {
			hh.PutBytes(t[idx1][:131072])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(4096, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
