// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 14e2fae0399103d307cf7c74d1edfda92ee5450994dc6089b4446162ed3391f4
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
package all

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth2-client/api/v1/bellatrix"
	"github.com/ethpandaops/go-eth2-client/api/v1/capella"
	"github.com/ethpandaops/go-eth2-client/api/v1/deneb"
	"github.com/ethpandaops/go-eth2-client/api/v1/electra"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[*bellatrix.SignedBlindedBeaconBlock](`ssz-static:"false"`)
var _ = sszutils.Annotate[*capella.SignedBlindedBeaconBlock](`ssz-static:"false"`)
var _ = sszutils.Annotate[*deneb.SignedBlindedBeaconBlock](`ssz-static:"false"`)
var _ = sszutils.Annotate[*electra.SignedBlindedBeaconBlock](`ssz-static:"false"`)

func (t *SignedBlindedBeaconBlock) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *bellatrix.SignedBlindedBeaconBlock:
		return t.marshalSSZView_SignedBlindedBeaconBlock
	case *capella.SignedBlindedBeaconBlock:
		return t.marshalSSZView_SignedBlindedBeaconBlock_0
	case *deneb.SignedBlindedBeaconBlock:
		return t.marshalSSZView_SignedBlindedBeaconBlock_1
	case *electra.SignedBlindedBeaconBlock:
		return t.marshalSSZView_SignedBlindedBeaconBlock_2
	}
	return nil
}
func (t *SignedBlindedBeaconBlock) marshalSSZView_SignedBlindedBeaconBlock(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedBlindedBeaconBlock)
	}
	dstlen := len(dst)
	// Offset Field #0 'Message'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'Message'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Message
		if t == nil {
			t = new(BlindedBeaconBlock)
		}
		if viewFn := t.MarshalSSZDynView((*bellatrix.BlindedBeaconBlock)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *SignedBlindedBeaconBlock) marshalSSZView_SignedBlindedBeaconBlock_0(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedBlindedBeaconBlock)
	}
	dstlen := len(dst)
	// Offset Field #0 'Message'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'Message'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Message
		if t == nil {
			t = new(BlindedBeaconBlock)
		}
		if viewFn := t.MarshalSSZDynView((*capella.BlindedBeaconBlock)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *SignedBlindedBeaconBlock) marshalSSZView_SignedBlindedBeaconBlock_1(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedBlindedBeaconBlock)
	}
	dstlen := len(dst)
	// Offset Field #0 'Message'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'Message'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Message
		if t == nil {
			t = new(BlindedBeaconBlock)
		}
		if viewFn := t.MarshalSSZDynView((*deneb.BlindedBeaconBlock)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *SignedBlindedBeaconBlock) marshalSSZView_SignedBlindedBeaconBlock_2(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedBlindedBeaconBlock)
	}
	dstlen := len(dst)
	// Offset Field #0 'Message'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'Message'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.Message
		if t == nil {
			t = new(BlindedBeaconBlock)
		}
		if viewFn := t.MarshalSSZDynView((*electra.BlindedBeaconBlock)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *SignedBlindedBeaconBlock) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *bellatrix.SignedBlindedBeaconBlock:
		return t.unmarshalSSZView_SignedBlindedBeaconBlock
	case *capella.SignedBlindedBeaconBlock:
		return t.unmarshalSSZView_SignedBlindedBeaconBlock_0
	case *deneb.SignedBlindedBeaconBlock:
		return t.unmarshalSSZView_SignedBlindedBeaconBlock_1
	case *electra.SignedBlindedBeaconBlock:
		return t.unmarshalSSZView_SignedBlindedBeaconBlock_2
	}
	return nil
}
func (t *SignedBlindedBeaconBlock) unmarshalSSZView_SignedBlindedBeaconBlock(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	// Field #0 'Message' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 100), "Message:o")
	}
	{ // Field #1 'Signature' (static)
		buf := buf[4:100]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'Message' (dynamic)
		buf := buf[offset0:]
		if t.Message == nil {
			t.Message = new(BlindedBeaconBlock)
		}
		if viewFn := t.Message.UnmarshalSSZDynView((*bellatrix.BlindedBeaconBlock)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *SignedBlindedBeaconBlock) unmarshalSSZView_SignedBlindedBeaconBlock_0(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	// Field #0 'Message' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 100), "Message:o")
	}
	{ // Field #1 'Signature' (static)
		buf := buf[4:100]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'Message' (dynamic)
		buf := buf[offset0:]
		if t.Message == nil {
			t.Message = new(BlindedBeaconBlock)
		}
		if viewFn := t.Message.UnmarshalSSZDynView((*capella.BlindedBeaconBlock)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *SignedBlindedBeaconBlock) unmarshalSSZView_SignedBlindedBeaconBlock_1(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	// Field #0 'Message' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 100), "Message:o")
	}
	{ // Field #1 'Signature' (static)
		buf := buf[4:100]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'Message' (dynamic)
		buf := buf[offset0:]
		if t.Message == nil {
			t.Message = new(BlindedBeaconBlock)
		}
		if viewFn := t.Message.UnmarshalSSZDynView((*deneb.BlindedBeaconBlock)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *SignedBlindedBeaconBlock) unmarshalSSZView_SignedBlindedBeaconBlock_2(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	// Field #0 'Message' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 100), "Message:o")
	}
	{ // Field #1 'Signature' (static)
		buf := buf[4:100]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'Message' (dynamic)
		buf := buf[offset0:]
		if t.Message == nil {
			t.Message = new(BlindedBeaconBlock)
		}
		if viewFn := t.Message.UnmarshalSSZDynView((*electra.BlindedBeaconBlock)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *SignedBlindedBeaconBlock) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *bellatrix.SignedBlindedBeaconBlock:
		return t.sizeSSZView_SignedBlindedBeaconBlock
	case *capella.SignedBlindedBeaconBlock:
		return t.sizeSSZView_SignedBlindedBeaconBlock_0
	case *deneb.SignedBlindedBeaconBlock:
		return t.sizeSSZView_SignedBlindedBeaconBlock_1
	case *electra.SignedBlindedBeaconBlock:
		return t.sizeSSZView_SignedBlindedBeaconBlock_2
	}
	return nil
}
func (t *SignedBlindedBeaconBlock) sizeSSZView_SignedBlindedBeaconBlock(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(SignedBlindedBeaconBlock)
	}
	// Field #0 'Message' offset (4 bytes)
	// Field #1 'Signature' static (96 bytes)
	size += 100
	{ // Dynamic field #0 'Message'
		if viewFn := t.Message.SizeSSZDynView((*bellatrix.BlindedBeaconBlock)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *SignedBlindedBeaconBlock) sizeSSZView_SignedBlindedBeaconBlock_0(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(SignedBlindedBeaconBlock)
	}
	// Field #0 'Message' offset (4 bytes)
	// Field #1 'Signature' static (96 bytes)
	size += 100
	{ // Dynamic field #0 'Message'
		if viewFn := t.Message.SizeSSZDynView((*capella.BlindedBeaconBlock)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *SignedBlindedBeaconBlock) sizeSSZView_SignedBlindedBeaconBlock_1(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(SignedBlindedBeaconBlock)
	}
	// Field #0 'Message' offset (4 bytes)
	// Field #1 'Signature' static (96 bytes)
	size += 100
	{ // Dynamic field #0 'Message'
		if viewFn := t.Message.SizeSSZDynView((*deneb.BlindedBeaconBlock)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *SignedBlindedBeaconBlock) sizeSSZView_SignedBlindedBeaconBlock_2(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(SignedBlindedBeaconBlock)
	}
	// Field #0 'Message' offset (4 bytes)
	// Field #1 'Signature' static (96 bytes)
	size += 100
	{ // Dynamic field #0 'Message'
		if viewFn := t.Message.SizeSSZDynView((*electra.BlindedBeaconBlock)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *SignedBlindedBeaconBlock) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *bellatrix.SignedBlindedBeaconBlock:
		return t.hashTreeRootView_SignedBlindedBeaconBlock
	case *capella.SignedBlindedBeaconBlock:
		return t.hashTreeRootView_SignedBlindedBeaconBlock_0
	case *deneb.SignedBlindedBeaconBlock:
		return t.hashTreeRootView_SignedBlindedBeaconBlock_1
	case *electra.SignedBlindedBeaconBlock:
		return t.hashTreeRootView_SignedBlindedBeaconBlock_2
	}
	return nil
}
func (t *SignedBlindedBeaconBlock) hashTreeRootView_SignedBlindedBeaconBlock(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedBlindedBeaconBlock)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(BlindedBeaconBlock)
		}
		if viewFn := t.HashTreeRootWithDynView((*bellatrix.BlindedBeaconBlock)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *SignedBlindedBeaconBlock) hashTreeRootView_SignedBlindedBeaconBlock_0(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedBlindedBeaconBlock)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(BlindedBeaconBlock)
		}
		if viewFn := t.HashTreeRootWithDynView((*capella.BlindedBeaconBlock)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *SignedBlindedBeaconBlock) hashTreeRootView_SignedBlindedBeaconBlock_1(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedBlindedBeaconBlock)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(BlindedBeaconBlock)
		}
		if viewFn := t.HashTreeRootWithDynView((*deneb.BlindedBeaconBlock)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}

func (t *SignedBlindedBeaconBlock) hashTreeRootView_SignedBlindedBeaconBlock_2(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedBlindedBeaconBlock)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(BlindedBeaconBlock)
		}
		if viewFn := t.HashTreeRootWithDynView((*electra.BlindedBeaconBlock)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}
