// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 5b7fb50c28e1ae8e4c34c1f57b1796866bd1bbf374b26684f8d360f7eaf460a7
// Version: v1.4.0-pre.3 (https://github.com/pk910/dynamic-ssz)

package all

import (
	"encoding/binary"
	"math"

	"github.com/ethpandaops/go-eth2-client/api/v1/gloas"
	"github.com/ethpandaops/go-eth2-client/spec/all"
	gloas1 "github.com/ethpandaops/go-eth2-client/spec/gloas"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[*gloas.SignedExecutionPayloadEnvelopeContents](`ssz-static:"false"`)

func (t *SignedExecutionPayloadEnvelopeContents) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *gloas.SignedExecutionPayloadEnvelopeContents:
		return t.marshalSSZView_SignedExecutionPayloadEnvelopeContents
	}
	return nil
}
func (t *SignedExecutionPayloadEnvelopeContents) marshalSSZView_SignedExecutionPayloadEnvelopeContents(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "FIELD_ELEMENTS_PER_EXT_BLOB*MAX_BLOB_COMMITMENTS_PER_BLOCK", 33554432)
	if err != nil {
		return dst, err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return dst, err
	}
	zeroBytes := sszutils.ZeroBytes()
	if t == nil {
		t = new(SignedExecutionPayloadEnvelopeContents)
	}
	dstlen := len(dst)
	// Offset Field #0 'SignedExecutionPayloadEnvelope'
	// Offset Field #1 'KZGProofs'
	// Offset Field #2 'Blobs'
	dst = append(dst, zeroBytes[:12]...)
	{ // Dynamic Field #0 'SignedExecutionPayloadEnvelope'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen:], uint32(off))
		}
		t := t.SignedExecutionPayloadEnvelope
		if t == nil {
			t = new(all.SignedExecutionPayloadEnvelope)
		}
		if viewFn := t.MarshalSSZDynView((*gloas1.SignedExecutionPayloadEnvelope)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	{ // Dynamic Field #1 'KZGProofs'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(off))
		}
		t := t.KZGProofs
		vlen := len(t)
		if uint64(vlen) > expr0 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "KZGProofs")
		}
		dst = sszutils.MarshalFixedBytesSlice(dst, t[:vlen])
	}
	{ // Dynamic Field #2 'Blobs'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+8:], uint32(off))
		}
		t := t.Blobs
		vlen := len(t)
		if uint64(vlen) > expr1 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr1), "Blobs")
		}
		dst = sszutils.MarshalFixedBytesSlice(dst, t[:vlen])
	}
	return dst, nil
}

func (t *SignedExecutionPayloadEnvelopeContents) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *gloas.SignedExecutionPayloadEnvelopeContents:
		return t.unmarshalSSZView_SignedExecutionPayloadEnvelopeContents
	}
	return nil
}
func (t *SignedExecutionPayloadEnvelopeContents) unmarshalSSZView_SignedExecutionPayloadEnvelopeContents(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "FIELD_ELEMENTS_PER_EXT_BLOB*MAX_BLOB_COMMITMENTS_PER_BLOCK", 33554432)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return err
	}
	buflen := uint64(len(buf))
	if buflen < 12 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 12)
	}
	maxOffset := uint32(sszutils.Min(buflen, math.MaxUint32))
	// Field #0 'SignedExecutionPayloadEnvelope' (offset)
	offset0 := binary.LittleEndian.Uint32(buf[0:4])
	if offset0 != 12 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 12), "SignedExecutionPayloadEnvelope:o")
	}
	// Field #1 'KZGProofs' (offset)
	offset1 := binary.LittleEndian.Uint32(buf[4:8])
	if offset1 < offset0 || offset1 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "KZGProofs:o")
	}
	// Field #2 'Blobs' (offset)
	offset2 := binary.LittleEndian.Uint32(buf[8:12])
	if offset2 < offset1 || offset2 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset2, offset1, buflen), "Blobs:o")
	}
	{ // Field #0 'SignedExecutionPayloadEnvelope' (dynamic)
		buf := buf[offset0:offset1]
		if t.SignedExecutionPayloadEnvelope == nil {
			t.SignedExecutionPayloadEnvelope = new(all.SignedExecutionPayloadEnvelope)
		}
		if viewFn := t.SignedExecutionPayloadEnvelope.UnmarshalSSZDynView((*gloas1.SignedExecutionPayloadEnvelope)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'KZGProofs' (dynamic)
		buf := buf[offset1:offset2]
		val1 := t.KZGProofs
		itemCount := len(buf) / 48
		if len(buf)%48 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 48), "KZGProofs")
		}
		if uint64(itemCount) > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, expr0), "KZGProofs")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		sszutils.UnmarshalFixedBytesSlice(val1[:itemCount], buf)
		t.KZGProofs = val1
	}
	{ // Field #2 'Blobs' (dynamic)
		buf := buf[offset2:]
		val2 := t.Blobs
		itemCount := len(buf) / 131072
		if len(buf)%131072 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 131072), "Blobs")
		}
		if uint64(itemCount) > expr1 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, expr1), "Blobs")
		}
		val2 = sszutils.ExpandSlice(val2, itemCount)
		sszutils.UnmarshalFixedBytesSlice(val2[:itemCount], buf)
		t.Blobs = val2
	}
	return nil
}

func (t *SignedExecutionPayloadEnvelopeContents) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *gloas.SignedExecutionPayloadEnvelopeContents:
		return t.sizeSSZView_SignedExecutionPayloadEnvelopeContents
	}
	return nil
}
func (t *SignedExecutionPayloadEnvelopeContents) sizeSSZView_SignedExecutionPayloadEnvelopeContents(ds sszutils.DynamicSpecs) int {
	var size int64
	if t == nil {
		t = new(SignedExecutionPayloadEnvelopeContents)
	}
	// Field #0 'SignedExecutionPayloadEnvelope' offset (4 bytes)
	// Field #1 'KZGProofs' offset (4 bytes)
	// Field #2 'Blobs' offset (4 bytes)
	size += 12
	{ // Dynamic field #0 'SignedExecutionPayloadEnvelope'
		if viewFn := t.SignedExecutionPayloadEnvelope.SizeSSZDynView((*gloas1.SignedExecutionPayloadEnvelope)(nil)); viewFn != nil {
			s1 := int64(viewFn(ds))
			if s1 < 0 {
				return -1
			}
			size += s1
		}
	}
	{ // Dynamic field #1 'KZGProofs'
		size += int64(len(t.KZGProofs)) * 48
	}
	{ // Dynamic field #2 'Blobs'
		size += int64(len(t.Blobs)) * 131072
	}
	if uint64(size) > sszutils.MaxSszSize {
		return -1
	}
	return int(size)
}

func (t *SignedExecutionPayloadEnvelopeContents) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *gloas.SignedExecutionPayloadEnvelopeContents:
		return t.hashTreeRootView_SignedExecutionPayloadEnvelopeContents
	}
	return nil
}
func (t *SignedExecutionPayloadEnvelopeContents) hashTreeRootView_SignedExecutionPayloadEnvelopeContents(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "FIELD_ELEMENTS_PER_EXT_BLOB*MAX_BLOB_COMMITMENTS_PER_BLOCK", 33554432)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(SignedExecutionPayloadEnvelopeContents)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'SignedExecutionPayloadEnvelope'
		t := t.SignedExecutionPayloadEnvelope
		if t == nil {
			t = new(all.SignedExecutionPayloadEnvelope)
		}
		if viewFn := t.HashTreeRootWithDynView((*gloas1.SignedExecutionPayloadEnvelope)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'KZGProofs'
		t := t.KZGProofs
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "KZGProofs")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range len(t) {
			hh.PutBytes(t[idx1][:48])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	{ // Field #2 'Blobs'
		t := t.Blobs
		vlen := uint64(len(t))
		if vlen > expr1 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr1), "Blobs")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range len(t) {
			hh.PutBytes(t[idx1][:131072])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr1, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
