// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: f3c91fa730a723f211a7b35fe312c487d88c538a0582764fc375b93cf20028c7
// Version: v1.3.2 (https://github.com/pk910/dynamic-ssz)
package all

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth2-client/api/v1/gloas"
	"github.com/ethpandaops/go-eth2-client/spec/all"
	"github.com/ethpandaops/go-eth2-client/spec/capella"
	"github.com/ethpandaops/go-eth2-client/spec/electra"
	gloas1 "github.com/ethpandaops/go-eth2-client/spec/gloas"
	"github.com/holiman/uint256"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[*gloas.SignedExecutionPayloadEnvelopeContents](`ssz-static:"false"`)

func (t *SignedExecutionPayloadEnvelopeContents) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *gloas.SignedExecutionPayloadEnvelopeContents:
		return t.marshalSSZView_SignedExecutionPayloadEnvelopeContents
	}
	return nil
}
func (t *SignedExecutionPayloadEnvelopeContents) marshalSSZView_SignedExecutionPayloadEnvelopeContents(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXTRA_DATA_BYTES", 32)
	if err != nil {
		return dst, err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_TRANSACTIONS_PER_PAYLOAD", 1048576)
	if err != nil {
		return dst, err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return dst, err
	}
	expr3, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWALS_PER_PAYLOAD", 16)
	if err != nil {
		return dst, err
	}
	expr4, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_DEPOSIT_REQUESTS_PER_PAYLOAD", 8192)
	if err != nil {
		return dst, err
	}
	expr5, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWAL_REQUESTS_PER_PAYLOAD", 16)
	if err != nil {
		return dst, err
	}
	expr6, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_CONSOLIDATION_REQUESTS_PER_PAYLOAD", 2)
	if err != nil {
		return dst, err
	}
	expr7, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BUILDER_DEPOSIT_REQUESTS_PER_PAYLOAD", 256)
	if err != nil {
		return dst, err
	}
	expr8, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BUILDER_EXIT_REQUESTS_PER_PAYLOAD", 16)
	if err != nil {
		return dst, err
	}
	expr9, err := sszutils.ResolveSpecValueWithDefault(ds, "FIELD_ELEMENTS_PER_EXT_BLOB*MAX_BLOB_COMMITMENTS_PER_BLOCK", 33554432)
	if err != nil {
		return dst, err
	}
	expr10, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return dst, err
	}
	zeroBytes := sszutils.ZeroBytes()
	if t == nil {
		t = new(SignedExecutionPayloadEnvelopeContents)
	}
	dstlen := len(dst)
	// Offset Field #0 'SignedExecutionPayloadEnvelope'
	// Offset Field #1 'KZGProofs'
	// Offset Field #2 'Blobs'
	dst = append(dst, zeroBytes[:12]...)
	{ // Dynamic Field #0 'SignedExecutionPayloadEnvelope'
		binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
		t := t.SignedExecutionPayloadEnvelope
		if t == nil {
			t = new(all.SignedExecutionPayloadEnvelope)
		}
		dstlen := len(dst)
		// Offset Field #0 'Message'
		dst = append(dst, 0, 0, 0, 0)
		{ // Static Field #1 'Signature'
			dst = append(dst, t.Signature[:96]...)
		}
		{ // Dynamic Field #0 'Message'
			binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
			t := t.Message
			if t == nil {
				t = new(all.ExecutionPayloadEnvelope)
			}
			dstlen := len(dst)
			// Offset Field #0 'Payload'
			// Offset Field #1 'ExecutionRequests'
			dst = append(dst, 0, 0, 0, 0, 0, 0, 0, 0)
			{ // Static Field #2 'BuilderIndex'
				dst = binary.LittleEndian.AppendUint64(dst, uint64(t.BuilderIndex))
			}
			{ // Static Field #3 'BeaconBlockRoot'
				dst = append(dst, t.BeaconBlockRoot[:32]...)
			}
			{ // Static Field #4 'ParentBeaconBlockRoot'
				dst = append(dst, t.ParentBeaconBlockRoot[:32]...)
			}
			{ // Dynamic Field #0 'Payload'
				binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
				t := t.Payload
				if t == nil {
					t = new(all.ExecutionPayload)
				}
				dstlen := len(dst)
				{ // Static Field #0 'ParentHash'
					dst = append(dst, t.ParentHash[:32]...)
				}
				{ // Static Field #1 'FeeRecipient'
					dst = append(dst, t.FeeRecipient[:20]...)
				}
				{ // Static Field #2 'StateRoot'
					dst = append(dst, t.StateRoot[:32]...)
				}
				{ // Static Field #3 'ReceiptsRoot'
					dst = append(dst, t.ReceiptsRoot[:32]...)
				}
				{ // Static Field #4 'LogsBloom'
					dst = append(dst, t.LogsBloom[:256]...)
				}
				{ // Static Field #5 'PrevRandao'
					dst = append(dst, t.PrevRandao[:32]...)
				}
				{ // Static Field #6 'BlockNumber'
					dst = binary.LittleEndian.AppendUint64(dst, t.BlockNumber)
				}
				{ // Static Field #7 'GasLimit'
					dst = binary.LittleEndian.AppendUint64(dst, t.GasLimit)
				}
				{ // Static Field #8 'GasUsed'
					dst = binary.LittleEndian.AppendUint64(dst, t.GasUsed)
				}
				{ // Static Field #9 'Timestamp'
					dst = binary.LittleEndian.AppendUint64(dst, t.Timestamp)
				}
				// Offset Field #10 'ExtraData'
				dst = append(dst, 0, 0, 0, 0)
				{ // Static Field #11 'BaseFeePerGas'
					t := t.BaseFeePerGas
					if t == nil {
						t = new(uint256.Int)
					}
					dst = sszutils.MarshalUint64Slice(dst, (*t)[:4])
				}
				{ // Static Field #12 'BlockHash'
					dst = append(dst, t.BlockHash[:32]...)
				}
				// Offset Field #13 'Transactions'
				// Offset Field #14 'Withdrawals'
				dst = append(dst, 0, 0, 0, 0, 0, 0, 0, 0)
				{ // Static Field #15 'BlobGasUsed'
					dst = binary.LittleEndian.AppendUint64(dst, t.BlobGasUsed)
				}
				{ // Static Field #16 'ExcessBlobGas'
					dst = binary.LittleEndian.AppendUint64(dst, t.ExcessBlobGas)
				}
				// Offset Field #17 'BlockAccessList'
				dst = append(dst, 0, 0, 0, 0)
				{ // Static Field #18 'SlotNumber'
					dst = binary.LittleEndian.AppendUint64(dst, t.SlotNumber)
				}
				{ // Dynamic Field #10 'ExtraData'
					binary.LittleEndian.PutUint32(dst[dstlen+436:], uint32(len(dst)-dstlen))
					vlen := len(t.ExtraData)
					if vlen > int(expr0) {
						return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr0)), "SignedExecutionPayloadEnvelope.Message.Payload.ExtraData")
					}
					dst = append(dst, t.ExtraData[:]...)
				}
				{ // Dynamic Field #13 'Transactions'
					binary.LittleEndian.PutUint32(dst[dstlen+504:], uint32(len(dst)-dstlen))
					t := t.Transactions
					vlen := len(t)
					if vlen > int(expr1) {
						return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr1)), "SignedExecutionPayloadEnvelope.Message.Payload.Transactions")
					}
					dstlen := len(dst)
					dst = sszutils.AppendZeroPadding(dst, vlen*4)
					for idx1 := range vlen {
						binary.LittleEndian.PutUint32(dst[dstlen+(idx1*4):], uint32(len(dst)-dstlen))
						vlen := len(t[idx1])
						if vlen > int(expr2) {
							return nil, sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, int(expr2)), "SignedExecutionPayloadEnvelope.Message.Payload.Transactions[%d]", idx1)
						}
						dst = append(dst, t[idx1][:]...)
					}
				}
				{ // Dynamic Field #14 'Withdrawals'
					binary.LittleEndian.PutUint32(dst[dstlen+508:], uint32(len(dst)-dstlen))
					t := t.Withdrawals
					vlen := len(t)
					if vlen > int(expr3) {
						return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr3)), "SignedExecutionPayloadEnvelope.Message.Payload.Withdrawals")
					}
					for idx1 := range vlen {
						t := t[idx1]
						if t == nil {
							t = new(capella.Withdrawal)
						}
						if dst, err = t.MarshalSSZTo(dst); err != nil {
							return nil, sszutils.ErrorWithPathf(err, "SignedExecutionPayloadEnvelope.Message.Payload.Withdrawals[%d]", idx1)
						}
					}
				}
				{ // Dynamic Field #17 'BlockAccessList'
					binary.LittleEndian.PutUint32(dst[dstlen+528:], uint32(len(dst)-dstlen))
					vlen := len(t.BlockAccessList)
					if vlen > int(expr2) {
						return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr2)), "SignedExecutionPayloadEnvelope.Message.Payload.BlockAccessList")
					}
					dst = append(dst, t.BlockAccessList[:]...)
				}
			}
			{ // Dynamic Field #1 'ExecutionRequests'
				binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(len(dst)-dstlen))
				t := t.ExecutionRequests
				if t == nil {
					t = new(all.ExecutionRequests)
				}
				dstlen := len(dst)
				// Offset Field #0 'Deposits'
				// Offset Field #1 'Withdrawals'
				// Offset Field #2 'Consolidations'
				// Offset Field #3 'BuilderDeposits'
				// Offset Field #4 'BuilderExits'
				dst = append(dst, zeroBytes[:20]...)
				{ // Dynamic Field #0 'Deposits'
					binary.LittleEndian.PutUint32(dst[dstlen:], uint32(len(dst)-dstlen))
					t := t.Deposits
					vlen := len(t)
					if vlen > int(expr4) {
						return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr4)), "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Deposits")
					}
					for idx1 := range vlen {
						t := t[idx1]
						if t == nil {
							t = new(electra.DepositRequest)
						}
						if dst, err = t.MarshalSSZTo(dst); err != nil {
							return nil, sszutils.ErrorWithPathf(err, "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Deposits[%d]", idx1)
						}
					}
				}
				{ // Dynamic Field #1 'Withdrawals'
					binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(len(dst)-dstlen))
					t := t.Withdrawals
					vlen := len(t)
					if vlen > int(expr5) {
						return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr5)), "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Withdrawals")
					}
					for idx1 := range vlen {
						t := t[idx1]
						if t == nil {
							t = new(electra.WithdrawalRequest)
						}
						if dst, err = t.MarshalSSZTo(dst); err != nil {
							return nil, sszutils.ErrorWithPathf(err, "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Withdrawals[%d]", idx1)
						}
					}
				}
				{ // Dynamic Field #2 'Consolidations'
					binary.LittleEndian.PutUint32(dst[dstlen+8:], uint32(len(dst)-dstlen))
					t := t.Consolidations
					vlen := len(t)
					if vlen > int(expr6) {
						return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr6)), "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Consolidations")
					}
					for idx1 := range vlen {
						t := t[idx1]
						if t == nil {
							t = new(electra.ConsolidationRequest)
						}
						if dst, err = t.MarshalSSZTo(dst); err != nil {
							return nil, sszutils.ErrorWithPathf(err, "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Consolidations[%d]", idx1)
						}
					}
				}
				{ // Dynamic Field #3 'BuilderDeposits'
					binary.LittleEndian.PutUint32(dst[dstlen+12:], uint32(len(dst)-dstlen))
					t := t.BuilderDeposits
					vlen := len(t)
					if vlen > int(expr7) {
						return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr7)), "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.BuilderDeposits")
					}
					for idx1 := range vlen {
						t := t[idx1]
						if t == nil {
							t = new(gloas1.BuilderDepositRequest)
						}
						if dst, err = t.MarshalSSZTo(dst); err != nil {
							return nil, sszutils.ErrorWithPathf(err, "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.BuilderDeposits[%d]", idx1)
						}
					}
				}
				{ // Dynamic Field #4 'BuilderExits'
					binary.LittleEndian.PutUint32(dst[dstlen+16:], uint32(len(dst)-dstlen))
					t := t.BuilderExits
					vlen := len(t)
					if vlen > int(expr8) {
						return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr8)), "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.BuilderExits")
					}
					for idx1 := range vlen {
						t := t[idx1]
						if t == nil {
							t = new(gloas1.BuilderExitRequest)
						}
						if dst, err = t.MarshalSSZTo(dst); err != nil {
							return nil, sszutils.ErrorWithPathf(err, "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.BuilderExits[%d]", idx1)
						}
					}
				}
			}
		}
	}
	{ // Dynamic Field #1 'KZGProofs'
		binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(len(dst)-dstlen))
		t := t.KZGProofs
		vlen := len(t)
		if vlen > int(expr9) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr9)), "KZGProofs")
		}
		dst = sszutils.MarshalFixedBytesSlice(dst, t[:vlen])
	}
	{ // Dynamic Field #2 'Blobs'
		binary.LittleEndian.PutUint32(dst[dstlen+8:], uint32(len(dst)-dstlen))
		t := t.Blobs
		vlen := len(t)
		if vlen > int(expr10) {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(expr10)), "Blobs")
		}
		dst = sszutils.MarshalFixedBytesSlice(dst, t[:vlen])
	}
	return dst, nil
}

func (t *SignedExecutionPayloadEnvelopeContents) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *gloas.SignedExecutionPayloadEnvelopeContents:
		return t.unmarshalSSZView_SignedExecutionPayloadEnvelopeContents
	}
	return nil
}
func (t *SignedExecutionPayloadEnvelopeContents) unmarshalSSZView_SignedExecutionPayloadEnvelopeContents(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXTRA_DATA_BYTES", 32)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_TRANSACTIONS_PER_PAYLOAD", 1048576)
	if err != nil {
		return err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return err
	}
	expr3, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWALS_PER_PAYLOAD", 16)
	if err != nil {
		return err
	}
	expr4, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_DEPOSIT_REQUESTS_PER_PAYLOAD", 8192)
	if err != nil {
		return err
	}
	expr5, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWAL_REQUESTS_PER_PAYLOAD", 16)
	if err != nil {
		return err
	}
	expr6, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_CONSOLIDATION_REQUESTS_PER_PAYLOAD", 2)
	if err != nil {
		return err
	}
	expr7, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BUILDER_DEPOSIT_REQUESTS_PER_PAYLOAD", 256)
	if err != nil {
		return err
	}
	expr8, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BUILDER_EXIT_REQUESTS_PER_PAYLOAD", 16)
	if err != nil {
		return err
	}
	expr9, err := sszutils.ResolveSpecValueWithDefault(ds, "FIELD_ELEMENTS_PER_EXT_BLOB*MAX_BLOB_COMMITMENTS_PER_BLOCK", 33554432)
	if err != nil {
		return err
	}
	expr10, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return err
	}
	buflen := len(buf)
	if buflen < 12 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 12)
	}
	// Field #0 'SignedExecutionPayloadEnvelope' (offset)
	offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
	if offset0 != 12 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 12), "SignedExecutionPayloadEnvelope:o")
	}
	// Field #1 'KZGProofs' (offset)
	offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
	if offset1 < offset0 || offset1 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "KZGProofs:o")
	}
	// Field #2 'Blobs' (offset)
	offset2 := int(binary.LittleEndian.Uint32(buf[8:12]))
	if offset2 < offset1 || offset2 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset2, offset1, buflen), "Blobs:o")
	}
	{ // Field #0 'SignedExecutionPayloadEnvelope' (dynamic)
		buf := buf[offset0:offset1]
		if t.SignedExecutionPayloadEnvelope == nil {
			t.SignedExecutionPayloadEnvelope = new(all.SignedExecutionPayloadEnvelope)
		}
		buflen := len(buf)
		if buflen < 100 {
			return sszutils.ErrorWithPath(sszutils.ErrFixedFieldsEOFFn(buflen, 100), "SignedExecutionPayloadEnvelope")
		}
		// Field #0 'Message' (offset)
		offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
		if offset0 != 100 {
			return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 100), "SignedExecutionPayloadEnvelope.Message:o")
		}
		{ // Field #1 'Signature' (static)
			buf := buf[4:100]
			copy(t.SignedExecutionPayloadEnvelope.Signature[:], buf)
		}
		{ // Field #0 'Message' (dynamic)
			buf := buf[offset0:]
			if t.SignedExecutionPayloadEnvelope.Message == nil {
				t.SignedExecutionPayloadEnvelope.Message = new(all.ExecutionPayloadEnvelope)
			}
			buflen := len(buf)
			if buflen < 80 {
				return sszutils.ErrorWithPath(sszutils.ErrFixedFieldsEOFFn(buflen, 80), "SignedExecutionPayloadEnvelope.Message")
			}
			// Field #0 'Payload' (offset)
			offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
			if offset0 != 80 {
				return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 80), "SignedExecutionPayloadEnvelope.Message.Payload:o")
			}
			// Field #1 'ExecutionRequests' (offset)
			offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
			if offset1 < offset0 || offset1 > buflen {
				return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "SignedExecutionPayloadEnvelope.Message.ExecutionRequests:o")
			}
			{ // Field #2 'BuilderIndex' (static)
				buf := buf[8:16]
				t.SignedExecutionPayloadEnvelope.Message.BuilderIndex = gloas1.BuilderIndex(binary.LittleEndian.Uint64(buf))
			}
			{ // Field #3 'BeaconBlockRoot' (static)
				buf := buf[16:48]
				copy(t.SignedExecutionPayloadEnvelope.Message.BeaconBlockRoot[:], buf)
			}
			{ // Field #4 'ParentBeaconBlockRoot' (static)
				buf := buf[48:80]
				copy(t.SignedExecutionPayloadEnvelope.Message.ParentBeaconBlockRoot[:], buf)
			}
			{ // Field #0 'Payload' (dynamic)
				buf := buf[offset0:offset1]
				if t.SignedExecutionPayloadEnvelope.Message.Payload == nil {
					t.SignedExecutionPayloadEnvelope.Message.Payload = new(all.ExecutionPayload)
				}
				buflen := len(buf)
				if buflen < 540 {
					return sszutils.ErrorWithPath(sszutils.ErrFixedFieldsEOFFn(buflen, 540), "SignedExecutionPayloadEnvelope.Message.Payload")
				}
				{ // Field #0 'ParentHash' (static)
					buf := buf[0:32]
					copy(t.SignedExecutionPayloadEnvelope.Message.Payload.ParentHash[:], buf)
				}
				{ // Field #1 'FeeRecipient' (static)
					buf := buf[32:52]
					copy(t.SignedExecutionPayloadEnvelope.Message.Payload.FeeRecipient[:], buf)
				}
				{ // Field #2 'StateRoot' (static)
					buf := buf[52:84]
					copy(t.SignedExecutionPayloadEnvelope.Message.Payload.StateRoot[:], buf)
				}
				{ // Field #3 'ReceiptsRoot' (static)
					buf := buf[84:116]
					copy(t.SignedExecutionPayloadEnvelope.Message.Payload.ReceiptsRoot[:], buf)
				}
				{ // Field #4 'LogsBloom' (static)
					buf := buf[116:372]
					copy(t.SignedExecutionPayloadEnvelope.Message.Payload.LogsBloom[:], buf)
				}
				{ // Field #5 'PrevRandao' (static)
					buf := buf[372:404]
					copy(t.SignedExecutionPayloadEnvelope.Message.Payload.PrevRandao[:], buf)
				}
				{ // Field #6 'BlockNumber' (static)
					buf := buf[404:412]
					t.SignedExecutionPayloadEnvelope.Message.Payload.BlockNumber = binary.LittleEndian.Uint64(buf)
				}
				{ // Field #7 'GasLimit' (static)
					buf := buf[412:420]
					t.SignedExecutionPayloadEnvelope.Message.Payload.GasLimit = binary.LittleEndian.Uint64(buf)
				}
				{ // Field #8 'GasUsed' (static)
					buf := buf[420:428]
					t.SignedExecutionPayloadEnvelope.Message.Payload.GasUsed = binary.LittleEndian.Uint64(buf)
				}
				{ // Field #9 'Timestamp' (static)
					buf := buf[428:436]
					t.SignedExecutionPayloadEnvelope.Message.Payload.Timestamp = binary.LittleEndian.Uint64(buf)
				}
				// Field #10 'ExtraData' (offset)
				offset10 := int(binary.LittleEndian.Uint32(buf[436:440]))
				if offset10 != 540 {
					return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset10, 540), "SignedExecutionPayloadEnvelope.Message.Payload.ExtraData:o")
				}
				{ // Field #11 'BaseFeePerGas' (static)
					buf := buf[440:472]
					val1 := t.SignedExecutionPayloadEnvelope.Message.Payload.BaseFeePerGas
					if val1 == nil {
						val1 = new(uint256.Int)
					}
					sszutils.UnmarshalUint64Slice((*val1)[:4], buf)
					t.SignedExecutionPayloadEnvelope.Message.Payload.BaseFeePerGas = val1
				}
				{ // Field #12 'BlockHash' (static)
					buf := buf[472:504]
					copy(t.SignedExecutionPayloadEnvelope.Message.Payload.BlockHash[:], buf)
				}
				// Field #13 'Transactions' (offset)
				offset13 := int(binary.LittleEndian.Uint32(buf[504:508]))
				if offset13 < offset10 || offset13 > buflen {
					return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset13, offset10, buflen), "SignedExecutionPayloadEnvelope.Message.Payload.Transactions:o")
				}
				// Field #14 'Withdrawals' (offset)
				offset14 := int(binary.LittleEndian.Uint32(buf[508:512]))
				if offset14 < offset13 || offset14 > buflen {
					return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset14, offset13, buflen), "SignedExecutionPayloadEnvelope.Message.Payload.Withdrawals:o")
				}
				{ // Field #15 'BlobGasUsed' (static)
					buf := buf[512:520]
					t.SignedExecutionPayloadEnvelope.Message.Payload.BlobGasUsed = binary.LittleEndian.Uint64(buf)
				}
				{ // Field #16 'ExcessBlobGas' (static)
					buf := buf[520:528]
					t.SignedExecutionPayloadEnvelope.Message.Payload.ExcessBlobGas = binary.LittleEndian.Uint64(buf)
				}
				// Field #17 'BlockAccessList' (offset)
				offset17 := int(binary.LittleEndian.Uint32(buf[528:532]))
				if offset17 < offset14 || offset17 > buflen {
					return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset17, offset14, buflen), "SignedExecutionPayloadEnvelope.Message.Payload.BlockAccessList:o")
				}
				{ // Field #18 'SlotNumber' (static)
					buf := buf[532:540]
					t.SignedExecutionPayloadEnvelope.Message.Payload.SlotNumber = binary.LittleEndian.Uint64(buf)
				}
				{ // Field #10 'ExtraData' (dynamic)
					buf := buf[offset10:offset13]
					if len(buf) > int(expr0) {
						return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(len(buf), int(expr0)), "SignedExecutionPayloadEnvelope.Message.Payload.ExtraData")
					}
					t.SignedExecutionPayloadEnvelope.Message.Payload.ExtraData = sszutils.ExpandSlice(t.SignedExecutionPayloadEnvelope.Message.Payload.ExtraData, len(buf))
					copy(t.SignedExecutionPayloadEnvelope.Message.Payload.ExtraData[:], buf)
				}
				{ // Field #13 'Transactions' (dynamic)
					buf := buf[offset13:offset14]
					val2 := t.SignedExecutionPayloadEnvelope.Message.Payload.Transactions
					startOffset := int(0)
					if len(buf) != 0 {
						if len(buf) < 4 {
							return sszutils.ErrorWithPath(sszutils.ErrListOffsetsEOFFn(len(buf), 4), "SignedExecutionPayloadEnvelope.Message.Payload.Transactions")
						}
						startOffset = int(binary.LittleEndian.Uint32(buf[0:4]))
					}
					itemCount := startOffset / 4
					if startOffset%4 != 0 || len(buf) < startOffset || (len(buf) != 0 && startOffset == 0) {
						return sszutils.ErrorWithPath(sszutils.ErrInvalidListStartOffsetFn(startOffset, len(buf)), "SignedExecutionPayloadEnvelope.Message.Payload.Transactions")
					}
					if itemCount > int(expr1) {
						return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr1)), "SignedExecutionPayloadEnvelope.Message.Payload.Transactions")
					}
					val2 = sszutils.ExpandSlice(val2, itemCount)
					for idx1 := range itemCount {
						var endOffset int
						if idx1 < itemCount-1 {
							endOffset = int(binary.LittleEndian.Uint32(buf[(idx1+1)*4 : (idx1+2)*4]))
						} else {
							endOffset = len(buf)
						}
						if endOffset < startOffset || endOffset > len(buf) {
							return sszutils.ErrorWithPathf(sszutils.ErrElementOffsetOutOfRangeFn(endOffset, startOffset, len(buf)), "SignedExecutionPayloadEnvelope.Message.Payload.Transactions[%d]", idx1)
						}
						buf := buf[startOffset:endOffset]
						startOffset = endOffset
						val3 := val2[idx1]
						if len(buf) > int(expr2) {
							return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(len(buf), int(expr2)), "SignedExecutionPayloadEnvelope.Message.Payload.Transactions[%d]", idx1)
						}
						val3 = sszutils.ExpandSlice(val3, len(buf))
						copy(val3[:], buf)
						val2[idx1] = val3
					}
					t.SignedExecutionPayloadEnvelope.Message.Payload.Transactions = val2
				}
				{ // Field #14 'Withdrawals' (dynamic)
					buf := buf[offset14:offset17]
					val4 := t.SignedExecutionPayloadEnvelope.Message.Payload.Withdrawals
					itemCount := len(buf) / 44
					if len(buf)%44 != 0 {
						return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 44), "SignedExecutionPayloadEnvelope.Message.Payload.Withdrawals")
					}
					if itemCount > int(expr3) {
						return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr3)), "SignedExecutionPayloadEnvelope.Message.Payload.Withdrawals")
					}
					val4 = sszutils.ExpandSlice(val4, itemCount)
					for idx1 := range itemCount {
						if val4[idx1] == nil {
							val4[idx1] = new(capella.Withdrawal)
						}
						buf := buf[44*idx1 : 44*(idx1+1)]
						if err = val4[idx1].UnmarshalSSZ(buf); err != nil {
							return sszutils.ErrorWithPathf(err, "SignedExecutionPayloadEnvelope.Message.Payload.Withdrawals[%d]", idx1)
						}
					}
					t.SignedExecutionPayloadEnvelope.Message.Payload.Withdrawals = val4
				}
				{ // Field #17 'BlockAccessList' (dynamic)
					buf := buf[offset17:]
					if len(buf) > int(expr2) {
						return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(len(buf), int(expr2)), "SignedExecutionPayloadEnvelope.Message.Payload.BlockAccessList")
					}
					t.SignedExecutionPayloadEnvelope.Message.Payload.BlockAccessList = sszutils.ExpandSlice(t.SignedExecutionPayloadEnvelope.Message.Payload.BlockAccessList, len(buf))
					copy(t.SignedExecutionPayloadEnvelope.Message.Payload.BlockAccessList[:], buf)
				}
			}
			{ // Field #1 'ExecutionRequests' (dynamic)
				buf := buf[offset1:]
				if t.SignedExecutionPayloadEnvelope.Message.ExecutionRequests == nil {
					t.SignedExecutionPayloadEnvelope.Message.ExecutionRequests = new(all.ExecutionRequests)
				}
				buflen := len(buf)
				if buflen < 20 {
					return sszutils.ErrorWithPath(sszutils.ErrFixedFieldsEOFFn(buflen, 20), "SignedExecutionPayloadEnvelope.Message.ExecutionRequests")
				}
				// Field #0 'Deposits' (offset)
				offset0 := int(binary.LittleEndian.Uint32(buf[0:4]))
				if offset0 != 20 {
					return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 20), "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Deposits:o")
				}
				// Field #1 'Withdrawals' (offset)
				offset1 := int(binary.LittleEndian.Uint32(buf[4:8]))
				if offset1 < offset0 || offset1 > buflen {
					return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Withdrawals:o")
				}
				// Field #2 'Consolidations' (offset)
				offset2 := int(binary.LittleEndian.Uint32(buf[8:12]))
				if offset2 < offset1 || offset2 > buflen {
					return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset2, offset1, buflen), "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Consolidations:o")
				}
				// Field #3 'BuilderDeposits' (offset)
				offset3 := int(binary.LittleEndian.Uint32(buf[12:16]))
				if offset3 < offset2 || offset3 > buflen {
					return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset3, offset2, buflen), "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.BuilderDeposits:o")
				}
				// Field #4 'BuilderExits' (offset)
				offset4 := int(binary.LittleEndian.Uint32(buf[16:20]))
				if offset4 < offset3 || offset4 > buflen {
					return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset4, offset3, buflen), "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.BuilderExits:o")
				}
				{ // Field #0 'Deposits' (dynamic)
					buf := buf[offset0:offset1]
					val5 := t.SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Deposits
					itemCount := len(buf) / 192
					if len(buf)%192 != 0 {
						return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 192), "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Deposits")
					}
					if itemCount > int(expr4) {
						return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr4)), "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Deposits")
					}
					val5 = sszutils.ExpandSlice(val5, itemCount)
					for idx1 := range itemCount {
						if val5[idx1] == nil {
							val5[idx1] = new(electra.DepositRequest)
						}
						buf := buf[192*idx1 : 192*(idx1+1)]
						if err = val5[idx1].UnmarshalSSZ(buf); err != nil {
							return sszutils.ErrorWithPathf(err, "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Deposits[%d]", idx1)
						}
					}
					t.SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Deposits = val5
				}
				{ // Field #1 'Withdrawals' (dynamic)
					buf := buf[offset1:offset2]
					val6 := t.SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Withdrawals
					itemCount := len(buf) / 76
					if len(buf)%76 != 0 {
						return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 76), "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Withdrawals")
					}
					if itemCount > int(expr5) {
						return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr5)), "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Withdrawals")
					}
					val6 = sszutils.ExpandSlice(val6, itemCount)
					for idx1 := range itemCount {
						if val6[idx1] == nil {
							val6[idx1] = new(electra.WithdrawalRequest)
						}
						buf := buf[76*idx1 : 76*(idx1+1)]
						if err = val6[idx1].UnmarshalSSZ(buf); err != nil {
							return sszutils.ErrorWithPathf(err, "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Withdrawals[%d]", idx1)
						}
					}
					t.SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Withdrawals = val6
				}
				{ // Field #2 'Consolidations' (dynamic)
					buf := buf[offset2:offset3]
					val7 := t.SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Consolidations
					itemCount := len(buf) / 116
					if len(buf)%116 != 0 {
						return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 116), "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Consolidations")
					}
					if itemCount > int(expr6) {
						return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr6)), "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Consolidations")
					}
					val7 = sszutils.ExpandSlice(val7, itemCount)
					for idx1 := range itemCount {
						if val7[idx1] == nil {
							val7[idx1] = new(electra.ConsolidationRequest)
						}
						buf := buf[116*idx1 : 116*(idx1+1)]
						if err = val7[idx1].UnmarshalSSZ(buf); err != nil {
							return sszutils.ErrorWithPathf(err, "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Consolidations[%d]", idx1)
						}
					}
					t.SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Consolidations = val7
				}
				{ // Field #3 'BuilderDeposits' (dynamic)
					buf := buf[offset3:offset4]
					val8 := t.SignedExecutionPayloadEnvelope.Message.ExecutionRequests.BuilderDeposits
					itemCount := len(buf) / 184
					if len(buf)%184 != 0 {
						return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 184), "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.BuilderDeposits")
					}
					if itemCount > int(expr7) {
						return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr7)), "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.BuilderDeposits")
					}
					val8 = sszutils.ExpandSlice(val8, itemCount)
					for idx1 := range itemCount {
						if val8[idx1] == nil {
							val8[idx1] = new(gloas1.BuilderDepositRequest)
						}
						buf := buf[184*idx1 : 184*(idx1+1)]
						if err = val8[idx1].UnmarshalSSZ(buf); err != nil {
							return sszutils.ErrorWithPathf(err, "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.BuilderDeposits[%d]", idx1)
						}
					}
					t.SignedExecutionPayloadEnvelope.Message.ExecutionRequests.BuilderDeposits = val8
				}
				{ // Field #4 'BuilderExits' (dynamic)
					buf := buf[offset4:]
					val9 := t.SignedExecutionPayloadEnvelope.Message.ExecutionRequests.BuilderExits
					itemCount := len(buf) / 68
					if len(buf)%68 != 0 {
						return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 68), "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.BuilderExits")
					}
					if itemCount > int(expr8) {
						return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr8)), "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.BuilderExits")
					}
					val9 = sszutils.ExpandSlice(val9, itemCount)
					for idx1 := range itemCount {
						if val9[idx1] == nil {
							val9[idx1] = new(gloas1.BuilderExitRequest)
						}
						buf := buf[68*idx1 : 68*(idx1+1)]
						if err = val9[idx1].UnmarshalSSZ(buf); err != nil {
							return sszutils.ErrorWithPathf(err, "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.BuilderExits[%d]", idx1)
						}
					}
					t.SignedExecutionPayloadEnvelope.Message.ExecutionRequests.BuilderExits = val9
				}
			}
		}
	}
	{ // Field #1 'KZGProofs' (dynamic)
		buf := buf[offset1:offset2]
		val10 := t.KZGProofs
		itemCount := len(buf) / 48
		if len(buf)%48 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 48), "KZGProofs")
		}
		if itemCount > int(expr9) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr9)), "KZGProofs")
		}
		val10 = sszutils.ExpandSlice(val10, itemCount)
		sszutils.UnmarshalFixedBytesSlice(val10[:itemCount], buf)
		t.KZGProofs = val10
	}
	{ // Field #2 'Blobs' (dynamic)
		buf := buf[offset2:]
		val11 := t.Blobs
		itemCount := len(buf) / 131072
		if len(buf)%131072 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 131072), "Blobs")
		}
		if itemCount > int(expr10) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr10)), "Blobs")
		}
		val11 = sszutils.ExpandSlice(val11, itemCount)
		sszutils.UnmarshalFixedBytesSlice(val11[:itemCount], buf)
		t.Blobs = val11
	}
	return nil
}

func (t *SignedExecutionPayloadEnvelopeContents) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *gloas.SignedExecutionPayloadEnvelopeContents:
		return t.sizeSSZView_SignedExecutionPayloadEnvelopeContents
	}
	return nil
}
func (t *SignedExecutionPayloadEnvelopeContents) sizeSSZView_SignedExecutionPayloadEnvelopeContents(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(SignedExecutionPayloadEnvelopeContents)
	}
	// Field #0 'SignedExecutionPayloadEnvelope' offset (4 bytes)
	// Field #1 'KZGProofs' offset (4 bytes)
	// Field #2 'Blobs' offset (4 bytes)
	size += 12
	{ // Dynamic field #0 'SignedExecutionPayloadEnvelope'
		t := t.SignedExecutionPayloadEnvelope
		if t == nil {
			t = new(all.SignedExecutionPayloadEnvelope)
		}
		// Field #0 'Message' offset (4 bytes)
		// Field #1 'Signature' static (96 bytes)
		size += 100
		{ // Dynamic field #0 'Message'
			t := t.Message
			if t == nil {
				t = new(all.ExecutionPayloadEnvelope)
			}
			// Field #0 'Payload' offset (4 bytes)
			// Field #1 'ExecutionRequests' offset (4 bytes)
			// Field #2 'BuilderIndex' static (8 bytes)
			// Field #3 'BeaconBlockRoot' static (32 bytes)
			// Field #4 'ParentBeaconBlockRoot' static (32 bytes)
			size += 80
			{ // Dynamic field #0 'Payload'
				t := t.Payload
				if t == nil {
					t = new(all.ExecutionPayload)
				}
				// Field #0 'ParentHash' static (32 bytes)
				// Field #1 'FeeRecipient' static (20 bytes)
				// Field #2 'StateRoot' static (32 bytes)
				// Field #3 'ReceiptsRoot' static (32 bytes)
				// Field #4 'LogsBloom' static (256 bytes)
				// Field #5 'PrevRandao' static (32 bytes)
				// Field #6 'BlockNumber' static (8 bytes)
				// Field #7 'GasLimit' static (8 bytes)
				// Field #8 'GasUsed' static (8 bytes)
				// Field #9 'Timestamp' static (8 bytes)
				// Field #10 'ExtraData' offset (4 bytes)
				// Field #11 'BaseFeePerGas' static (32 bytes)
				// Field #12 'BlockHash' static (32 bytes)
				// Field #13 'Transactions' offset (4 bytes)
				// Field #14 'Withdrawals' offset (4 bytes)
				// Field #15 'BlobGasUsed' static (8 bytes)
				// Field #16 'ExcessBlobGas' static (8 bytes)
				// Field #17 'BlockAccessList' offset (4 bytes)
				// Field #18 'SlotNumber' static (8 bytes)
				size += 540
				{ // Dynamic field #10 'ExtraData'
					size += len(t.ExtraData)
				}
				{ // Dynamic field #13 'Transactions'
					t := t.Transactions
					vlen := len(t)
					size += vlen * 4 // Offsets
					for i1 := range vlen {
						size += len(t[i1])
					}
				}
				{ // Dynamic field #14 'Withdrawals'
					size += len(t.Withdrawals) * 44
				}
				{ // Dynamic field #17 'BlockAccessList'
					size += len(t.BlockAccessList)
				}
			}
			{ // Dynamic field #1 'ExecutionRequests'
				t := t.ExecutionRequests
				if t == nil {
					t = new(all.ExecutionRequests)
				}
				// Field #0 'Deposits' offset (4 bytes)
				// Field #1 'Withdrawals' offset (4 bytes)
				// Field #2 'Consolidations' offset (4 bytes)
				// Field #3 'BuilderDeposits' offset (4 bytes)
				// Field #4 'BuilderExits' offset (4 bytes)
				size += 20
				{ // Dynamic field #0 'Deposits'
					size += len(t.Deposits) * 192
				}
				{ // Dynamic field #1 'Withdrawals'
					size += len(t.Withdrawals) * 76
				}
				{ // Dynamic field #2 'Consolidations'
					size += len(t.Consolidations) * 116
				}
				{ // Dynamic field #3 'BuilderDeposits'
					size += len(t.BuilderDeposits) * 184
				}
				{ // Dynamic field #4 'BuilderExits'
					size += len(t.BuilderExits) * 68
				}
			}
		}
	}
	{ // Dynamic field #1 'KZGProofs'
		size += len(t.KZGProofs) * 48
	}
	{ // Dynamic field #2 'Blobs'
		size += len(t.Blobs) * 131072
	}
	return size
}

func (t *SignedExecutionPayloadEnvelopeContents) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *gloas.SignedExecutionPayloadEnvelopeContents:
		return t.hashTreeRootView_SignedExecutionPayloadEnvelopeContents
	}
	return nil
}
func (t *SignedExecutionPayloadEnvelopeContents) hashTreeRootView_SignedExecutionPayloadEnvelopeContents(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_EXTRA_DATA_BYTES", 32)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_TRANSACTIONS_PER_PAYLOAD", 1048576)
	if err != nil {
		return err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BYTES_PER_TRANSACTION", 1073741824)
	if err != nil {
		return err
	}
	expr3, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWALS_PER_PAYLOAD", 16)
	if err != nil {
		return err
	}
	expr4, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_DEPOSIT_REQUESTS_PER_PAYLOAD", 8192)
	if err != nil {
		return err
	}
	expr5, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWAL_REQUESTS_PER_PAYLOAD", 16)
	if err != nil {
		return err
	}
	expr6, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_CONSOLIDATION_REQUESTS_PER_PAYLOAD", 2)
	if err != nil {
		return err
	}
	expr7, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BUILDER_DEPOSIT_REQUESTS_PER_PAYLOAD", 256)
	if err != nil {
		return err
	}
	expr8, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BUILDER_EXIT_REQUESTS_PER_PAYLOAD", 16)
	if err != nil {
		return err
	}
	expr9, err := sszutils.ResolveSpecValueWithDefault(ds, "FIELD_ELEMENTS_PER_EXT_BLOB*MAX_BLOB_COMMITMENTS_PER_BLOCK", 33554432)
	if err != nil {
		return err
	}
	expr10, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_BLOB_COMMITMENTS_PER_BLOCK", 4096)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(SignedExecutionPayloadEnvelopeContents)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'SignedExecutionPayloadEnvelope'
		t := t.SignedExecutionPayloadEnvelope
		if t == nil {
			t = new(all.SignedExecutionPayloadEnvelope)
		}
		idx := hh.StartTree(sszutils.TreeTypeNone)
		{ // Field #0 'Message'
			t := t.Message
			if t == nil {
				t = new(all.ExecutionPayloadEnvelope)
			}
			idx := hh.StartTree(sszutils.TreeTypeNone)
			{ // Field #0 'Payload'
				t := t.Payload
				if t == nil {
					t = new(all.ExecutionPayload)
				}
				idx := hh.StartTree(sszutils.TreeTypeNone)
				{ // Field #0 'ParentHash'
					hh.PutBytes(t.ParentHash[:32])
				}
				{ // Field #1 'FeeRecipient'
					hh.PutBytes(t.FeeRecipient[:20])
				}
				{ // Field #2 'StateRoot'
					hh.PutBytes(t.StateRoot[:32])
				}
				{ // Field #3 'ReceiptsRoot'
					hh.PutBytes(t.ReceiptsRoot[:32])
				}
				{ // Field #4 'LogsBloom'
					hh.PutBytes(t.LogsBloom[:256])
				}
				{ // Field #5 'PrevRandao'
					hh.PutBytes(t.PrevRandao[:32])
				}
				{ // Field #6 'BlockNumber'
					hh.PutUint64(t.BlockNumber)
				}
				{ // Field #7 'GasLimit'
					hh.PutUint64(t.GasLimit)
				}
				{ // Field #8 'GasUsed'
					hh.PutUint64(t.GasUsed)
				}
				{ // Field #9 'Timestamp'
					hh.PutUint64(t.Timestamp)
				}
				{ // Field #10 'ExtraData'
					vlen := uint64(len(t.ExtraData))
					if vlen > expr0 {
						return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "SignedExecutionPayloadEnvelope.Message.Payload.ExtraData")
					}
					idx := hh.StartTree(sszutils.TreeTypeBinary)
					hh.AppendBytes32(t.ExtraData[:])
					hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 1))
				}
				{ // Field #11 'BaseFeePerGas'
					t := t.BaseFeePerGas
					if t == nil {
						t = new(uint256.Int)
					}
					if root, err := t.HashTreeRoot(); err != nil {
						return sszutils.ErrorWithPath(err, "SignedExecutionPayloadEnvelope.Message.Payload.BaseFeePerGas")
					} else {
						hh.AppendBytes32(root[:])
					}
				}
				{ // Field #12 'BlockHash'
					hh.PutBytes(t.BlockHash[:32])
				}
				{ // Field #13 'Transactions'
					t := t.Transactions
					vlen := uint64(len(t))
					if vlen > expr1 {
						return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr1), "SignedExecutionPayloadEnvelope.Message.Payload.Transactions")
					}
					idx := hh.StartTree(sszutils.TreeTypeBinary)
					for idx1 := range int(vlen) {
						vlen := uint64(len(t[idx1]))
						if vlen > expr2 {
							return sszutils.ErrorWithPathf(sszutils.ErrListLengthFn(vlen, expr2), "SignedExecutionPayloadEnvelope.Message.Payload.Transactions[%d]", idx1)
						}
						idx := hh.StartTree(sszutils.TreeTypeBinary)
						hh.AppendBytes32(t[idx1][:])
						hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr2, vlen, 1))
						if (idx1+1)%256 == 0 {
							hh.Collapse()
						}
					}
					hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr1, vlen, 32))
				}
				{ // Field #14 'Withdrawals'
					t := t.Withdrawals
					vlen := uint64(len(t))
					if vlen > expr3 {
						return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr3), "SignedExecutionPayloadEnvelope.Message.Payload.Withdrawals")
					}
					idx := hh.StartTree(sszutils.TreeTypeBinary)
					for idx1 := range int(vlen) {
						t := t[idx1]
						if t == nil {
							t = new(capella.Withdrawal)
						}
						if err := t.HashTreeRootWith(hh); err != nil {
							return sszutils.ErrorWithPathf(err, "SignedExecutionPayloadEnvelope.Message.Payload.Withdrawals[%d]", idx1)
						}
						if (idx1+1)%256 == 0 {
							hh.Collapse()
						}
					}
					hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr3, vlen, 32))
				}
				{ // Field #15 'BlobGasUsed'
					hh.PutUint64(t.BlobGasUsed)
				}
				{ // Field #16 'ExcessBlobGas'
					hh.PutUint64(t.ExcessBlobGas)
				}
				{ // Field #17 'BlockAccessList'
					vlen := uint64(len(t.BlockAccessList))
					if vlen > expr2 {
						return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr2), "SignedExecutionPayloadEnvelope.Message.Payload.BlockAccessList")
					}
					idx := hh.StartTree(sszutils.TreeTypeBinary)
					hh.AppendBytes32(t.BlockAccessList[:])
					hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr2, vlen, 1))
				}
				{ // Field #18 'SlotNumber'
					hh.PutUint64(t.SlotNumber)
				}
				hh.Merkleize(idx)
			}
			{ // Field #1 'ExecutionRequests'
				t := t.ExecutionRequests
				if t == nil {
					t = new(all.ExecutionRequests)
				}
				idx := hh.StartTree(sszutils.TreeTypeNone)
				{ // Field #0 'Deposits'
					t := t.Deposits
					vlen := uint64(len(t))
					if vlen > expr4 {
						return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr4), "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Deposits")
					}
					idx := hh.StartTree(sszutils.TreeTypeBinary)
					for idx1 := range int(vlen) {
						t := t[idx1]
						if t == nil {
							t = new(electra.DepositRequest)
						}
						if err := t.HashTreeRootWith(hh); err != nil {
							return sszutils.ErrorWithPathf(err, "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Deposits[%d]", idx1)
						}
						if (idx1+1)%256 == 0 {
							hh.Collapse()
						}
					}
					hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr4, vlen, 32))
				}
				{ // Field #1 'Withdrawals'
					t := t.Withdrawals
					vlen := uint64(len(t))
					if vlen > expr5 {
						return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr5), "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Withdrawals")
					}
					idx := hh.StartTree(sszutils.TreeTypeBinary)
					for idx1 := range int(vlen) {
						t := t[idx1]
						if t == nil {
							t = new(electra.WithdrawalRequest)
						}
						if err := t.HashTreeRootWith(hh); err != nil {
							return sszutils.ErrorWithPathf(err, "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Withdrawals[%d]", idx1)
						}
						if (idx1+1)%256 == 0 {
							hh.Collapse()
						}
					}
					hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr5, vlen, 32))
				}
				{ // Field #2 'Consolidations'
					t := t.Consolidations
					vlen := uint64(len(t))
					if vlen > expr6 {
						return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr6), "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Consolidations")
					}
					idx := hh.StartTree(sszutils.TreeTypeBinary)
					for idx1 := range int(vlen) {
						t := t[idx1]
						if t == nil {
							t = new(electra.ConsolidationRequest)
						}
						if err := t.HashTreeRootWith(hh); err != nil {
							return sszutils.ErrorWithPathf(err, "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.Consolidations[%d]", idx1)
						}
						if (idx1+1)%256 == 0 {
							hh.Collapse()
						}
					}
					hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr6, vlen, 32))
				}
				{ // Field #3 'BuilderDeposits'
					t := t.BuilderDeposits
					vlen := uint64(len(t))
					if vlen > expr7 {
						return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr7), "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.BuilderDeposits")
					}
					idx := hh.StartTree(sszutils.TreeTypeBinary)
					for idx1 := range int(vlen) {
						t := t[idx1]
						if t == nil {
							t = new(gloas1.BuilderDepositRequest)
						}
						if err := t.HashTreeRootWith(hh); err != nil {
							return sszutils.ErrorWithPathf(err, "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.BuilderDeposits[%d]", idx1)
						}
						if (idx1+1)%256 == 0 {
							hh.Collapse()
						}
					}
					hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr7, vlen, 32))
				}
				{ // Field #4 'BuilderExits'
					t := t.BuilderExits
					vlen := uint64(len(t))
					if vlen > expr8 {
						return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr8), "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.BuilderExits")
					}
					idx := hh.StartTree(sszutils.TreeTypeBinary)
					for idx1 := range int(vlen) {
						t := t[idx1]
						if t == nil {
							t = new(gloas1.BuilderExitRequest)
						}
						if err := t.HashTreeRootWith(hh); err != nil {
							return sszutils.ErrorWithPathf(err, "SignedExecutionPayloadEnvelope.Message.ExecutionRequests.BuilderExits[%d]", idx1)
						}
						if (idx1+1)%256 == 0 {
							hh.Collapse()
						}
					}
					hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr8, vlen, 32))
				}
				hh.Merkleize(idx)
			}
			{ // Field #2 'BuilderIndex'
				hh.PutUint64(uint64(t.BuilderIndex))
			}
			{ // Field #3 'BeaconBlockRoot'
				hh.PutBytes(t.BeaconBlockRoot[:32])
			}
			{ // Field #4 'ParentBeaconBlockRoot'
				hh.PutBytes(t.ParentBeaconBlockRoot[:32])
			}
			hh.Merkleize(idx)
		}
		{ // Field #1 'Signature'
			hh.PutBytes(t.Signature[:96])
		}
		hh.Merkleize(idx)
	}
	{ // Field #1 'KZGProofs'
		t := t.KZGProofs
		vlen := uint64(len(t))
		if vlen > expr9 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr9), "KZGProofs")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:48])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr9, vlen, 32))
	}
	{ // Field #2 'Blobs'
		t := t.Blobs
		vlen := uint64(len(t))
		if vlen > expr10 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr10), "Blobs")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:131072])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr10, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}
