// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: e7529fc59cd717399e7ea3a4b32362d7d2e7e5701e975d780a89992a3906b45e
// Version: v1.3.1 (https://github.com/pk910/dynamic-ssz)
package fulu

import (
	"encoding/binary"

	"github.com/ethpandaops/go-eth2-client/spec/altair"
	"github.com/ethpandaops/go-eth2-client/spec/capella"
	"github.com/ethpandaops/go-eth2-client/spec/deneb"
	"github.com/ethpandaops/go-eth2-client/spec/electra"
	"github.com/ethpandaops/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

// MarshalSSZ marshals the *BeaconState to SSZ-encoded bytes.
func (t *BeaconState) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *BeaconState to SSZ-encoded bytes, appending to the provided buffer.
func (t *BeaconState) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	zeroBytes := sszutils.ZeroBytes()
	if t == nil {
		t = new(BeaconState)
	}
	dstlen := len(dst)
	{ // Static Field #0 'GenesisTime'
		dst = binary.LittleEndian.AppendUint64(dst, t.GenesisTime)
	}
	{ // Static Field #1 'GenesisValidatorsRoot'
		dst = append(dst, t.GenesisValidatorsRoot[:32]...)
	}
	{ // Static Field #2 'Slot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Slot))
	}
	{ // Static Field #3 'Fork'
		t := t.Fork
		if t == nil {
			t = new(phase0.Fork)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Fork")
		}
	}
	{ // Static Field #4 'LatestBlockHeader'
		t := t.LatestBlockHeader
		if t == nil {
			t = new(phase0.BeaconBlockHeader)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "LatestBlockHeader")
		}
	}
	{ // Static Field #5 'BlockRoots'
		t := t.BlockRoots
		vlen := len(t)
		if vlen > 8192 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 8192), "BlockRoots")
		}
		for idx1 := range vlen {
			dst = append(dst, t[idx1][:32]...)
		}
		if vlen < 8192 {
			dst = sszutils.AppendZeroPadding(dst, (8192-vlen)*32)
		}
	}
	{ // Static Field #6 'StateRoots'
		t := t.StateRoots
		vlen := len(t)
		if vlen > 8192 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 8192), "StateRoots")
		}
		for idx1 := range vlen {
			dst = append(dst, t[idx1][:32]...)
		}
		if vlen < 8192 {
			dst = sszutils.AppendZeroPadding(dst, (8192-vlen)*32)
		}
	}
	// Offset Field #7 'HistoricalRoots'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #8 'ETH1Data'
		t := t.ETH1Data
		if t == nil {
			t = new(phase0.ETH1Data)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "ETH1Data")
		}
	}
	// Offset Field #9 'ETH1DataVotes'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #10 'ETH1DepositIndex'
		dst = binary.LittleEndian.AppendUint64(dst, t.ETH1DepositIndex)
	}
	// Offset Field #11 'Validators'
	// Offset Field #12 'Balances'
	dst = append(dst, 0, 0, 0, 0, 0, 0, 0, 0)
	{ // Static Field #13 'RANDAOMixes'
		t := t.RANDAOMixes
		vlen := len(t)
		if vlen > 65536 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 65536), "RANDAOMixes")
		}
		for idx1 := range vlen {
			dst = append(dst, t[idx1][:32]...)
		}
		if vlen < 65536 {
			dst = sszutils.AppendZeroPadding(dst, (65536-vlen)*32)
		}
	}
	{ // Static Field #14 'Slashings'
		t := t.Slashings
		vlen := len(t)
		if vlen > 8192 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 8192), "Slashings")
		}
		dst = sszutils.MarshalUint64Slice(dst, t[:vlen])
		if vlen < 8192 {
			dst = sszutils.AppendZeroPadding(dst, (8192-vlen)*8)
		}
	}
	// Offset Field #15 'PreviousEpochParticipation'
	// Offset Field #16 'CurrentEpochParticipation'
	dst = append(dst, 0, 0, 0, 0, 0, 0, 0, 0)
	{ // Static Field #17 'JustificationBits'
		vlen := len(t.JustificationBits)
		if vlen > 1 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 1), "JustificationBits")
		}
		dst = append(dst, t.JustificationBits[:vlen]...)
		if vlen < 1 {
			dst = sszutils.AppendZeroPadding(dst, (1-vlen)*1)
		}
	}
	{ // Static Field #18 'PreviousJustifiedCheckpoint'
		t := t.PreviousJustifiedCheckpoint
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "PreviousJustifiedCheckpoint")
		}
	}
	{ // Static Field #19 'CurrentJustifiedCheckpoint'
		t := t.CurrentJustifiedCheckpoint
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "CurrentJustifiedCheckpoint")
		}
	}
	{ // Static Field #20 'FinalizedCheckpoint'
		t := t.FinalizedCheckpoint
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "FinalizedCheckpoint")
		}
	}
	// Offset Field #21 'InactivityScores'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #22 'CurrentSyncCommittee'
		t := t.CurrentSyncCommittee
		if t == nil {
			t = new(altair.SyncCommittee)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "CurrentSyncCommittee")
		}
	}
	{ // Static Field #23 'NextSyncCommittee'
		t := t.NextSyncCommittee
		if t == nil {
			t = new(altair.SyncCommittee)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "NextSyncCommittee")
		}
	}
	// Offset Field #24 'LatestExecutionPayloadHeader'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #25 'NextWithdrawalIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.NextWithdrawalIndex))
	}
	{ // Static Field #26 'NextWithdrawalValidatorIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.NextWithdrawalValidatorIndex))
	}
	// Offset Field #27 'HistoricalSummaries'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #28 'DepositRequestsStartIndex'
		dst = binary.LittleEndian.AppendUint64(dst, t.DepositRequestsStartIndex)
	}
	{ // Static Field #29 'DepositBalanceToConsume'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.DepositBalanceToConsume))
	}
	{ // Static Field #30 'ExitBalanceToConsume'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ExitBalanceToConsume))
	}
	{ // Static Field #31 'EarliestExitEpoch'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.EarliestExitEpoch))
	}
	{ // Static Field #32 'ConsolidationBalanceToConsume'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ConsolidationBalanceToConsume))
	}
	{ // Static Field #33 'EarliestConsolidationEpoch'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.EarliestConsolidationEpoch))
	}
	// Offset Field #34 'PendingDeposits'
	// Offset Field #35 'PendingPartialWithdrawals'
	// Offset Field #36 'PendingConsolidations'
	dst = append(dst, zeroBytes[:12]...)
	{ // Static Field #37 'ProposerLookahead'
		t := t.ProposerLookahead
		vlen := len(t)
		if vlen > 64 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 64), "ProposerLookahead")
		}
		dst = sszutils.MarshalUint64Slice(dst, t[:vlen])
		if vlen < 64 {
			dst = sszutils.AppendZeroPadding(dst, (64-vlen)*8)
		}
	}
	{ // Dynamic Field #7 'HistoricalRoots'
		binary.LittleEndian.PutUint32(dst[dstlen+524464:], uint32(len(dst)-dstlen))
		t := t.HistoricalRoots
		vlen := len(t)
		if vlen > 16777216 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 16777216), "HistoricalRoots")
		}
		for idx1 := range vlen {
			dst = append(dst, t[idx1][:32]...)
		}
	}
	{ // Dynamic Field #9 'ETH1DataVotes'
		binary.LittleEndian.PutUint32(dst[dstlen+524540:], uint32(len(dst)-dstlen))
		t := t.ETH1DataVotes
		vlen := len(t)
		if vlen > 2048 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 2048), "ETH1DataVotes")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(phase0.ETH1Data)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "ETH1DataVotes[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #11 'Validators'
		binary.LittleEndian.PutUint32(dst[dstlen+524552:], uint32(len(dst)-dstlen))
		t := t.Validators
		vlen := len(t)
		if vlen > 1099511627776 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1099511627776), "Validators")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(phase0.Validator)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Validators[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #12 'Balances'
		binary.LittleEndian.PutUint32(dst[dstlen+524556:], uint32(len(dst)-dstlen))
		t := t.Balances
		vlen := len(t)
		if vlen > 1099511627776 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1099511627776), "Balances")
		}
		dst = sszutils.MarshalUint64Slice(dst, t[:vlen])
	}
	{ // Dynamic Field #15 'PreviousEpochParticipation'
		binary.LittleEndian.PutUint32(dst[dstlen+2687248:], uint32(len(dst)-dstlen))
		t := t.PreviousEpochParticipation
		vlen := len(t)
		if vlen > 1099511627776 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1099511627776), "PreviousEpochParticipation")
		}
		for idx1 := range vlen {
			dst = append(dst, byte(t[idx1]))
		}
	}
	{ // Dynamic Field #16 'CurrentEpochParticipation'
		binary.LittleEndian.PutUint32(dst[dstlen+2687252:], uint32(len(dst)-dstlen))
		t := t.CurrentEpochParticipation
		vlen := len(t)
		if vlen > 1099511627776 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1099511627776), "CurrentEpochParticipation")
		}
		for idx1 := range vlen {
			dst = append(dst, byte(t[idx1]))
		}
	}
	{ // Dynamic Field #21 'InactivityScores'
		binary.LittleEndian.PutUint32(dst[dstlen+2687377:], uint32(len(dst)-dstlen))
		t := t.InactivityScores
		vlen := len(t)
		if vlen > 1099511627776 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1099511627776), "InactivityScores")
		}
		dst = sszutils.MarshalUint64Slice(dst, t[:vlen])
	}
	{ // Dynamic Field #24 'LatestExecutionPayloadHeader'
		binary.LittleEndian.PutUint32(dst[dstlen+2736629:], uint32(len(dst)-dstlen))
		t := t.LatestExecutionPayloadHeader
		if t == nil {
			t = new(deneb.ExecutionPayloadHeader)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "LatestExecutionPayloadHeader")
		}
	}
	{ // Dynamic Field #27 'HistoricalSummaries'
		binary.LittleEndian.PutUint32(dst[dstlen+2736649:], uint32(len(dst)-dstlen))
		t := t.HistoricalSummaries
		vlen := len(t)
		if vlen > 16777216 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 16777216), "HistoricalSummaries")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(capella.HistoricalSummary)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "HistoricalSummaries[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #34 'PendingDeposits'
		binary.LittleEndian.PutUint32(dst[dstlen+2736701:], uint32(len(dst)-dstlen))
		t := t.PendingDeposits
		vlen := len(t)
		if vlen > 134217728 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 134217728), "PendingDeposits")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(electra.PendingDeposit)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "PendingDeposits[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #35 'PendingPartialWithdrawals'
		binary.LittleEndian.PutUint32(dst[dstlen+2736705:], uint32(len(dst)-dstlen))
		t := t.PendingPartialWithdrawals
		vlen := len(t)
		if vlen > 134217728 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 134217728), "PendingPartialWithdrawals")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(electra.PendingPartialWithdrawal)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "PendingPartialWithdrawals[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #36 'PendingConsolidations'
		binary.LittleEndian.PutUint32(dst[dstlen+2736709:], uint32(len(dst)-dstlen))
		t := t.PendingConsolidations
		vlen := len(t)
		if vlen > 262144 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 262144), "PendingConsolidations")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(electra.PendingConsolidation)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "PendingConsolidations[%d]", idx1)
			}
		}
	}
	return dst, nil
}

// MarshalSSZEncoder marshals the *BeaconState to the given SSZ encoder using dynamic specifications.
func (t *BeaconState) MarshalSSZEncoder(ds sszutils.DynamicSpecs, enc sszutils.Encoder) (err error) {
	type encoderCtx struct {
		ds       sszutils.DynamicSpecs
		exprs    [11]uint64
		sizeFn1  func(ctx *encoderCtx, t []phase0.Root) (size int)
		sizeFn10 func(ctx *encoderCtx, t []*electra.PendingDeposit) (size int)
		sizeFn11 func(ctx *encoderCtx, t []*electra.PendingPartialWithdrawal) (size int)
		sizeFn12 func(ctx *encoderCtx, t []*electra.PendingConsolidation) (size int)
		sizeFn2  func(ctx *encoderCtx, t []*phase0.ETH1Data) (size int)
		sizeFn3  func(ctx *encoderCtx, t []*phase0.Validator) (size int)
		sizeFn4  func(ctx *encoderCtx, t []phase0.Gwei) (size int)
		sizeFn5  func(ctx *encoderCtx, t []altair.ParticipationFlags) (size int)
		sizeFn6  func(ctx *encoderCtx, t []altair.ParticipationFlags) (size int)
		sizeFn7  func(ctx *encoderCtx, t []uint64) (size int)
		sizeFn8  func(ctx *encoderCtx, t *deneb.ExecutionPayloadHeader) (size int)
		sizeFn9  func(ctx *encoderCtx, t []*capella.HistoricalSummary) (size int)
	}
	ctx := &encoderCtx{ds: ds}
	canSeek := enc.Seekable()
	ctx.exprs[0], err = sszutils.ResolveSpecValueWithDefault(ds, "SLOTS_PER_HISTORICAL_ROOT", 8192)
	if err != nil {
		return err
	}
	ctx.exprs[1], err = sszutils.ResolveSpecValueWithDefault(ds, "EPOCHS_PER_HISTORICAL_VECTOR", 65536)
	if err != nil {
		return err
	}
	ctx.exprs[2], err = sszutils.ResolveSpecValueWithDefault(ds, "EPOCHS_PER_SLASHINGS_VECTOR", 8192)
	if err != nil {
		return err
	}
	ctx.exprs[3], err = sszutils.ResolveSpecValueWithDefault(ds, "SYNC_COMMITTEE_SIZE", 512)
	if err != nil {
		return err
	}
	ctx.exprs[4], err = sszutils.ResolveSpecValueWithDefault(ds, "(MIN_SEED_LOOKAHEAD+1)*SLOTS_PER_EPOCH", 64)
	if err != nil {
		return err
	}
	ctx.exprs[5], err = sszutils.ResolveSpecValueWithDefault(ds, "HISTORICAL_ROOTS_LIMIT", 16777216)
	if err != nil {
		return err
	}
	ctx.exprs[6], err = sszutils.ResolveSpecValueWithDefault(ds, "EPOCHS_PER_ETH1_VOTING_PERIOD*SLOTS_PER_EPOCH", 2048)
	if err != nil {
		return err
	}
	ctx.exprs[7], err = sszutils.ResolveSpecValueWithDefault(ds, "VALIDATOR_REGISTRY_LIMIT", 1099511627776)
	if err != nil {
		return err
	}
	ctx.exprs[8], err = sszutils.ResolveSpecValueWithDefault(ds, "PENDING_DEPOSITS_LIMIT", 134217728)
	if err != nil {
		return err
	}
	ctx.exprs[9], err = sszutils.ResolveSpecValueWithDefault(ds, "PENDING_PARTIAL_WITHDRAWALS_LIMIT", 134217728)
	if err != nil {
		return err
	}
	ctx.exprs[10], err = sszutils.ResolveSpecValueWithDefault(ds, "PENDING_CONSOLIDATIONS_LIMIT", 262144)
	if err != nil {
		return err
	}
	// size for []phase0.Root
	ctx.sizeFn1 = func(ctx *encoderCtx, t []phase0.Root) (size int) {
		size += len(t) * 32
		return size
	}
	// size for []*phase0.ETH1Data
	ctx.sizeFn2 = func(ctx *encoderCtx, t []*phase0.ETH1Data) (size int) {
		size += len(t) * 72
		return size
	}
	// size for []*phase0.Validator
	ctx.sizeFn3 = func(ctx *encoderCtx, t []*phase0.Validator) (size int) {
		size += len(t) * 121
		return size
	}
	// size for []phase0.Gwei
	ctx.sizeFn4 = func(ctx *encoderCtx, t []phase0.Gwei) (size int) {
		size += len(t) * 8
		return size
	}
	// size for []altair.ParticipationFlags
	ctx.sizeFn5 = func(ctx *encoderCtx, t []altair.ParticipationFlags) (size int) {
		size += len(t)
		return size
	}
	// size for []altair.ParticipationFlags
	ctx.sizeFn6 = func(ctx *encoderCtx, t []altair.ParticipationFlags) (size int) {
		size += len(t)
		return size
	}
	// size for []uint64
	ctx.sizeFn7 = func(ctx *encoderCtx, t []uint64) (size int) {
		size += len(t) * 8
		return size
	}
	// size for *deneb.ExecutionPayloadHeader
	ctx.sizeFn8 = func(ctx *encoderCtx, t *deneb.ExecutionPayloadHeader) (size int) {
		size += t.SizeSSZ()
		return size
	}
	// size for []*capella.HistoricalSummary
	ctx.sizeFn9 = func(ctx *encoderCtx, t []*capella.HistoricalSummary) (size int) {
		size += len(t) * 64
		return size
	}
	// size for []*electra.PendingDeposit
	ctx.sizeFn10 = func(ctx *encoderCtx, t []*electra.PendingDeposit) (size int) {
		size += len(t) * 192
		return size
	}
	// size for []*electra.PendingPartialWithdrawal
	ctx.sizeFn11 = func(ctx *encoderCtx, t []*electra.PendingPartialWithdrawal) (size int) {
		size += len(t) * 24
		return size
	}
	// size for []*electra.PendingConsolidation
	ctx.sizeFn12 = func(ctx *encoderCtx, t []*electra.PendingConsolidation) (size int) {
		size += len(t) * 16
		return size
	}
	size1 := 32 * int(ctx.exprs[0])
	size2 := 32 * int(ctx.exprs[1])
	size3 := 8 * int(ctx.exprs[2])
	size5 := 48 * int(ctx.exprs[3])
	size4 := size5 + 48 // size expression for '*SyncCommittee'
	size6 := 8 * int(ctx.exprs[4])
	if t == nil {
		t = new(BeaconState)
	}
	dstlen := enc.GetPosition()
	dynoff := uint32(size1 + size1 + size2 + size3 + size4 + size4 + size6 + 489)
	{ // Field #0 'GenesisTime'
		enc.EncodeUint64(t.GenesisTime)
	}
	{ // Field #1 'GenesisValidatorsRoot'
		enc.EncodeBytes(t.GenesisValidatorsRoot[:32])
	}
	{ // Field #2 'Slot'
		enc.EncodeUint64(uint64(t.Slot))
	}
	{ // Field #3 'Fork'
		t := t.Fork
		if t == nil {
			t = new(phase0.Fork)
		}
		if buf, err := t.MarshalSSZTo(enc.GetBuffer()); err != nil {
			return sszutils.ErrorWithPath(err, "Fork")
		} else {
			enc.SetBuffer(buf)
		}
	}
	{ // Field #4 'LatestBlockHeader'
		t := t.LatestBlockHeader
		if t == nil {
			t = new(phase0.BeaconBlockHeader)
		}
		if buf, err := t.MarshalSSZTo(enc.GetBuffer()); err != nil {
			return sszutils.ErrorWithPath(err, "LatestBlockHeader")
		} else {
			enc.SetBuffer(buf)
		}
	}
	{ // Field #5 'BlockRoots'
		t := t.BlockRoots
		vlen := len(t)
		if vlen > int(ctx.exprs[0]) {
			return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, int(ctx.exprs[0])), "BlockRoots")
		}
		for idx1 := range vlen {
			enc.EncodeBytes(t[idx1][:32])
		}
		if vlen < int(ctx.exprs[0]) {
			enc.EncodeZeroPadding((int(ctx.exprs[0]) - vlen) * 32)
		}
	}
	{ // Field #6 'StateRoots'
		t := t.StateRoots
		vlen := len(t)
		if vlen > int(ctx.exprs[0]) {
			return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, int(ctx.exprs[0])), "StateRoots")
		}
		for idx1 := range vlen {
			enc.EncodeBytes(t[idx1][:32])
		}
		if vlen < int(ctx.exprs[0]) {
			enc.EncodeZeroPadding((int(ctx.exprs[0]) - vlen) * 32)
		}
	}
	// Offset #7 'HistoricalRoots'
	offset7 := enc.GetPosition()
	if canSeek {
		enc.EncodeOffset(0)
	} else {
		enc.EncodeOffset(dynoff)
		dynoff += uint32(ctx.sizeFn1(ctx, t.HistoricalRoots))
	}
	{ // Field #8 'ETH1Data'
		t := t.ETH1Data
		if t == nil {
			t = new(phase0.ETH1Data)
		}
		if buf, err := t.MarshalSSZTo(enc.GetBuffer()); err != nil {
			return sszutils.ErrorWithPath(err, "ETH1Data")
		} else {
			enc.SetBuffer(buf)
		}
	}
	// Offset #9 'ETH1DataVotes'
	offset9 := enc.GetPosition()
	if canSeek {
		enc.EncodeOffset(0)
	} else {
		enc.EncodeOffset(dynoff)
		dynoff += uint32(ctx.sizeFn2(ctx, t.ETH1DataVotes))
	}
	{ // Field #10 'ETH1DepositIndex'
		enc.EncodeUint64(t.ETH1DepositIndex)
	}
	// Offset #11 'Validators'
	offset11 := enc.GetPosition()
	if canSeek {
		enc.EncodeOffset(0)
	} else {
		enc.EncodeOffset(dynoff)
		dynoff += uint32(ctx.sizeFn3(ctx, t.Validators))
	}
	// Offset #12 'Balances'
	offset12 := enc.GetPosition()
	if canSeek {
		enc.EncodeOffset(0)
	} else {
		enc.EncodeOffset(dynoff)
		dynoff += uint32(ctx.sizeFn4(ctx, t.Balances))
	}
	{ // Field #13 'RANDAOMixes'
		t := t.RANDAOMixes
		vlen := len(t)
		if vlen > int(ctx.exprs[1]) {
			return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, int(ctx.exprs[1])), "RANDAOMixes")
		}
		for idx1 := range vlen {
			enc.EncodeBytes(t[idx1][:32])
		}
		if vlen < int(ctx.exprs[1]) {
			enc.EncodeZeroPadding((int(ctx.exprs[1]) - vlen) * 32)
		}
	}
	{ // Field #14 'Slashings'
		t := t.Slashings
		vlen := len(t)
		if vlen > int(ctx.exprs[2]) {
			return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, int(ctx.exprs[2])), "Slashings")
		}
		sszutils.EncodeUint64Slice(enc, t[:vlen])
		if vlen < int(ctx.exprs[2]) {
			enc.EncodeZeroPadding((int(ctx.exprs[2]) - vlen) * 8)
		}
	}
	// Offset #15 'PreviousEpochParticipation'
	offset15 := enc.GetPosition()
	if canSeek {
		enc.EncodeOffset(0)
	} else {
		enc.EncodeOffset(dynoff)
		dynoff += uint32(ctx.sizeFn5(ctx, t.PreviousEpochParticipation))
	}
	// Offset #16 'CurrentEpochParticipation'
	offset16 := enc.GetPosition()
	if canSeek {
		enc.EncodeOffset(0)
	} else {
		enc.EncodeOffset(dynoff)
		dynoff += uint32(ctx.sizeFn6(ctx, t.CurrentEpochParticipation))
	}
	{ // Field #17 'JustificationBits'
		vlen := len(t.JustificationBits)
		if vlen > 1 {
			return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 1), "JustificationBits")
		}
		enc.EncodeBytes(t.JustificationBits[:vlen])
		if vlen < 1 {
			enc.EncodeZeroPadding((1 - vlen) * 1)
		}
	}
	{ // Field #18 'PreviousJustifiedCheckpoint'
		t := t.PreviousJustifiedCheckpoint
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if buf, err := t.MarshalSSZTo(enc.GetBuffer()); err != nil {
			return sszutils.ErrorWithPath(err, "PreviousJustifiedCheckpoint")
		} else {
			enc.SetBuffer(buf)
		}
	}
	{ // Field #19 'CurrentJustifiedCheckpoint'
		t := t.CurrentJustifiedCheckpoint
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if buf, err := t.MarshalSSZTo(enc.GetBuffer()); err != nil {
			return sszutils.ErrorWithPath(err, "CurrentJustifiedCheckpoint")
		} else {
			enc.SetBuffer(buf)
		}
	}
	{ // Field #20 'FinalizedCheckpoint'
		t := t.FinalizedCheckpoint
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if buf, err := t.MarshalSSZTo(enc.GetBuffer()); err != nil {
			return sszutils.ErrorWithPath(err, "FinalizedCheckpoint")
		} else {
			enc.SetBuffer(buf)
		}
	}
	// Offset #21 'InactivityScores'
	offset21 := enc.GetPosition()
	if canSeek {
		enc.EncodeOffset(0)
	} else {
		enc.EncodeOffset(dynoff)
		dynoff += uint32(ctx.sizeFn7(ctx, t.InactivityScores))
	}
	{ // Field #22 'CurrentSyncCommittee'
		t := t.CurrentSyncCommittee
		if t == nil {
			t = new(altair.SyncCommittee)
		}
		{ // Field #0 'Pubkeys'
			t := t.Pubkeys
			vlen := len(t)
			if vlen > int(ctx.exprs[3]) {
				return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, int(ctx.exprs[3])), "CurrentSyncCommittee.Pubkeys")
			}
			for idx1 := range vlen {
				enc.EncodeBytes(t[idx1][:48])
			}
			if vlen < int(ctx.exprs[3]) {
				enc.EncodeZeroPadding((int(ctx.exprs[3]) - vlen) * 48)
			}
		}
		{ // Field #1 'AggregatePubkey'
			enc.EncodeBytes(t.AggregatePubkey[:48])
		}
	}
	{ // Field #23 'NextSyncCommittee'
		t := t.NextSyncCommittee
		if t == nil {
			t = new(altair.SyncCommittee)
		}
		{ // Field #0 'Pubkeys'
			t := t.Pubkeys
			vlen := len(t)
			if vlen > int(ctx.exprs[3]) {
				return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, int(ctx.exprs[3])), "NextSyncCommittee.Pubkeys")
			}
			for idx1 := range vlen {
				enc.EncodeBytes(t[idx1][:48])
			}
			if vlen < int(ctx.exprs[3]) {
				enc.EncodeZeroPadding((int(ctx.exprs[3]) - vlen) * 48)
			}
		}
		{ // Field #1 'AggregatePubkey'
			enc.EncodeBytes(t.AggregatePubkey[:48])
		}
	}
	// Offset #24 'LatestExecutionPayloadHeader'
	offset24 := enc.GetPosition()
	if canSeek {
		enc.EncodeOffset(0)
	} else {
		enc.EncodeOffset(dynoff)
		dynoff += uint32(ctx.sizeFn8(ctx, t.LatestExecutionPayloadHeader))
	}
	{ // Field #25 'NextWithdrawalIndex'
		enc.EncodeUint64(uint64(t.NextWithdrawalIndex))
	}
	{ // Field #26 'NextWithdrawalValidatorIndex'
		enc.EncodeUint64(uint64(t.NextWithdrawalValidatorIndex))
	}
	// Offset #27 'HistoricalSummaries'
	offset27 := enc.GetPosition()
	if canSeek {
		enc.EncodeOffset(0)
	} else {
		enc.EncodeOffset(dynoff)
		dynoff += uint32(ctx.sizeFn9(ctx, t.HistoricalSummaries))
	}
	{ // Field #28 'DepositRequestsStartIndex'
		enc.EncodeUint64(t.DepositRequestsStartIndex)
	}
	{ // Field #29 'DepositBalanceToConsume'
		enc.EncodeUint64(uint64(t.DepositBalanceToConsume))
	}
	{ // Field #30 'ExitBalanceToConsume'
		enc.EncodeUint64(uint64(t.ExitBalanceToConsume))
	}
	{ // Field #31 'EarliestExitEpoch'
		enc.EncodeUint64(uint64(t.EarliestExitEpoch))
	}
	{ // Field #32 'ConsolidationBalanceToConsume'
		enc.EncodeUint64(uint64(t.ConsolidationBalanceToConsume))
	}
	{ // Field #33 'EarliestConsolidationEpoch'
		enc.EncodeUint64(uint64(t.EarliestConsolidationEpoch))
	}
	// Offset #34 'PendingDeposits'
	offset34 := enc.GetPosition()
	if canSeek {
		enc.EncodeOffset(0)
	} else {
		enc.EncodeOffset(dynoff)
		dynoff += uint32(ctx.sizeFn10(ctx, t.PendingDeposits))
	}
	// Offset #35 'PendingPartialWithdrawals'
	offset35 := enc.GetPosition()
	if canSeek {
		enc.EncodeOffset(0)
	} else {
		enc.EncodeOffset(dynoff)
		dynoff += uint32(ctx.sizeFn11(ctx, t.PendingPartialWithdrawals))
	}
	// Offset #36 'PendingConsolidations'
	offset36 := enc.GetPosition()
	if canSeek {
		enc.EncodeOffset(0)
	} else {
		enc.EncodeOffset(dynoff)
		dynoff += uint32(ctx.sizeFn12(ctx, t.PendingConsolidations))
	}
	{ // Field #37 'ProposerLookahead'
		t := t.ProposerLookahead
		vlen := len(t)
		if vlen > int(ctx.exprs[4]) {
			return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, int(ctx.exprs[4])), "ProposerLookahead")
		}
		sszutils.EncodeUint64Slice(enc, t[:vlen])
		if vlen < int(ctx.exprs[4]) {
			enc.EncodeZeroPadding((int(ctx.exprs[4]) - vlen) * 8)
		}
	}
	{ // Dynamic Field #7 'HistoricalRoots'
		if canSeek {
			enc.EncodeOffsetAt(offset7, uint32(enc.GetPosition()-dstlen))
		}
		t := t.HistoricalRoots
		vlen := len(t)
		if vlen > int(ctx.exprs[5]) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(ctx.exprs[5])), "HistoricalRoots")
		}
		for idx1 := range vlen {
			enc.EncodeBytes(t[idx1][:32])
		}
	}
	{ // Dynamic Field #9 'ETH1DataVotes'
		if canSeek {
			enc.EncodeOffsetAt(offset9, uint32(enc.GetPosition()-dstlen))
		}
		t := t.ETH1DataVotes
		vlen := len(t)
		if vlen > int(ctx.exprs[6]) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(ctx.exprs[6])), "ETH1DataVotes")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(phase0.ETH1Data)
			}
			if buf, err := t.MarshalSSZTo(enc.GetBuffer()); err != nil {
				return sszutils.ErrorWithPathf(err, "ETH1DataVotes[%d]", idx1)
			} else {
				enc.SetBuffer(buf)
			}
		}
	}
	{ // Dynamic Field #11 'Validators'
		if canSeek {
			enc.EncodeOffsetAt(offset11, uint32(enc.GetPosition()-dstlen))
		}
		t := t.Validators
		vlen := len(t)
		if vlen > int(ctx.exprs[7]) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(ctx.exprs[7])), "Validators")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(phase0.Validator)
			}
			if buf, err := t.MarshalSSZTo(enc.GetBuffer()); err != nil {
				return sszutils.ErrorWithPathf(err, "Validators[%d]", idx1)
			} else {
				enc.SetBuffer(buf)
			}
		}
	}
	{ // Dynamic Field #12 'Balances'
		if canSeek {
			enc.EncodeOffsetAt(offset12, uint32(enc.GetPosition()-dstlen))
		}
		t := t.Balances
		vlen := len(t)
		if vlen > int(ctx.exprs[7]) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(ctx.exprs[7])), "Balances")
		}
		sszutils.EncodeUint64Slice(enc, t[:vlen])
	}
	{ // Dynamic Field #15 'PreviousEpochParticipation'
		if canSeek {
			enc.EncodeOffsetAt(offset15, uint32(enc.GetPosition()-dstlen))
		}
		t := t.PreviousEpochParticipation
		vlen := len(t)
		if vlen > int(ctx.exprs[7]) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(ctx.exprs[7])), "PreviousEpochParticipation")
		}
		for idx1 := range vlen {
			enc.EncodeUint8(byte(t[idx1]))
		}
	}
	{ // Dynamic Field #16 'CurrentEpochParticipation'
		if canSeek {
			enc.EncodeOffsetAt(offset16, uint32(enc.GetPosition()-dstlen))
		}
		t := t.CurrentEpochParticipation
		vlen := len(t)
		if vlen > int(ctx.exprs[7]) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(ctx.exprs[7])), "CurrentEpochParticipation")
		}
		for idx1 := range vlen {
			enc.EncodeUint8(byte(t[idx1]))
		}
	}
	{ // Dynamic Field #21 'InactivityScores'
		if canSeek {
			enc.EncodeOffsetAt(offset21, uint32(enc.GetPosition()-dstlen))
		}
		t := t.InactivityScores
		vlen := len(t)
		if vlen > int(ctx.exprs[7]) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(ctx.exprs[7])), "InactivityScores")
		}
		sszutils.EncodeUint64Slice(enc, t[:vlen])
	}
	{ // Dynamic Field #24 'LatestExecutionPayloadHeader'
		if canSeek {
			enc.EncodeOffsetAt(offset24, uint32(enc.GetPosition()-dstlen))
		}
		t := t.LatestExecutionPayloadHeader
		if t == nil {
			t = new(deneb.ExecutionPayloadHeader)
		}
		if buf, err := t.MarshalSSZTo(enc.GetBuffer()); err != nil {
			return sszutils.ErrorWithPath(err, "LatestExecutionPayloadHeader")
		} else {
			enc.SetBuffer(buf)
		}
	}
	{ // Dynamic Field #27 'HistoricalSummaries'
		if canSeek {
			enc.EncodeOffsetAt(offset27, uint32(enc.GetPosition()-dstlen))
		}
		t := t.HistoricalSummaries
		vlen := len(t)
		if vlen > int(ctx.exprs[5]) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(ctx.exprs[5])), "HistoricalSummaries")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(capella.HistoricalSummary)
			}
			if buf, err := t.MarshalSSZTo(enc.GetBuffer()); err != nil {
				return sszutils.ErrorWithPathf(err, "HistoricalSummaries[%d]", idx1)
			} else {
				enc.SetBuffer(buf)
			}
		}
	}
	{ // Dynamic Field #34 'PendingDeposits'
		if canSeek {
			enc.EncodeOffsetAt(offset34, uint32(enc.GetPosition()-dstlen))
		}
		t := t.PendingDeposits
		vlen := len(t)
		if vlen > int(ctx.exprs[8]) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(ctx.exprs[8])), "PendingDeposits")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(electra.PendingDeposit)
			}
			if buf, err := t.MarshalSSZTo(enc.GetBuffer()); err != nil {
				return sszutils.ErrorWithPathf(err, "PendingDeposits[%d]", idx1)
			} else {
				enc.SetBuffer(buf)
			}
		}
	}
	{ // Dynamic Field #35 'PendingPartialWithdrawals'
		if canSeek {
			enc.EncodeOffsetAt(offset35, uint32(enc.GetPosition()-dstlen))
		}
		t := t.PendingPartialWithdrawals
		vlen := len(t)
		if vlen > int(ctx.exprs[9]) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(ctx.exprs[9])), "PendingPartialWithdrawals")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(electra.PendingPartialWithdrawal)
			}
			if buf, err := t.MarshalSSZTo(enc.GetBuffer()); err != nil {
				return sszutils.ErrorWithPathf(err, "PendingPartialWithdrawals[%d]", idx1)
			} else {
				enc.SetBuffer(buf)
			}
		}
	}
	{ // Dynamic Field #36 'PendingConsolidations'
		if canSeek {
			enc.EncodeOffsetAt(offset36, uint32(enc.GetPosition()-dstlen))
		}
		t := t.PendingConsolidations
		vlen := len(t)
		if vlen > int(ctx.exprs[10]) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, int(ctx.exprs[10])), "PendingConsolidations")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(electra.PendingConsolidation)
			}
			if buf, err := t.MarshalSSZTo(enc.GetBuffer()); err != nil {
				return sszutils.ErrorWithPathf(err, "PendingConsolidations[%d]", idx1)
			} else {
				enc.SetBuffer(buf)
			}
		}
	}
	return nil
}

// UnmarshalSSZ unmarshals the *BeaconState from SSZ-encoded bytes.
func (t *BeaconState) UnmarshalSSZ(buf []byte) (err error) {
	buflen := len(buf)
	if buflen < 2737225 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 2737225)
	}
	{ // Field #0 'GenesisTime' (static)
		buf := buf[0:8]
		t.GenesisTime = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #1 'GenesisValidatorsRoot' (static)
		buf := buf[8:40]
		copy(t.GenesisValidatorsRoot[:], buf)
	}
	{ // Field #2 'Slot' (static)
		buf := buf[40:48]
		t.Slot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #3 'Fork' (static)
		buf := buf[48:64]
		if t.Fork == nil {
			t.Fork = new(phase0.Fork)
		}
		if err = t.Fork.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Fork")
		}
	}
	{ // Field #4 'LatestBlockHeader' (static)
		buf := buf[64:176]
		if t.LatestBlockHeader == nil {
			t.LatestBlockHeader = new(phase0.BeaconBlockHeader)
		}
		if err = t.LatestBlockHeader.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "LatestBlockHeader")
		}
	}
	{ // Field #5 'BlockRoots' (static)
		buf := buf[176:262320]
		val1 := t.BlockRoots
		val1 = sszutils.ExpandSlice(val1, 8192)
		for idx1 := range 8192 {
			buf := buf[32*idx1 : 32*(idx1+1)]
			copy(val1[idx1][:], buf)
		}
		t.BlockRoots = val1
	}
	{ // Field #6 'StateRoots' (static)
		buf := buf[262320:524464]
		val2 := t.StateRoots
		val2 = sszutils.ExpandSlice(val2, 8192)
		for idx1 := range 8192 {
			buf := buf[32*idx1 : 32*(idx1+1)]
			copy(val2[idx1][:], buf)
		}
		t.StateRoots = val2
	}
	// Field #7 'HistoricalRoots' (offset)
	offset7 := int(binary.LittleEndian.Uint32(buf[524464:524468]))
	if offset7 != 2737225 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset7, 2737225), "HistoricalRoots:o")
	}
	{ // Field #8 'ETH1Data' (static)
		buf := buf[524468:524540]
		if t.ETH1Data == nil {
			t.ETH1Data = new(phase0.ETH1Data)
		}
		if err = t.ETH1Data.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "ETH1Data")
		}
	}
	// Field #9 'ETH1DataVotes' (offset)
	offset9 := int(binary.LittleEndian.Uint32(buf[524540:524544]))
	if offset9 < offset7 || offset9 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset9, offset7, buflen), "ETH1DataVotes:o")
	}
	{ // Field #10 'ETH1DepositIndex' (static)
		buf := buf[524544:524552]
		t.ETH1DepositIndex = binary.LittleEndian.Uint64(buf)
	}
	// Field #11 'Validators' (offset)
	offset11 := int(binary.LittleEndian.Uint32(buf[524552:524556]))
	if offset11 < offset9 || offset11 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset11, offset9, buflen), "Validators:o")
	}
	// Field #12 'Balances' (offset)
	offset12 := int(binary.LittleEndian.Uint32(buf[524556:524560]))
	if offset12 < offset11 || offset12 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset12, offset11, buflen), "Balances:o")
	}
	{ // Field #13 'RANDAOMixes' (static)
		buf := buf[524560:2621712]
		val3 := t.RANDAOMixes
		val3 = sszutils.ExpandSlice(val3, 65536)
		for idx1 := range 65536 {
			buf := buf[32*idx1 : 32*(idx1+1)]
			copy(val3[idx1][:], buf)
		}
		t.RANDAOMixes = val3
	}
	{ // Field #14 'Slashings' (static)
		buf := buf[2621712:2687248]
		val4 := t.Slashings
		val4 = sszutils.ExpandSlice(val4, 8192)
		sszutils.UnmarshalUint64Slice(val4[:8192], buf)
		t.Slashings = val4
	}
	// Field #15 'PreviousEpochParticipation' (offset)
	offset15 := int(binary.LittleEndian.Uint32(buf[2687248:2687252]))
	if offset15 < offset12 || offset15 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset15, offset12, buflen), "PreviousEpochParticipation:o")
	}
	// Field #16 'CurrentEpochParticipation' (offset)
	offset16 := int(binary.LittleEndian.Uint32(buf[2687252:2687256]))
	if offset16 < offset15 || offset16 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset16, offset15, buflen), "CurrentEpochParticipation:o")
	}
	{ // Field #17 'JustificationBits' (static)
		buf := buf[2687256:2687257]
		t.JustificationBits = sszutils.ExpandSlice(t.JustificationBits, 1)
		copy(t.JustificationBits[:], buf)
	}
	{ // Field #18 'PreviousJustifiedCheckpoint' (static)
		buf := buf[2687257:2687297]
		if t.PreviousJustifiedCheckpoint == nil {
			t.PreviousJustifiedCheckpoint = new(phase0.Checkpoint)
		}
		if err = t.PreviousJustifiedCheckpoint.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "PreviousJustifiedCheckpoint")
		}
	}
	{ // Field #19 'CurrentJustifiedCheckpoint' (static)
		buf := buf[2687297:2687337]
		if t.CurrentJustifiedCheckpoint == nil {
			t.CurrentJustifiedCheckpoint = new(phase0.Checkpoint)
		}
		if err = t.CurrentJustifiedCheckpoint.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "CurrentJustifiedCheckpoint")
		}
	}
	{ // Field #20 'FinalizedCheckpoint' (static)
		buf := buf[2687337:2687377]
		if t.FinalizedCheckpoint == nil {
			t.FinalizedCheckpoint = new(phase0.Checkpoint)
		}
		if err = t.FinalizedCheckpoint.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "FinalizedCheckpoint")
		}
	}
	// Field #21 'InactivityScores' (offset)
	offset21 := int(binary.LittleEndian.Uint32(buf[2687377:2687381]))
	if offset21 < offset16 || offset21 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset21, offset16, buflen), "InactivityScores:o")
	}
	{ // Field #22 'CurrentSyncCommittee' (static)
		buf := buf[2687381:2712005]
		if t.CurrentSyncCommittee == nil {
			t.CurrentSyncCommittee = new(altair.SyncCommittee)
		}
		if err = t.CurrentSyncCommittee.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "CurrentSyncCommittee")
		}
	}
	{ // Field #23 'NextSyncCommittee' (static)
		buf := buf[2712005:2736629]
		if t.NextSyncCommittee == nil {
			t.NextSyncCommittee = new(altair.SyncCommittee)
		}
		if err = t.NextSyncCommittee.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "NextSyncCommittee")
		}
	}
	// Field #24 'LatestExecutionPayloadHeader' (offset)
	offset24 := int(binary.LittleEndian.Uint32(buf[2736629:2736633]))
	if offset24 < offset21 || offset24 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset24, offset21, buflen), "LatestExecutionPayloadHeader:o")
	}
	{ // Field #25 'NextWithdrawalIndex' (static)
		buf := buf[2736633:2736641]
		t.NextWithdrawalIndex = capella.WithdrawalIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #26 'NextWithdrawalValidatorIndex' (static)
		buf := buf[2736641:2736649]
		t.NextWithdrawalValidatorIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	// Field #27 'HistoricalSummaries' (offset)
	offset27 := int(binary.LittleEndian.Uint32(buf[2736649:2736653]))
	if offset27 < offset24 || offset27 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset27, offset24, buflen), "HistoricalSummaries:o")
	}
	{ // Field #28 'DepositRequestsStartIndex' (static)
		buf := buf[2736653:2736661]
		t.DepositRequestsStartIndex = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #29 'DepositBalanceToConsume' (static)
		buf := buf[2736661:2736669]
		t.DepositBalanceToConsume = phase0.Gwei(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #30 'ExitBalanceToConsume' (static)
		buf := buf[2736669:2736677]
		t.ExitBalanceToConsume = phase0.Gwei(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #31 'EarliestExitEpoch' (static)
		buf := buf[2736677:2736685]
		t.EarliestExitEpoch = phase0.Epoch(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #32 'ConsolidationBalanceToConsume' (static)
		buf := buf[2736685:2736693]
		t.ConsolidationBalanceToConsume = phase0.Gwei(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #33 'EarliestConsolidationEpoch' (static)
		buf := buf[2736693:2736701]
		t.EarliestConsolidationEpoch = phase0.Epoch(binary.LittleEndian.Uint64(buf))
	}
	// Field #34 'PendingDeposits' (offset)
	offset34 := int(binary.LittleEndian.Uint32(buf[2736701:2736705]))
	if offset34 < offset27 || offset34 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset34, offset27, buflen), "PendingDeposits:o")
	}
	// Field #35 'PendingPartialWithdrawals' (offset)
	offset35 := int(binary.LittleEndian.Uint32(buf[2736705:2736709]))
	if offset35 < offset34 || offset35 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset35, offset34, buflen), "PendingPartialWithdrawals:o")
	}
	// Field #36 'PendingConsolidations' (offset)
	offset36 := int(binary.LittleEndian.Uint32(buf[2736709:2736713]))
	if offset36 < offset35 || offset36 > buflen {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset36, offset35, buflen), "PendingConsolidations:o")
	}
	{ // Field #37 'ProposerLookahead' (static)
		buf := buf[2736713:2737225]
		val5 := t.ProposerLookahead
		val5 = sszutils.ExpandSlice(val5, 64)
		sszutils.UnmarshalUint64Slice(val5[:64], buf)
		t.ProposerLookahead = val5
	}
	{ // Field #7 'HistoricalRoots' (dynamic)
		buf := buf[offset7:offset9]
		val6 := t.HistoricalRoots
		itemCount := len(buf) / 32
		if len(buf)%32 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 32), "HistoricalRoots")
		}
		if itemCount > 16777216 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 16777216), "HistoricalRoots")
		}
		val6 = sszutils.ExpandSlice(val6, itemCount)
		for idx1 := range itemCount {
			buf := buf[32*idx1 : 32*(idx1+1)]
			copy(val6[idx1][:], buf)
		}
		t.HistoricalRoots = val6
	}
	{ // Field #9 'ETH1DataVotes' (dynamic)
		buf := buf[offset9:offset11]
		val7 := t.ETH1DataVotes
		itemCount := len(buf) / 72
		if len(buf)%72 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 72), "ETH1DataVotes")
		}
		if itemCount > 2048 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 2048), "ETH1DataVotes")
		}
		val7 = sszutils.ExpandSlice(val7, itemCount)
		for idx1 := range itemCount {
			if val7[idx1] == nil {
				val7[idx1] = new(phase0.ETH1Data)
			}
			buf := buf[72*idx1 : 72*(idx1+1)]
			if err = val7[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "ETH1DataVotes[%d]", idx1)
			}
		}
		t.ETH1DataVotes = val7
	}
	{ // Field #11 'Validators' (dynamic)
		buf := buf[offset11:offset12]
		val8 := t.Validators
		itemCount := len(buf) / 121
		if len(buf)%121 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 121), "Validators")
		}
		if itemCount > 1099511627776 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 1099511627776), "Validators")
		}
		val8 = sszutils.ExpandSlice(val8, itemCount)
		for idx1 := range itemCount {
			if val8[idx1] == nil {
				val8[idx1] = new(phase0.Validator)
			}
			buf := buf[121*idx1 : 121*(idx1+1)]
			if err = val8[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Validators[%d]", idx1)
			}
		}
		t.Validators = val8
	}
	{ // Field #12 'Balances' (dynamic)
		buf := buf[offset12:offset15]
		val9 := t.Balances
		itemCount := len(buf) / 8
		if len(buf)%8 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 8), "Balances")
		}
		if itemCount > 1099511627776 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 1099511627776), "Balances")
		}
		val9 = sszutils.ExpandSlice(val9, itemCount)
		sszutils.UnmarshalUint64Slice(val9, buf)
		t.Balances = val9
	}
	{ // Field #15 'PreviousEpochParticipation' (dynamic)
		buf := buf[offset15:offset16]
		val10 := t.PreviousEpochParticipation
		itemCount := len(buf)
		if itemCount > 1099511627776 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 1099511627776), "PreviousEpochParticipation")
		}
		val10 = sszutils.ExpandSlice(val10, itemCount)
		for idx1 := range itemCount {
			buf := buf[1*idx1 : 1*(idx1+1)]
			val10[idx1] = altair.ParticipationFlags(buf[0])
		}
		t.PreviousEpochParticipation = val10
	}
	{ // Field #16 'CurrentEpochParticipation' (dynamic)
		buf := buf[offset16:offset21]
		val11 := t.CurrentEpochParticipation
		itemCount := len(buf)
		if itemCount > 1099511627776 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 1099511627776), "CurrentEpochParticipation")
		}
		val11 = sszutils.ExpandSlice(val11, itemCount)
		for idx1 := range itemCount {
			buf := buf[1*idx1 : 1*(idx1+1)]
			val11[idx1] = altair.ParticipationFlags(buf[0])
		}
		t.CurrentEpochParticipation = val11
	}
	{ // Field #21 'InactivityScores' (dynamic)
		buf := buf[offset21:offset24]
		val12 := t.InactivityScores
		itemCount := len(buf) / 8
		if len(buf)%8 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 8), "InactivityScores")
		}
		if itemCount > 1099511627776 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 1099511627776), "InactivityScores")
		}
		val12 = sszutils.ExpandSlice(val12, itemCount)
		sszutils.UnmarshalUint64Slice(val12, buf)
		t.InactivityScores = val12
	}
	{ // Field #24 'LatestExecutionPayloadHeader' (dynamic)
		buf := buf[offset24:offset27]
		if t.LatestExecutionPayloadHeader == nil {
			t.LatestExecutionPayloadHeader = new(deneb.ExecutionPayloadHeader)
		}
		if err = t.LatestExecutionPayloadHeader.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "LatestExecutionPayloadHeader")
		}
	}
	{ // Field #27 'HistoricalSummaries' (dynamic)
		buf := buf[offset27:offset34]
		val13 := t.HistoricalSummaries
		itemCount := len(buf) / 64
		if len(buf)%64 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 64), "HistoricalSummaries")
		}
		if itemCount > 16777216 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 16777216), "HistoricalSummaries")
		}
		val13 = sszutils.ExpandSlice(val13, itemCount)
		for idx1 := range itemCount {
			if val13[idx1] == nil {
				val13[idx1] = new(capella.HistoricalSummary)
			}
			buf := buf[64*idx1 : 64*(idx1+1)]
			if err = val13[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "HistoricalSummaries[%d]", idx1)
			}
		}
		t.HistoricalSummaries = val13
	}
	{ // Field #34 'PendingDeposits' (dynamic)
		buf := buf[offset34:offset35]
		val14 := t.PendingDeposits
		itemCount := len(buf) / 192
		if len(buf)%192 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 192), "PendingDeposits")
		}
		if itemCount > 134217728 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 134217728), "PendingDeposits")
		}
		val14 = sszutils.ExpandSlice(val14, itemCount)
		for idx1 := range itemCount {
			if val14[idx1] == nil {
				val14[idx1] = new(electra.PendingDeposit)
			}
			buf := buf[192*idx1 : 192*(idx1+1)]
			if err = val14[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "PendingDeposits[%d]", idx1)
			}
		}
		t.PendingDeposits = val14
	}
	{ // Field #35 'PendingPartialWithdrawals' (dynamic)
		buf := buf[offset35:offset36]
		val15 := t.PendingPartialWithdrawals
		itemCount := len(buf) / 24
		if len(buf)%24 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 24), "PendingPartialWithdrawals")
		}
		if itemCount > 134217728 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 134217728), "PendingPartialWithdrawals")
		}
		val15 = sszutils.ExpandSlice(val15, itemCount)
		for idx1 := range itemCount {
			if val15[idx1] == nil {
				val15[idx1] = new(electra.PendingPartialWithdrawal)
			}
			buf := buf[24*idx1 : 24*(idx1+1)]
			if err = val15[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "PendingPartialWithdrawals[%d]", idx1)
			}
		}
		t.PendingPartialWithdrawals = val15
	}
	{ // Field #36 'PendingConsolidations' (dynamic)
		buf := buf[offset36:]
		val16 := t.PendingConsolidations
		itemCount := len(buf) / 16
		if len(buf)%16 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 16), "PendingConsolidations")
		}
		if itemCount > 262144 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 262144), "PendingConsolidations")
		}
		val16 = sszutils.ExpandSlice(val16, itemCount)
		for idx1 := range itemCount {
			if val16[idx1] == nil {
				val16[idx1] = new(electra.PendingConsolidation)
			}
			buf := buf[16*idx1 : 16*(idx1+1)]
			if err = val16[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "PendingConsolidations[%d]", idx1)
			}
		}
		t.PendingConsolidations = val16
	}
	return nil
}

// UnmarshalSSZDecoder unmarshals the *BeaconState from the given SSZ decoder using dynamic specifications.
func (t *BeaconState) UnmarshalSSZDecoder(ds sszutils.DynamicSpecs, dec sszutils.Decoder) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "SLOTS_PER_HISTORICAL_ROOT", 8192)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "EPOCHS_PER_HISTORICAL_VECTOR", 65536)
	if err != nil {
		return err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "EPOCHS_PER_SLASHINGS_VECTOR", 8192)
	if err != nil {
		return err
	}
	expr3, err := sszutils.ResolveSpecValueWithDefault(ds, "SYNC_COMMITTEE_SIZE", 512)
	if err != nil {
		return err
	}
	expr4, err := sszutils.ResolveSpecValueWithDefault(ds, "(MIN_SEED_LOOKAHEAD+1)*SLOTS_PER_EPOCH", 64)
	if err != nil {
		return err
	}
	expr5, err := sszutils.ResolveSpecValueWithDefault(ds, "HISTORICAL_ROOTS_LIMIT", 16777216)
	if err != nil {
		return err
	}
	expr6, err := sszutils.ResolveSpecValueWithDefault(ds, "EPOCHS_PER_ETH1_VOTING_PERIOD*SLOTS_PER_EPOCH", 2048)
	if err != nil {
		return err
	}
	expr7, err := sszutils.ResolveSpecValueWithDefault(ds, "VALIDATOR_REGISTRY_LIMIT", 1099511627776)
	if err != nil {
		return err
	}
	expr8, err := sszutils.ResolveSpecValueWithDefault(ds, "PENDING_DEPOSITS_LIMIT", 134217728)
	if err != nil {
		return err
	}
	expr9, err := sszutils.ResolveSpecValueWithDefault(ds, "PENDING_PARTIAL_WITHDRAWALS_LIMIT", 134217728)
	if err != nil {
		return err
	}
	expr10, err := sszutils.ResolveSpecValueWithDefault(ds, "PENDING_CONSOLIDATIONS_LIMIT", 262144)
	if err != nil {
		return err
	}
	size1 := 32 * int(expr0)
	size2 := 32 * int(expr1)
	size3 := 8 * int(expr2)
	size5 := 48 * int(expr3)
	size4 := size5 + 48 // size expression for '*SyncCommittee'
	size6 := 8 * int(expr4)
	totalSize := size1+size1+size2+size3+size4+size4+size6+489
	maxOffset := uint32(dec.GetLength())
	startPos0 := dec.GetPosition()
	if maxOffset < uint32(totalSize) {
		return sszutils.ErrFixedFieldsEOFFn(maxOffset, uint32(totalSize))
	}
	// Field #0 'GenesisTime' (static)
	if val, err := dec.DecodeUint64(); err != nil {
		return sszutils.ErrorWithPath(err, "GenesisTime")
	} else {
		t.GenesisTime = val
	}
	// Field #1 'GenesisValidatorsRoot' (static)
	if _, err = dec.DecodeBytes(t.GenesisValidatorsRoot[:32]); err != nil {
		return err
	}
	// Field #2 'Slot' (static)
	if val, err := dec.DecodeUint64(); err != nil {
		return sszutils.ErrorWithPath(err, "Slot")
	} else {
		t.Slot = phase0.Slot(val)
	}
	// Field #3 'Fork' (static)
	if t.Fork == nil {
		t.Fork = new(phase0.Fork)
	}
	if buf, err := dec.DecodeBytesBuf(16); err != nil {
		return sszutils.ErrorWithPath(err, "Fork")
	} else if err = t.Fork.UnmarshalSSZ(buf); err != nil {
		return sszutils.ErrorWithPath(err, "Fork")
	}
	// Field #4 'LatestBlockHeader' (static)
	if t.LatestBlockHeader == nil {
		t.LatestBlockHeader = new(phase0.BeaconBlockHeader)
	}
	if buf, err := dec.DecodeBytesBuf(112); err != nil {
		return sszutils.ErrorWithPath(err, "LatestBlockHeader")
	} else if err = t.LatestBlockHeader.UnmarshalSSZ(buf); err != nil {
		return sszutils.ErrorWithPath(err, "LatestBlockHeader")
	}
	{ // Field #5 'BlockRoots' (static)
		val1 := t.BlockRoots
		val1 = sszutils.ExpandSlice(val1, int(expr0))
		startPos1 := dec.GetPosition()
		for idx1 := range int(expr0) {
			if _, err = dec.DecodeBytes(val1[idx1][:32]); err != nil {
				return err
			}
			if dec.GetPosition() != startPos1+int(32*(idx1+1)) {
				return sszutils.ErrorWithPathf(sszutils.ErrStaticElementNotConsumedFn(dec.GetPosition(), startPos1+int(32*(idx1+1))), "BlockRoots[%d]", idx1)
			}
		}
		t.BlockRoots = val1
	}
	{ // Field #6 'StateRoots' (static)
		val2 := t.StateRoots
		val2 = sszutils.ExpandSlice(val2, int(expr0))
		startPos2 := dec.GetPosition()
		for idx1 := range int(expr0) {
			if _, err = dec.DecodeBytes(val2[idx1][:32]); err != nil {
				return err
			}
			if dec.GetPosition() != startPos2+int(32*(idx1+1)) {
				return sszutils.ErrorWithPathf(sszutils.ErrStaticElementNotConsumedFn(dec.GetPosition(), startPos2+int(32*(idx1+1))), "StateRoots[%d]", idx1)
			}
		}
		t.StateRoots = val2
	}
	// Field #7 'HistoricalRoots' (offset)
	offset7, err := dec.DecodeOffset()
	if err != nil {
		return sszutils.ErrorWithPath(err, "HistoricalRoots")
	}
	if offset7 != uint32(totalSize) {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset7, totalSize), "HistoricalRoots")
	}
	// Field #8 'ETH1Data' (static)
	if t.ETH1Data == nil {
		t.ETH1Data = new(phase0.ETH1Data)
	}
	if buf, err := dec.DecodeBytesBuf(72); err != nil {
		return sszutils.ErrorWithPath(err, "ETH1Data")
	} else if err = t.ETH1Data.UnmarshalSSZ(buf); err != nil {
		return sszutils.ErrorWithPath(err, "ETH1Data")
	}
	// Field #9 'ETH1DataVotes' (offset)
	offset9, err := dec.DecodeOffset()
	if err != nil {
		return sszutils.ErrorWithPath(err, "ETH1DataVotes")
	}
	if offset9 < offset7 || offset9 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset9, offset7, maxOffset), "ETH1DataVotes")
	}
	// Field #10 'ETH1DepositIndex' (static)
	if val, err := dec.DecodeUint64(); err != nil {
		return sszutils.ErrorWithPath(err, "ETH1DepositIndex")
	} else {
		t.ETH1DepositIndex = val
	}
	// Field #11 'Validators' (offset)
	offset11, err := dec.DecodeOffset()
	if err != nil {
		return sszutils.ErrorWithPath(err, "Validators")
	}
	if offset11 < offset9 || offset11 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset11, offset9, maxOffset), "Validators")
	}
	// Field #12 'Balances' (offset)
	offset12, err := dec.DecodeOffset()
	if err != nil {
		return sszutils.ErrorWithPath(err, "Balances")
	}
	if offset12 < offset11 || offset12 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset12, offset11, maxOffset), "Balances")
	}
	{ // Field #13 'RANDAOMixes' (static)
		val3 := t.RANDAOMixes
		val3 = sszutils.ExpandSlice(val3, int(expr1))
		startPos3 := dec.GetPosition()
		for idx1 := range int(expr1) {
			if _, err = dec.DecodeBytes(val3[idx1][:32]); err != nil {
				return err
			}
			if dec.GetPosition() != startPos3+int(32*(idx1+1)) {
				return sszutils.ErrorWithPathf(sszutils.ErrStaticElementNotConsumedFn(dec.GetPosition(), startPos3+int(32*(idx1+1))), "RANDAOMixes[%d]", idx1)
			}
		}
		t.RANDAOMixes = val3
	}
	{ // Field #14 'Slashings' (static)
		val4 := t.Slashings
		val4 = sszutils.ExpandSlice(val4, int(expr2))
		if err = sszutils.DecodeUint64Slice(dec, val4[:int(expr2)]); err != nil {
			return sszutils.ErrorWithPath(err, "Slashings")
		}
		t.Slashings = val4
	}
	// Field #15 'PreviousEpochParticipation' (offset)
	offset15, err := dec.DecodeOffset()
	if err != nil {
		return sszutils.ErrorWithPath(err, "PreviousEpochParticipation")
	}
	if offset15 < offset12 || offset15 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset15, offset12, maxOffset), "PreviousEpochParticipation")
	}
	// Field #16 'CurrentEpochParticipation' (offset)
	offset16, err := dec.DecodeOffset()
	if err != nil {
		return sszutils.ErrorWithPath(err, "CurrentEpochParticipation")
	}
	if offset16 < offset15 || offset16 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset16, offset15, maxOffset), "CurrentEpochParticipation")
	}
	// Field #17 'JustificationBits' (static)
	t.JustificationBits = sszutils.ExpandSlice(t.JustificationBits, 1)
	if _, err = dec.DecodeBytes(t.JustificationBits[:1]); err != nil {
		return err
	}
	// Field #18 'PreviousJustifiedCheckpoint' (static)
	if t.PreviousJustifiedCheckpoint == nil {
		t.PreviousJustifiedCheckpoint = new(phase0.Checkpoint)
	}
	if buf, err := dec.DecodeBytesBuf(40); err != nil {
		return sszutils.ErrorWithPath(err, "PreviousJustifiedCheckpoint")
	} else if err = t.PreviousJustifiedCheckpoint.UnmarshalSSZ(buf); err != nil {
		return sszutils.ErrorWithPath(err, "PreviousJustifiedCheckpoint")
	}
	// Field #19 'CurrentJustifiedCheckpoint' (static)
	if t.CurrentJustifiedCheckpoint == nil {
		t.CurrentJustifiedCheckpoint = new(phase0.Checkpoint)
	}
	if buf, err := dec.DecodeBytesBuf(40); err != nil {
		return sszutils.ErrorWithPath(err, "CurrentJustifiedCheckpoint")
	} else if err = t.CurrentJustifiedCheckpoint.UnmarshalSSZ(buf); err != nil {
		return sszutils.ErrorWithPath(err, "CurrentJustifiedCheckpoint")
	}
	// Field #20 'FinalizedCheckpoint' (static)
	if t.FinalizedCheckpoint == nil {
		t.FinalizedCheckpoint = new(phase0.Checkpoint)
	}
	if buf, err := dec.DecodeBytesBuf(40); err != nil {
		return sszutils.ErrorWithPath(err, "FinalizedCheckpoint")
	} else if err = t.FinalizedCheckpoint.UnmarshalSSZ(buf); err != nil {
		return sszutils.ErrorWithPath(err, "FinalizedCheckpoint")
	}
	// Field #21 'InactivityScores' (offset)
	offset21, err := dec.DecodeOffset()
	if err != nil {
		return sszutils.ErrorWithPath(err, "InactivityScores")
	}
	if offset21 < offset16 || offset21 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset21, offset16, maxOffset), "InactivityScores")
	}
	{ // Field #22 'CurrentSyncCommittee' (static)
		val5 := t.CurrentSyncCommittee
		if val5 == nil {
			val5 = new(altair.SyncCommittee)
		}
		totalSize := size5+48
		maxOffset := uint32(dec.GetLength())
		if maxOffset < uint32(totalSize) {
			return sszutils.ErrorWithPath(sszutils.ErrFixedFieldsEOFFn(maxOffset, uint32(totalSize)), "CurrentSyncCommittee")
		}
		{ // Field #0 'Pubkeys' (static)
			val6 := val5.Pubkeys
			val6 = sszutils.ExpandSlice(val6, int(expr3))
			startPos4 := dec.GetPosition()
			for idx1 := range int(expr3) {
				if _, err = dec.DecodeBytes(val6[idx1][:48]); err != nil {
					return err
				}
				if dec.GetPosition() != startPos4+int(48*(idx1+1)) {
					return sszutils.ErrorWithPathf(sszutils.ErrStaticElementNotConsumedFn(dec.GetPosition(), startPos4+int(48*(idx1+1))), "CurrentSyncCommittee.Pubkeys[%d]", idx1)
				}
			}
			val5.Pubkeys = val6
		}
		// Field #1 'AggregatePubkey' (static)
		if _, err = dec.DecodeBytes(val5.AggregatePubkey[:48]); err != nil {
			return err
		}
		t.CurrentSyncCommittee = val5
	}
	{ // Field #23 'NextSyncCommittee' (static)
		val7 := t.NextSyncCommittee
		if val7 == nil {
			val7 = new(altair.SyncCommittee)
		}
		totalSize := size5+48
		maxOffset := uint32(dec.GetLength())
		if maxOffset < uint32(totalSize) {
			return sszutils.ErrorWithPath(sszutils.ErrFixedFieldsEOFFn(maxOffset, uint32(totalSize)), "NextSyncCommittee")
		}
		{ // Field #0 'Pubkeys' (static)
			val8 := val7.Pubkeys
			val8 = sszutils.ExpandSlice(val8, int(expr3))
			startPos5 := dec.GetPosition()
			for idx1 := range int(expr3) {
				if _, err = dec.DecodeBytes(val8[idx1][:48]); err != nil {
					return err
				}
				if dec.GetPosition() != startPos5+int(48*(idx1+1)) {
					return sszutils.ErrorWithPathf(sszutils.ErrStaticElementNotConsumedFn(dec.GetPosition(), startPos5+int(48*(idx1+1))), "NextSyncCommittee.Pubkeys[%d]", idx1)
				}
			}
			val7.Pubkeys = val8
		}
		// Field #1 'AggregatePubkey' (static)
		if _, err = dec.DecodeBytes(val7.AggregatePubkey[:48]); err != nil {
			return err
		}
		t.NextSyncCommittee = val7
	}
	// Field #24 'LatestExecutionPayloadHeader' (offset)
	offset24, err := dec.DecodeOffset()
	if err != nil {
		return sszutils.ErrorWithPath(err, "LatestExecutionPayloadHeader")
	}
	if offset24 < offset21 || offset24 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset24, offset21, maxOffset), "LatestExecutionPayloadHeader")
	}
	// Field #25 'NextWithdrawalIndex' (static)
	if val, err := dec.DecodeUint64(); err != nil {
		return sszutils.ErrorWithPath(err, "NextWithdrawalIndex")
	} else {
		t.NextWithdrawalIndex = capella.WithdrawalIndex(val)
	}
	// Field #26 'NextWithdrawalValidatorIndex' (static)
	if val, err := dec.DecodeUint64(); err != nil {
		return sszutils.ErrorWithPath(err, "NextWithdrawalValidatorIndex")
	} else {
		t.NextWithdrawalValidatorIndex = phase0.ValidatorIndex(val)
	}
	// Field #27 'HistoricalSummaries' (offset)
	offset27, err := dec.DecodeOffset()
	if err != nil {
		return sszutils.ErrorWithPath(err, "HistoricalSummaries")
	}
	if offset27 < offset24 || offset27 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset27, offset24, maxOffset), "HistoricalSummaries")
	}
	// Field #28 'DepositRequestsStartIndex' (static)
	if val, err := dec.DecodeUint64(); err != nil {
		return sszutils.ErrorWithPath(err, "DepositRequestsStartIndex")
	} else {
		t.DepositRequestsStartIndex = val
	}
	// Field #29 'DepositBalanceToConsume' (static)
	if val, err := dec.DecodeUint64(); err != nil {
		return sszutils.ErrorWithPath(err, "DepositBalanceToConsume")
	} else {
		t.DepositBalanceToConsume = phase0.Gwei(val)
	}
	// Field #30 'ExitBalanceToConsume' (static)
	if val, err := dec.DecodeUint64(); err != nil {
		return sszutils.ErrorWithPath(err, "ExitBalanceToConsume")
	} else {
		t.ExitBalanceToConsume = phase0.Gwei(val)
	}
	// Field #31 'EarliestExitEpoch' (static)
	if val, err := dec.DecodeUint64(); err != nil {
		return sszutils.ErrorWithPath(err, "EarliestExitEpoch")
	} else {
		t.EarliestExitEpoch = phase0.Epoch(val)
	}
	// Field #32 'ConsolidationBalanceToConsume' (static)
	if val, err := dec.DecodeUint64(); err != nil {
		return sszutils.ErrorWithPath(err, "ConsolidationBalanceToConsume")
	} else {
		t.ConsolidationBalanceToConsume = phase0.Gwei(val)
	}
	// Field #33 'EarliestConsolidationEpoch' (static)
	if val, err := dec.DecodeUint64(); err != nil {
		return sszutils.ErrorWithPath(err, "EarliestConsolidationEpoch")
	} else {
		t.EarliestConsolidationEpoch = phase0.Epoch(val)
	}
	// Field #34 'PendingDeposits' (offset)
	offset34, err := dec.DecodeOffset()
	if err != nil {
		return sszutils.ErrorWithPath(err, "PendingDeposits")
	}
	if offset34 < offset27 || offset34 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset34, offset27, maxOffset), "PendingDeposits")
	}
	// Field #35 'PendingPartialWithdrawals' (offset)
	offset35, err := dec.DecodeOffset()
	if err != nil {
		return sszutils.ErrorWithPath(err, "PendingPartialWithdrawals")
	}
	if offset35 < offset34 || offset35 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset35, offset34, maxOffset), "PendingPartialWithdrawals")
	}
	// Field #36 'PendingConsolidations' (offset)
	offset36, err := dec.DecodeOffset()
	if err != nil {
		return sszutils.ErrorWithPath(err, "PendingConsolidations")
	}
	if offset36 < offset35 || offset36 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset36, offset35, maxOffset), "PendingConsolidations")
	}
	{ // Field #37 'ProposerLookahead' (static)
		val9 := t.ProposerLookahead
		val9 = sszutils.ExpandSlice(val9, int(expr4))
		if err = sszutils.DecodeUint64Slice(dec, val9[:int(expr4)]); err != nil {
			return sszutils.ErrorWithPath(err, "ProposerLookahead")
		}
		t.ProposerLookahead = val9
	}
	{ // Field #7 'HistoricalRoots' (dynamic)
		if dec.GetPosition() != startPos0+int(offset7) {
			return sszutils.ErrorWithPath(sszutils.ErrFieldNotConsumedFn(dec.GetPosition(), startPos0+int(offset7)), "HistoricalRoots")
		}
		dec.PushLimit(int(offset9 - offset7))
		val10 := t.HistoricalRoots
		sszLen := dec.GetLength()
		itemCount := sszLen / 32
		if sszLen%32 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(sszLen, 32), "HistoricalRoots")
		}
		if itemCount > int(expr5) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr5)), "HistoricalRoots")
		}
		val10 = sszutils.ExpandSlice(val10, itemCount)
		startPos6 := dec.GetPosition()
		for idx1 := range itemCount {
			if _, err = dec.DecodeBytes(val10[idx1][:32]); err != nil {
				return err
			}
			if dec.GetPosition() != startPos6+int(32*(idx1+1)) {
				return sszutils.ErrorWithPathf(sszutils.ErrStaticElementNotConsumedFn(dec.GetPosition(), startPos6+int(32*(idx1+1))), "HistoricalRoots[%d]", idx1)
			}
		}
		if diff := dec.PopLimit(); diff != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrTrailingDataFn(diff), "HistoricalRoots")
		}
		t.HistoricalRoots = val10
	}
	{ // Field #9 'ETH1DataVotes' (dynamic)
		if dec.GetPosition() != startPos0+int(offset9) {
			return sszutils.ErrorWithPath(sszutils.ErrFieldNotConsumedFn(dec.GetPosition(), startPos0+int(offset9)), "ETH1DataVotes")
		}
		dec.PushLimit(int(offset11 - offset9))
		val11 := t.ETH1DataVotes
		sszLen := dec.GetLength()
		itemCount := sszLen / 72
		if sszLen%72 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(sszLen, 72), "ETH1DataVotes")
		}
		if itemCount > int(expr6) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr6)), "ETH1DataVotes")
		}
		val11 = sszutils.ExpandSlice(val11, itemCount)
		startPos7 := dec.GetPosition()
		for idx1 := range itemCount {
			if val11[idx1] == nil {
				val11[idx1] = new(phase0.ETH1Data)
			}
			if buf, err := dec.DecodeBytesBuf(72); err != nil {
				return sszutils.ErrorWithPathf(err, "ETH1DataVotes[%d]", idx1)
			} else if err = val11[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "ETH1DataVotes[%d]", idx1)
			}
			if dec.GetPosition() != startPos7+int(72*(idx1+1)) {
				return sszutils.ErrorWithPathf(sszutils.ErrStaticElementNotConsumedFn(dec.GetPosition(), startPos7+int(72*(idx1+1))), "ETH1DataVotes[%d]", idx1)
			}
		}
		if diff := dec.PopLimit(); diff != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrTrailingDataFn(diff), "ETH1DataVotes")
		}
		t.ETH1DataVotes = val11
	}
	{ // Field #11 'Validators' (dynamic)
		if dec.GetPosition() != startPos0+int(offset11) {
			return sszutils.ErrorWithPath(sszutils.ErrFieldNotConsumedFn(dec.GetPosition(), startPos0+int(offset11)), "Validators")
		}
		dec.PushLimit(int(offset12 - offset11))
		val12 := t.Validators
		sszLen := dec.GetLength()
		itemCount := sszLen / 121
		if sszLen%121 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(sszLen, 121), "Validators")
		}
		if itemCount > int(expr7) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr7)), "Validators")
		}
		val12 = sszutils.ExpandSlice(val12, itemCount)
		startPos8 := dec.GetPosition()
		for idx1 := range itemCount {
			if val12[idx1] == nil {
				val12[idx1] = new(phase0.Validator)
			}
			if buf, err := dec.DecodeBytesBuf(121); err != nil {
				return sszutils.ErrorWithPathf(err, "Validators[%d]", idx1)
			} else if err = val12[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Validators[%d]", idx1)
			}
			if dec.GetPosition() != startPos8+int(121*(idx1+1)) {
				return sszutils.ErrorWithPathf(sszutils.ErrStaticElementNotConsumedFn(dec.GetPosition(), startPos8+int(121*(idx1+1))), "Validators[%d]", idx1)
			}
		}
		if diff := dec.PopLimit(); diff != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrTrailingDataFn(diff), "Validators")
		}
		t.Validators = val12
	}
	{ // Field #12 'Balances' (dynamic)
		if dec.GetPosition() != startPos0+int(offset12) {
			return sszutils.ErrorWithPath(sszutils.ErrFieldNotConsumedFn(dec.GetPosition(), startPos0+int(offset12)), "Balances")
		}
		dec.PushLimit(int(offset15 - offset12))
		val13 := t.Balances
		sszLen := dec.GetLength()
		itemCount := sszLen / 8
		if sszLen%8 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(sszLen, 8), "Balances")
		}
		if itemCount > int(expr7) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr7)), "Balances")
		}
		val13 = sszutils.ExpandSlice(val13, itemCount)
		if err = sszutils.DecodeUint64Slice(dec, val13); err != nil {
			return sszutils.ErrorWithPath(err, "Balances")
		}
		if diff := dec.PopLimit(); diff != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrTrailingDataFn(diff), "Balances")
		}
		t.Balances = val13
	}
	{ // Field #15 'PreviousEpochParticipation' (dynamic)
		if dec.GetPosition() != startPos0+int(offset15) {
			return sszutils.ErrorWithPath(sszutils.ErrFieldNotConsumedFn(dec.GetPosition(), startPos0+int(offset15)), "PreviousEpochParticipation")
		}
		dec.PushLimit(int(offset16 - offset15))
		val14 := t.PreviousEpochParticipation
		itemCount := dec.GetLength()
		if itemCount > int(expr7) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr7)), "PreviousEpochParticipation")
		}
		val14 = sszutils.ExpandSlice(val14, itemCount)
		startPos9 := dec.GetPosition()
		for idx1 := range itemCount {
			if val, err := dec.DecodeUint8(); err != nil {
				return sszutils.ErrorWithPathf(err, "PreviousEpochParticipation[%d]", idx1)
			} else {
				val14[idx1] = altair.ParticipationFlags(val)
			}
			if dec.GetPosition() != startPos9+int(1*(idx1+1)) {
				return sszutils.ErrorWithPathf(sszutils.ErrStaticElementNotConsumedFn(dec.GetPosition(), startPos9+int(1*(idx1+1))), "PreviousEpochParticipation[%d]", idx1)
			}
		}
		if diff := dec.PopLimit(); diff != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrTrailingDataFn(diff), "PreviousEpochParticipation")
		}
		t.PreviousEpochParticipation = val14
	}
	{ // Field #16 'CurrentEpochParticipation' (dynamic)
		if dec.GetPosition() != startPos0+int(offset16) {
			return sszutils.ErrorWithPath(sszutils.ErrFieldNotConsumedFn(dec.GetPosition(), startPos0+int(offset16)), "CurrentEpochParticipation")
		}
		dec.PushLimit(int(offset21 - offset16))
		val15 := t.CurrentEpochParticipation
		itemCount := dec.GetLength()
		if itemCount > int(expr7) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr7)), "CurrentEpochParticipation")
		}
		val15 = sszutils.ExpandSlice(val15, itemCount)
		startPos10 := dec.GetPosition()
		for idx1 := range itemCount {
			if val, err := dec.DecodeUint8(); err != nil {
				return sszutils.ErrorWithPathf(err, "CurrentEpochParticipation[%d]", idx1)
			} else {
				val15[idx1] = altair.ParticipationFlags(val)
			}
			if dec.GetPosition() != startPos10+int(1*(idx1+1)) {
				return sszutils.ErrorWithPathf(sszutils.ErrStaticElementNotConsumedFn(dec.GetPosition(), startPos10+int(1*(idx1+1))), "CurrentEpochParticipation[%d]", idx1)
			}
		}
		if diff := dec.PopLimit(); diff != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrTrailingDataFn(diff), "CurrentEpochParticipation")
		}
		t.CurrentEpochParticipation = val15
	}
	{ // Field #21 'InactivityScores' (dynamic)
		if dec.GetPosition() != startPos0+int(offset21) {
			return sszutils.ErrorWithPath(sszutils.ErrFieldNotConsumedFn(dec.GetPosition(), startPos0+int(offset21)), "InactivityScores")
		}
		dec.PushLimit(int(offset24 - offset21))
		val16 := t.InactivityScores
		sszLen := dec.GetLength()
		itemCount := sszLen / 8
		if sszLen%8 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(sszLen, 8), "InactivityScores")
		}
		if itemCount > int(expr7) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr7)), "InactivityScores")
		}
		val16 = sszutils.ExpandSlice(val16, itemCount)
		if err = sszutils.DecodeUint64Slice(dec, val16); err != nil {
			return sszutils.ErrorWithPath(err, "InactivityScores")
		}
		if diff := dec.PopLimit(); diff != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrTrailingDataFn(diff), "InactivityScores")
		}
		t.InactivityScores = val16
	}
	{ // Field #24 'LatestExecutionPayloadHeader' (dynamic)
		if dec.GetPosition() != startPos0+int(offset24) {
			return sszutils.ErrorWithPath(sszutils.ErrFieldNotConsumedFn(dec.GetPosition(), startPos0+int(offset24)), "LatestExecutionPayloadHeader")
		}
		dec.PushLimit(int(offset27 - offset24))
		val17 := t.LatestExecutionPayloadHeader
		if val17 == nil {
			val17 = new(deneb.ExecutionPayloadHeader)
		}
		if buf, err := dec.DecodeBytesBuf(dec.GetLength()); err != nil {
			return sszutils.ErrorWithPath(err, "LatestExecutionPayloadHeader")
		} else if err = val17.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "LatestExecutionPayloadHeader")
		}
		if diff := dec.PopLimit(); diff != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrTrailingDataFn(diff), "LatestExecutionPayloadHeader")
		}
		t.LatestExecutionPayloadHeader = val17
	}
	{ // Field #27 'HistoricalSummaries' (dynamic)
		if dec.GetPosition() != startPos0+int(offset27) {
			return sszutils.ErrorWithPath(sszutils.ErrFieldNotConsumedFn(dec.GetPosition(), startPos0+int(offset27)), "HistoricalSummaries")
		}
		dec.PushLimit(int(offset34 - offset27))
		val18 := t.HistoricalSummaries
		sszLen := dec.GetLength()
		itemCount := sszLen / 64
		if sszLen%64 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(sszLen, 64), "HistoricalSummaries")
		}
		if itemCount > int(expr5) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr5)), "HistoricalSummaries")
		}
		val18 = sszutils.ExpandSlice(val18, itemCount)
		startPos11 := dec.GetPosition()
		for idx1 := range itemCount {
			if val18[idx1] == nil {
				val18[idx1] = new(capella.HistoricalSummary)
			}
			if buf, err := dec.DecodeBytesBuf(64); err != nil {
				return sszutils.ErrorWithPathf(err, "HistoricalSummaries[%d]", idx1)
			} else if err = val18[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "HistoricalSummaries[%d]", idx1)
			}
			if dec.GetPosition() != startPos11+int(64*(idx1+1)) {
				return sszutils.ErrorWithPathf(sszutils.ErrStaticElementNotConsumedFn(dec.GetPosition(), startPos11+int(64*(idx1+1))), "HistoricalSummaries[%d]", idx1)
			}
		}
		if diff := dec.PopLimit(); diff != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrTrailingDataFn(diff), "HistoricalSummaries")
		}
		t.HistoricalSummaries = val18
	}
	{ // Field #34 'PendingDeposits' (dynamic)
		if dec.GetPosition() != startPos0+int(offset34) {
			return sszutils.ErrorWithPath(sszutils.ErrFieldNotConsumedFn(dec.GetPosition(), startPos0+int(offset34)), "PendingDeposits")
		}
		dec.PushLimit(int(offset35 - offset34))
		val19 := t.PendingDeposits
		sszLen := dec.GetLength()
		itemCount := sszLen / 192
		if sszLen%192 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(sszLen, 192), "PendingDeposits")
		}
		if itemCount > int(expr8) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr8)), "PendingDeposits")
		}
		val19 = sszutils.ExpandSlice(val19, itemCount)
		startPos12 := dec.GetPosition()
		for idx1 := range itemCount {
			if val19[idx1] == nil {
				val19[idx1] = new(electra.PendingDeposit)
			}
			if buf, err := dec.DecodeBytesBuf(192); err != nil {
				return sszutils.ErrorWithPathf(err, "PendingDeposits[%d]", idx1)
			} else if err = val19[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "PendingDeposits[%d]", idx1)
			}
			if dec.GetPosition() != startPos12+int(192*(idx1+1)) {
				return sszutils.ErrorWithPathf(sszutils.ErrStaticElementNotConsumedFn(dec.GetPosition(), startPos12+int(192*(idx1+1))), "PendingDeposits[%d]", idx1)
			}
		}
		if diff := dec.PopLimit(); diff != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrTrailingDataFn(diff), "PendingDeposits")
		}
		t.PendingDeposits = val19
	}
	{ // Field #35 'PendingPartialWithdrawals' (dynamic)
		if dec.GetPosition() != startPos0+int(offset35) {
			return sszutils.ErrorWithPath(sszutils.ErrFieldNotConsumedFn(dec.GetPosition(), startPos0+int(offset35)), "PendingPartialWithdrawals")
		}
		dec.PushLimit(int(offset36 - offset35))
		val20 := t.PendingPartialWithdrawals
		sszLen := dec.GetLength()
		itemCount := sszLen / 24
		if sszLen%24 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(sszLen, 24), "PendingPartialWithdrawals")
		}
		if itemCount > int(expr9) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr9)), "PendingPartialWithdrawals")
		}
		val20 = sszutils.ExpandSlice(val20, itemCount)
		startPos13 := dec.GetPosition()
		for idx1 := range itemCount {
			if val20[idx1] == nil {
				val20[idx1] = new(electra.PendingPartialWithdrawal)
			}
			if buf, err := dec.DecodeBytesBuf(24); err != nil {
				return sszutils.ErrorWithPathf(err, "PendingPartialWithdrawals[%d]", idx1)
			} else if err = val20[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "PendingPartialWithdrawals[%d]", idx1)
			}
			if dec.GetPosition() != startPos13+int(24*(idx1+1)) {
				return sszutils.ErrorWithPathf(sszutils.ErrStaticElementNotConsumedFn(dec.GetPosition(), startPos13+int(24*(idx1+1))), "PendingPartialWithdrawals[%d]", idx1)
			}
		}
		if diff := dec.PopLimit(); diff != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrTrailingDataFn(diff), "PendingPartialWithdrawals")
		}
		t.PendingPartialWithdrawals = val20
	}
	{ // Field #36 'PendingConsolidations' (dynamic)
		if dec.GetPosition() != startPos0+int(offset36) {
			return sszutils.ErrorWithPath(sszutils.ErrFieldNotConsumedFn(dec.GetPosition(), startPos0+int(offset36)), "PendingConsolidations")
		}
		dec.PushLimit(int(maxOffset - offset36))
		val21 := t.PendingConsolidations
		sszLen := dec.GetLength()
		itemCount := sszLen / 16
		if sszLen%16 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(sszLen, 16), "PendingConsolidations")
		}
		if itemCount > int(expr10) {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, int(expr10)), "PendingConsolidations")
		}
		val21 = sszutils.ExpandSlice(val21, itemCount)
		startPos14 := dec.GetPosition()
		for idx1 := range itemCount {
			if val21[idx1] == nil {
				val21[idx1] = new(electra.PendingConsolidation)
			}
			if buf, err := dec.DecodeBytesBuf(16); err != nil {
				return sszutils.ErrorWithPathf(err, "PendingConsolidations[%d]", idx1)
			} else if err = val21[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "PendingConsolidations[%d]", idx1)
			}
			if dec.GetPosition() != startPos14+int(16*(idx1+1)) {
				return sszutils.ErrorWithPathf(sszutils.ErrStaticElementNotConsumedFn(dec.GetPosition(), startPos14+int(16*(idx1+1))), "PendingConsolidations[%d]", idx1)
			}
		}
		if diff := dec.PopLimit(); diff != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrTrailingDataFn(diff), "PendingConsolidations")
		}
		t.PendingConsolidations = val21
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *BeaconState.
func (t *BeaconState) SizeSSZ() (size int) {
	if t == nil {
		t = new(BeaconState)
	}
	// Field #0 'GenesisTime' static (8 bytes)
	// Field #1 'GenesisValidatorsRoot' static (32 bytes)
	// Field #2 'Slot' static (8 bytes)
	// Field #3 'Fork' static (16 bytes)
	// Field #4 'LatestBlockHeader' static (112 bytes)
	// Field #5 'BlockRoots' static (262144 bytes)
	// Field #6 'StateRoots' static (262144 bytes)
	// Field #7 'HistoricalRoots' offset (4 bytes)
	// Field #8 'ETH1Data' static (72 bytes)
	// Field #9 'ETH1DataVotes' offset (4 bytes)
	// Field #10 'ETH1DepositIndex' static (8 bytes)
	// Field #11 'Validators' offset (4 bytes)
	// Field #12 'Balances' offset (4 bytes)
	// Field #13 'RANDAOMixes' static (2097152 bytes)
	// Field #14 'Slashings' static (65536 bytes)
	// Field #15 'PreviousEpochParticipation' offset (4 bytes)
	// Field #16 'CurrentEpochParticipation' offset (4 bytes)
	// Field #17 'JustificationBits' static (1 bytes)
	// Field #18 'PreviousJustifiedCheckpoint' static (40 bytes)
	// Field #19 'CurrentJustifiedCheckpoint' static (40 bytes)
	// Field #20 'FinalizedCheckpoint' static (40 bytes)
	// Field #21 'InactivityScores' offset (4 bytes)
	// Field #22 'CurrentSyncCommittee' static (24624 bytes)
	// Field #23 'NextSyncCommittee' static (24624 bytes)
	// Field #24 'LatestExecutionPayloadHeader' offset (4 bytes)
	// Field #25 'NextWithdrawalIndex' static (8 bytes)
	// Field #26 'NextWithdrawalValidatorIndex' static (8 bytes)
	// Field #27 'HistoricalSummaries' offset (4 bytes)
	// Field #28 'DepositRequestsStartIndex' static (8 bytes)
	// Field #29 'DepositBalanceToConsume' static (8 bytes)
	// Field #30 'ExitBalanceToConsume' static (8 bytes)
	// Field #31 'EarliestExitEpoch' static (8 bytes)
	// Field #32 'ConsolidationBalanceToConsume' static (8 bytes)
	// Field #33 'EarliestConsolidationEpoch' static (8 bytes)
	// Field #34 'PendingDeposits' offset (4 bytes)
	// Field #35 'PendingPartialWithdrawals' offset (4 bytes)
	// Field #36 'PendingConsolidations' offset (4 bytes)
	// Field #37 'ProposerLookahead' static (512 bytes)
	size += 2737225
	{ // Dynamic field #7 'HistoricalRoots'
		size += len(t.HistoricalRoots) * 32
	}
	{ // Dynamic field #9 'ETH1DataVotes'
		size += len(t.ETH1DataVotes) * 72
	}
	{ // Dynamic field #11 'Validators'
		size += len(t.Validators) * 121
	}
	{ // Dynamic field #12 'Balances'
		size += len(t.Balances) * 8
	}
	{ // Dynamic field #15 'PreviousEpochParticipation'
		size += len(t.PreviousEpochParticipation)
	}
	{ // Dynamic field #16 'CurrentEpochParticipation'
		size += len(t.CurrentEpochParticipation)
	}
	{ // Dynamic field #21 'InactivityScores'
		size += len(t.InactivityScores) * 8
	}
	{ // Dynamic field #24 'LatestExecutionPayloadHeader'
		size += t.LatestExecutionPayloadHeader.SizeSSZ()
	}
	{ // Dynamic field #27 'HistoricalSummaries'
		size += len(t.HistoricalSummaries) * 64
	}
	{ // Dynamic field #34 'PendingDeposits'
		size += len(t.PendingDeposits) * 192
	}
	{ // Dynamic field #35 'PendingPartialWithdrawals'
		size += len(t.PendingPartialWithdrawals) * 24
	}
	{ // Dynamic field #36 'PendingConsolidations'
		size += len(t.PendingConsolidations) * 16
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *BeaconState.
func (t *BeaconState) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *BeaconState using the given hash walker.
func (t *BeaconState) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BeaconState)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'GenesisTime'
		hh.PutUint64(t.GenesisTime)
	}
	{ // Field #1 'GenesisValidatorsRoot'
		hh.PutBytes(t.GenesisValidatorsRoot[:32])
	}
	{ // Field #2 'Slot'
		hh.PutUint64(uint64(t.Slot))
	}
	{ // Field #3 'Fork'
		t := t.Fork
		if t == nil {
			t = new(phase0.Fork)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Fork")
		}
	}
	{ // Field #4 'LatestBlockHeader'
		t := t.LatestBlockHeader
		if t == nil {
			t = new(phase0.BeaconBlockHeader)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "LatestBlockHeader")
		}
	}
	{ // Field #5 'BlockRoots'
		t := t.BlockRoots
		vlen := len(t)
		if vlen > 8192 {
			return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 8192), "BlockRoots")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		var val1 *phase0.Root
		for idx1 := range 8192 {
			if idx1 < vlen {
				val1 = &t[idx1]
			} else if idx1 == vlen {
				val1 = new(phase0.Root)
			}
			hh.PutBytes(val1[:32])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.Merkleize(idx)
	}
	{ // Field #6 'StateRoots'
		t := t.StateRoots
		vlen := len(t)
		if vlen > 8192 {
			return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 8192), "StateRoots")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		var val2 *phase0.Root
		for idx1 := range 8192 {
			if idx1 < vlen {
				val2 = &t[idx1]
			} else if idx1 == vlen {
				val2 = new(phase0.Root)
			}
			hh.PutBytes(val2[:32])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.Merkleize(idx)
	}
	{ // Field #7 'HistoricalRoots'
		t := t.HistoricalRoots
		vlen := uint64(len(t))
		if vlen > 16777216 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 16777216), "HistoricalRoots")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.PutBytes(t[idx1][:32])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(16777216, vlen, 32))
	}
	{ // Field #8 'ETH1Data'
		t := t.ETH1Data
		if t == nil {
			t = new(phase0.ETH1Data)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "ETH1Data")
		}
	}
	{ // Field #9 'ETH1DataVotes'
		t := t.ETH1DataVotes
		vlen := uint64(len(t))
		if vlen > 2048 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 2048), "ETH1DataVotes")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			if t == nil {
				t = new(phase0.ETH1Data)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "ETH1DataVotes[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(2048, vlen, 32))
	}
	{ // Field #10 'ETH1DepositIndex'
		hh.PutUint64(t.ETH1DepositIndex)
	}
	{ // Field #11 'Validators'
		t := t.Validators
		vlen := uint64(len(t))
		if vlen > 1099511627776 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1099511627776), "Validators")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			if t == nil {
				t = new(phase0.Validator)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Validators[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(1099511627776, vlen, 32))
	}
	{ // Field #12 'Balances'
		t := t.Balances
		vlen := uint64(len(t))
		if vlen > 1099511627776 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1099511627776), "Balances")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		sszutils.HashUint64Slice(hh, t)
		hh.FillUpTo32()
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(1099511627776, vlen, 8))
	}
	{ // Field #13 'RANDAOMixes'
		t := t.RANDAOMixes
		vlen := len(t)
		if vlen > 65536 {
			return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 65536), "RANDAOMixes")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		var val3 *phase0.Root
		for idx1 := range 65536 {
			if idx1 < vlen {
				val3 = &t[idx1]
			} else if idx1 == vlen {
				val3 = new(phase0.Root)
			}
			hh.PutBytes(val3[:32])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.Merkleize(idx)
	}
	{ // Field #14 'Slashings'
		t := t.Slashings
		vlen := len(t)
		if vlen > 8192 {
			return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 8192), "Slashings")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		var val4, val4Empty phase0.Gwei
		for idx1 := range 8192 {
			if idx1 < vlen {
				val4 = t[idx1]
			} else if idx1 == vlen {
				val4 = val4Empty
			}
			hh.AppendUint64(uint64(val4))
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.FillUpTo32()
		hh.Merkleize(idx)
	}
	{ // Field #15 'PreviousEpochParticipation'
		t := t.PreviousEpochParticipation
		vlen := uint64(len(t))
		if vlen > 1099511627776 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1099511627776), "PreviousEpochParticipation")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.AppendUint8(uint8(t[idx1]))
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.FillUpTo32()
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(1099511627776, vlen, 1))
	}
	{ // Field #16 'CurrentEpochParticipation'
		t := t.CurrentEpochParticipation
		vlen := uint64(len(t))
		if vlen > 1099511627776 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1099511627776), "CurrentEpochParticipation")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			hh.AppendUint8(uint8(t[idx1]))
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.FillUpTo32()
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(1099511627776, vlen, 1))
	}
	{ // Field #17 'JustificationBits'
		vlen := len(t.JustificationBits)
		if vlen > 1 {
			return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 1), "JustificationBits")
		}
		val := t.JustificationBits[:]
		if vlen < 1 {
			val = sszutils.AppendZeroPadding(val, (1-vlen)*1)
		}
		hh.PutBytes(val[:1])
	}
	{ // Field #18 'PreviousJustifiedCheckpoint'
		t := t.PreviousJustifiedCheckpoint
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "PreviousJustifiedCheckpoint")
		}
	}
	{ // Field #19 'CurrentJustifiedCheckpoint'
		t := t.CurrentJustifiedCheckpoint
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "CurrentJustifiedCheckpoint")
		}
	}
	{ // Field #20 'FinalizedCheckpoint'
		t := t.FinalizedCheckpoint
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "FinalizedCheckpoint")
		}
	}
	{ // Field #21 'InactivityScores'
		t := t.InactivityScores
		vlen := uint64(len(t))
		if vlen > 1099511627776 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 1099511627776), "InactivityScores")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		sszutils.HashUint64Slice(hh, t)
		hh.FillUpTo32()
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(1099511627776, vlen, 8))
	}
	{ // Field #22 'CurrentSyncCommittee'
		t := t.CurrentSyncCommittee
		if t == nil {
			t = new(altair.SyncCommittee)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "CurrentSyncCommittee")
		}
	}
	{ // Field #23 'NextSyncCommittee'
		t := t.NextSyncCommittee
		if t == nil {
			t = new(altair.SyncCommittee)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "NextSyncCommittee")
		}
	}
	{ // Field #24 'LatestExecutionPayloadHeader'
		t := t.LatestExecutionPayloadHeader
		if t == nil {
			t = new(deneb.ExecutionPayloadHeader)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "LatestExecutionPayloadHeader")
		}
	}
	{ // Field #25 'NextWithdrawalIndex'
		hh.PutUint64(uint64(t.NextWithdrawalIndex))
	}
	{ // Field #26 'NextWithdrawalValidatorIndex'
		hh.PutUint64(uint64(t.NextWithdrawalValidatorIndex))
	}
	{ // Field #27 'HistoricalSummaries'
		t := t.HistoricalSummaries
		vlen := uint64(len(t))
		if vlen > 16777216 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 16777216), "HistoricalSummaries")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			if t == nil {
				t = new(capella.HistoricalSummary)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "HistoricalSummaries[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(16777216, vlen, 32))
	}
	{ // Field #28 'DepositRequestsStartIndex'
		hh.PutUint64(t.DepositRequestsStartIndex)
	}
	{ // Field #29 'DepositBalanceToConsume'
		hh.PutUint64(uint64(t.DepositBalanceToConsume))
	}
	{ // Field #30 'ExitBalanceToConsume'
		hh.PutUint64(uint64(t.ExitBalanceToConsume))
	}
	{ // Field #31 'EarliestExitEpoch'
		hh.PutUint64(uint64(t.EarliestExitEpoch))
	}
	{ // Field #32 'ConsolidationBalanceToConsume'
		hh.PutUint64(uint64(t.ConsolidationBalanceToConsume))
	}
	{ // Field #33 'EarliestConsolidationEpoch'
		hh.PutUint64(uint64(t.EarliestConsolidationEpoch))
	}
	{ // Field #34 'PendingDeposits'
		t := t.PendingDeposits
		vlen := uint64(len(t))
		if vlen > 134217728 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 134217728), "PendingDeposits")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			if t == nil {
				t = new(electra.PendingDeposit)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "PendingDeposits[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(134217728, vlen, 32))
	}
	{ // Field #35 'PendingPartialWithdrawals'
		t := t.PendingPartialWithdrawals
		vlen := uint64(len(t))
		if vlen > 134217728 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 134217728), "PendingPartialWithdrawals")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			if t == nil {
				t = new(electra.PendingPartialWithdrawal)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "PendingPartialWithdrawals[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(134217728, vlen, 32))
	}
	{ // Field #36 'PendingConsolidations'
		t := t.PendingConsolidations
		vlen := uint64(len(t))
		if vlen > 262144 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 262144), "PendingConsolidations")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range int(vlen) {
			t := t[idx1]
			if t == nil {
				t = new(electra.PendingConsolidation)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "PendingConsolidations[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(262144, vlen, 32))
	}
	{ // Field #37 'ProposerLookahead'
		t := t.ProposerLookahead
		vlen := len(t)
		if vlen > 64 {
			return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 64), "ProposerLookahead")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		var val5, val5Empty phase0.ValidatorIndex
		for idx1 := range 64 {
			if idx1 < vlen {
				val5 = t[idx1]
			} else if idx1 == vlen {
				val5 = val5Empty
			}
			hh.AppendUint64(uint64(val5))
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.FillUpTo32()
		hh.Merkleize(idx)
	}
	hh.Merkleize(idx)
	return nil
}
