// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 7e60a0952a9d80cfd45297a2754cb6804bed05eb79353a47b080576033c37e1f
// Version: v1.4.0-pre.3 (https://github.com/pk910/dynamic-ssz)

package heze

import (
	"encoding/binary"
	"math"

	"github.com/ethpandaops/go-eth2-client/spec/altair"
	"github.com/ethpandaops/go-eth2-client/spec/capella"
	"github.com/ethpandaops/go-eth2-client/spec/gloas"
	"github.com/ethpandaops/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[BeaconBlockBody](`ssz-static:"false"`)

// MarshalSSZ marshals the *BeaconBlockBody to SSZ-encoded bytes.
func (t *BeaconBlockBody) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *BeaconBlockBody to SSZ-encoded bytes, appending to the provided buffer.
func (t *BeaconBlockBody) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	zeroBytes := sszutils.ZeroBytes()
	if t == nil {
		t = new(BeaconBlockBody)
	}
	dstlen := len(dst)
	{ // Static Field #0 'RANDAOReveal'
		dst = append(dst, t.RANDAOReveal[:96]...)
	}
	{ // Static Field #1 'Graffiti'
		dst = append(dst, t.Graffiti[:32]...)
	}
	// Offset Field #2 'ProposerSlashings'
	// Offset Field #3 'AttesterSlashings'
	// Offset Field #4 'Attestations'
	// Offset Field #5 'VoluntaryExits'
	dst = append(dst, zeroBytes[:16]...)
	{ // Static Field #6 'SyncAggregate'
		t := t.SyncAggregate
		if t == nil {
			t = new(altair.SyncAggregate)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "SyncAggregate")
		}
	}
	// Offset Field #7 'BLSToExecutionChanges'
	// Offset Field #8 'SignedExecutionPayloadBid'
	// Offset Field #9 'PayloadAttestations'
	// Offset Field #10 'ParentExecutionRequests'
	dst = append(dst, zeroBytes[:16]...)
	{ // Dynamic Field #2 'ProposerSlashings'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+128:], uint32(off))
		}
		t := t.ProposerSlashings
		vlen := len(t)
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(phase0.ProposerSlashing)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "ProposerSlashings[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #3 'AttesterSlashings'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+132:], uint32(off))
		}
		t := t.AttesterSlashings
		dstlen := len(dst)
		vlen := len(t)
		if vlen > sszutils.MaxSszSize/4 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrSszSizeLimitFn("list offset table", uint64(vlen), 4), "AttesterSlashings")
		}
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for idx1 := range vlen {
			if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
				return nil, sszutils.ErrOffsetOverflowFn(off)
			} else {
				binary.LittleEndian.PutUint32(dst[dstlen+(idx1*4):], uint32(off))
			}
			t := t[idx1]
			if t == nil {
				t = new(gloas.AttesterSlashing)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "AttesterSlashings[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #4 'Attestations'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+136:], uint32(off))
		}
		t := t.Attestations
		dstlen := len(dst)
		vlen := len(t)
		if vlen > sszutils.MaxSszSize/4 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrSszSizeLimitFn("list offset table", uint64(vlen), 4), "Attestations")
		}
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for idx1 := range vlen {
			if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
				return nil, sszutils.ErrOffsetOverflowFn(off)
			} else {
				binary.LittleEndian.PutUint32(dst[dstlen+(idx1*4):], uint32(off))
			}
			t := t[idx1]
			if t == nil {
				t = new(gloas.Attestation)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Attestations[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #5 'VoluntaryExits'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+140:], uint32(off))
		}
		t := t.VoluntaryExits
		vlen := len(t)
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(phase0.SignedVoluntaryExit)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "VoluntaryExits[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #7 'BLSToExecutionChanges'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+304:], uint32(off))
		}
		t := t.BLSToExecutionChanges
		vlen := len(t)
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(capella.SignedBLSToExecutionChange)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "BLSToExecutionChanges[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #8 'SignedExecutionPayloadBid'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+308:], uint32(off))
		}
		t := t.SignedExecutionPayloadBid
		if t == nil {
			t = new(SignedExecutionPayloadBid)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "SignedExecutionPayloadBid")
		}
	}
	{ // Dynamic Field #9 'PayloadAttestations'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+312:], uint32(off))
		}
		t := t.PayloadAttestations
		vlen := len(t)
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(gloas.PayloadAttestation)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "PayloadAttestations[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #10 'ParentExecutionRequests'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+316:], uint32(off))
		}
		t := t.ParentExecutionRequests
		if t == nil {
			t = new(gloas.ExecutionRequests)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "ParentExecutionRequests")
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *BeaconBlockBody from SSZ-encoded bytes.
func (t *BeaconBlockBody) UnmarshalSSZ(buf []byte) (err error) {
	buflen := uint64(len(buf))
	if buflen < 320 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 320)
	}
	maxOffset := uint32(sszutils.Min(buflen, math.MaxUint32))
	{ // Field #0 'RANDAOReveal' (static)
		buf := buf[0:96]
		copy(t.RANDAOReveal[:], buf)
	}
	{ // Field #1 'Graffiti' (static)
		buf := buf[96:128]
		copy(t.Graffiti[:], buf)
	}
	// Field #2 'ProposerSlashings' (offset)
	offset2 := binary.LittleEndian.Uint32(buf[128:132])
	if offset2 != 320 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset2, 320), "ProposerSlashings:o")
	}
	// Field #3 'AttesterSlashings' (offset)
	offset3 := binary.LittleEndian.Uint32(buf[132:136])
	if offset3 < offset2 || offset3 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset3, offset2, buflen), "AttesterSlashings:o")
	}
	// Field #4 'Attestations' (offset)
	offset4 := binary.LittleEndian.Uint32(buf[136:140])
	if offset4 < offset3 || offset4 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset4, offset3, buflen), "Attestations:o")
	}
	// Field #5 'VoluntaryExits' (offset)
	offset5 := binary.LittleEndian.Uint32(buf[140:144])
	if offset5 < offset4 || offset5 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset5, offset4, buflen), "VoluntaryExits:o")
	}
	{ // Field #6 'SyncAggregate' (static)
		buf := buf[144:304]
		if t.SyncAggregate == nil {
			t.SyncAggregate = new(altair.SyncAggregate)
		}
		if err = t.SyncAggregate.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "SyncAggregate")
		}
	}
	// Field #7 'BLSToExecutionChanges' (offset)
	offset7 := binary.LittleEndian.Uint32(buf[304:308])
	if offset7 < offset5 || offset7 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset7, offset5, buflen), "BLSToExecutionChanges:o")
	}
	// Field #8 'SignedExecutionPayloadBid' (offset)
	offset8 := binary.LittleEndian.Uint32(buf[308:312])
	if offset8 < offset7 || offset8 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset8, offset7, buflen), "SignedExecutionPayloadBid:o")
	}
	// Field #9 'PayloadAttestations' (offset)
	offset9 := binary.LittleEndian.Uint32(buf[312:316])
	if offset9 < offset8 || offset9 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset9, offset8, buflen), "PayloadAttestations:o")
	}
	// Field #10 'ParentExecutionRequests' (offset)
	offset10 := binary.LittleEndian.Uint32(buf[316:320])
	if offset10 < offset9 || offset10 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset10, offset9, buflen), "ParentExecutionRequests:o")
	}
	{ // Field #2 'ProposerSlashings' (dynamic)
		buf := buf[offset2:offset3]
		val1 := t.ProposerSlashings
		itemCount := len(buf) / 416
		if len(buf)%416 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 416), "ProposerSlashings")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			if val1[idx1] == nil {
				val1[idx1] = new(phase0.ProposerSlashing)
			}
			buf := buf[416*idx1 : 416*(idx1+1)]
			if err = val1[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "ProposerSlashings[%d]", idx1)
			}
		}
		t.ProposerSlashings = val1
	}
	{ // Field #3 'AttesterSlashings' (dynamic)
		buf := buf[offset3:offset4]
		val2 := t.AttesterSlashings
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrorWithPath(sszutils.ErrListOffsetsEOFFn(len(buf), 4), "AttesterSlashings")
			}
			firstOffset := binary.LittleEndian.Uint32(buf[0:4])
			if firstOffset%4 != 0 || uint64(firstOffset) > uint64(len(buf)) || firstOffset == 0 {
				return sszutils.ErrorWithPath(sszutils.ErrInvalidListStartOffsetFn(firstOffset, len(buf)), "AttesterSlashings")
			}
			startOffset = int(firstOffset)
		}
		itemCount := startOffset / 4
		if itemCount > (len(buf)-startOffset)/(8) {
			return sszutils.ErrorWithPath(sszutils.ErrListRegionTooSmallFn(itemCount, 8, len(buf)-startOffset), "AttesterSlashings")
		}
		val2 = sszutils.ExpandSlice(val2, itemCount)
		for idx1 := range itemCount {
			var endOffset int
			if idx1 < itemCount-1 {
				endOffset = int(binary.LittleEndian.Uint32(buf[(idx1+1)*4 : (idx1+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrorWithPathf(sszutils.ErrElementOffsetOutOfRangeFn(endOffset, startOffset, len(buf)), "AttesterSlashings[%d]", idx1)
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val3 := val2[idx1]
			if val3 == nil {
				val3 = new(gloas.AttesterSlashing)
			}
			if err = val3.UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "AttesterSlashings[%d]", idx1)
			}
			val2[idx1] = val3
		}
		t.AttesterSlashings = val2
	}
	{ // Field #4 'Attestations' (dynamic)
		buf := buf[offset4:offset5]
		val4 := t.Attestations
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrorWithPath(sszutils.ErrListOffsetsEOFFn(len(buf), 4), "Attestations")
			}
			firstOffset := binary.LittleEndian.Uint32(buf[0:4])
			if firstOffset%4 != 0 || uint64(firstOffset) > uint64(len(buf)) || firstOffset == 0 {
				return sszutils.ErrorWithPath(sszutils.ErrInvalidListStartOffsetFn(firstOffset, len(buf)), "Attestations")
			}
			startOffset = int(firstOffset)
		}
		itemCount := startOffset / 4
		if itemCount > (len(buf)-startOffset)/(236) {
			return sszutils.ErrorWithPath(sszutils.ErrListRegionTooSmallFn(itemCount, 236, len(buf)-startOffset), "Attestations")
		}
		val4 = sszutils.ExpandSlice(val4, itemCount)
		for idx1 := range itemCount {
			var endOffset int
			if idx1 < itemCount-1 {
				endOffset = int(binary.LittleEndian.Uint32(buf[(idx1+1)*4 : (idx1+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrorWithPathf(sszutils.ErrElementOffsetOutOfRangeFn(endOffset, startOffset, len(buf)), "Attestations[%d]", idx1)
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val5 := val4[idx1]
			if val5 == nil {
				val5 = new(gloas.Attestation)
			}
			if err = val5.UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Attestations[%d]", idx1)
			}
			val4[idx1] = val5
		}
		t.Attestations = val4
	}
	{ // Field #5 'VoluntaryExits' (dynamic)
		buf := buf[offset5:offset7]
		val6 := t.VoluntaryExits
		itemCount := len(buf) / 112
		if len(buf)%112 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 112), "VoluntaryExits")
		}
		val6 = sszutils.ExpandSlice(val6, itemCount)
		for idx1 := range itemCount {
			if val6[idx1] == nil {
				val6[idx1] = new(phase0.SignedVoluntaryExit)
			}
			buf := buf[112*idx1 : 112*(idx1+1)]
			if err = val6[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "VoluntaryExits[%d]", idx1)
			}
		}
		t.VoluntaryExits = val6
	}
	{ // Field #7 'BLSToExecutionChanges' (dynamic)
		buf := buf[offset7:offset8]
		val7 := t.BLSToExecutionChanges
		itemCount := len(buf) / 172
		if len(buf)%172 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 172), "BLSToExecutionChanges")
		}
		val7 = sszutils.ExpandSlice(val7, itemCount)
		for idx1 := range itemCount {
			if val7[idx1] == nil {
				val7[idx1] = new(capella.SignedBLSToExecutionChange)
			}
			buf := buf[172*idx1 : 172*(idx1+1)]
			if err = val7[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "BLSToExecutionChanges[%d]", idx1)
			}
		}
		t.BLSToExecutionChanges = val7
	}
	{ // Field #8 'SignedExecutionPayloadBid' (dynamic)
		buf := buf[offset8:offset9]
		if t.SignedExecutionPayloadBid == nil {
			t.SignedExecutionPayloadBid = new(SignedExecutionPayloadBid)
		}
		if err = t.SignedExecutionPayloadBid.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "SignedExecutionPayloadBid")
		}
	}
	{ // Field #9 'PayloadAttestations' (dynamic)
		buf := buf[offset9:offset10]
		val8 := t.PayloadAttestations
		itemCount := len(buf) / 202
		if len(buf)%202 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 202), "PayloadAttestations")
		}
		val8 = sszutils.ExpandSlice(val8, itemCount)
		for idx1 := range itemCount {
			if val8[idx1] == nil {
				val8[idx1] = new(gloas.PayloadAttestation)
			}
			buf := buf[202*idx1 : 202*(idx1+1)]
			if err = val8[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "PayloadAttestations[%d]", idx1)
			}
		}
		t.PayloadAttestations = val8
	}
	{ // Field #10 'ParentExecutionRequests' (dynamic)
		buf := buf[offset10:]
		if t.ParentExecutionRequests == nil {
			t.ParentExecutionRequests = new(gloas.ExecutionRequests)
		}
		if err = t.ParentExecutionRequests.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "ParentExecutionRequests")
		}
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *BeaconBlockBody.
func (t *BeaconBlockBody) SizeSSZ() int {
	var size int64
	if t == nil {
		t = new(BeaconBlockBody)
	}
	// Field #0 'RANDAOReveal' static (96 bytes)
	// Field #1 'Graffiti' static (32 bytes)
	// Field #2 'ProposerSlashings' offset (4 bytes)
	// Field #3 'AttesterSlashings' offset (4 bytes)
	// Field #4 'Attestations' offset (4 bytes)
	// Field #5 'VoluntaryExits' offset (4 bytes)
	// Field #6 'SyncAggregate' static (160 bytes)
	// Field #7 'BLSToExecutionChanges' offset (4 bytes)
	// Field #8 'SignedExecutionPayloadBid' offset (4 bytes)
	// Field #9 'PayloadAttestations' offset (4 bytes)
	// Field #10 'ParentExecutionRequests' offset (4 bytes)
	size += 320
	{ // Dynamic field #2 'ProposerSlashings'
		size += int64(len(t.ProposerSlashings)) * 416
	}
	{ // Dynamic field #3 'AttesterSlashings'
		t2 := t.AttesterSlashings
		vlen := len(t2)
		size += int64(vlen) * 4 // Offsets
		for i1 := range vlen {
			s1 := int64(t2[i1].SizeSSZ())
			if s1 < 0 {
				return -1
			}
			size += s1
		}
	}
	{ // Dynamic field #4 'Attestations'
		t2 := t.Attestations
		vlen := len(t2)
		size += int64(vlen) * 4 // Offsets
		for i2 := range vlen {
			s2 := int64(t2[i2].SizeSSZ())
			if s2 < 0 {
				return -1
			}
			size += s2
		}
	}
	{ // Dynamic field #5 'VoluntaryExits'
		size += int64(len(t.VoluntaryExits)) * 112
	}
	{ // Dynamic field #7 'BLSToExecutionChanges'
		size += int64(len(t.BLSToExecutionChanges)) * 172
	}
	{ // Dynamic field #8 'SignedExecutionPayloadBid'
		s3 := int64(t.SignedExecutionPayloadBid.SizeSSZ())
		if s3 < 0 {
			return -1
		}
		size += s3
	}
	{ // Dynamic field #9 'PayloadAttestations'
		size += int64(len(t.PayloadAttestations)) * 202
	}
	{ // Dynamic field #10 'ParentExecutionRequests'
		s4 := int64(t.ParentExecutionRequests.SizeSSZ())
		if s4 < 0 {
			return -1
		}
		size += s4
	}
	if uint64(size) > sszutils.MaxSszSize {
		return -1
	}
	return int(size)
}

// HashTreeRoot computes the SSZ hash tree root of the *BeaconBlockBody.
func (t *BeaconBlockBody) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *BeaconBlockBody using the given hash walker.
func (t *BeaconBlockBody) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BeaconBlockBody)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'RANDAOReveal'
		hh.PutBytes(t.RANDAOReveal[:96])
	}
	// Inactive field #1
	hh.PutUint8(0)
	{ // Field #1 'Graffiti'
		hh.PutBytes(t.Graffiti[:32])
	}
	{ // Field #2 'ProposerSlashings'
		t := t.ProposerSlashings
		idx := hh.StartTree(sszutils.TreeTypeProgressive)
		vlen := uint64(len(t))
		for idx1 := range len(t) {
			t := t[idx1]
			if t == nil {
				t = new(phase0.ProposerSlashing)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "ProposerSlashings[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeProgressiveWithMixin(idx, vlen)
	}
	{ // Field #3 'AttesterSlashings'
		t := t.AttesterSlashings
		idx := hh.StartTree(sszutils.TreeTypeProgressive)
		vlen := uint64(len(t))
		for idx1 := range len(t) {
			t := t[idx1]
			if t == nil {
				t = new(gloas.AttesterSlashing)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "AttesterSlashings[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeProgressiveWithMixin(idx, vlen)
	}
	{ // Field #4 'Attestations'
		t := t.Attestations
		idx := hh.StartTree(sszutils.TreeTypeProgressive)
		vlen := uint64(len(t))
		for idx1 := range len(t) {
			t := t[idx1]
			if t == nil {
				t = new(gloas.Attestation)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Attestations[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeProgressiveWithMixin(idx, vlen)
	}
	// Inactive field #6
	hh.PutUint8(0)
	{ // Field #5 'VoluntaryExits'
		t := t.VoluntaryExits
		idx := hh.StartTree(sszutils.TreeTypeProgressive)
		vlen := uint64(len(t))
		for idx1 := range len(t) {
			t := t[idx1]
			if t == nil {
				t = new(phase0.SignedVoluntaryExit)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "VoluntaryExits[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeProgressiveWithMixin(idx, vlen)
	}
	{ // Field #6 'SyncAggregate'
		t := t.SyncAggregate
		if t == nil {
			t = new(altair.SyncAggregate)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "SyncAggregate")
		}
	}
	{ // Field #7 'BLSToExecutionChanges'
		t := t.BLSToExecutionChanges
		idx := hh.StartTree(sszutils.TreeTypeProgressive)
		vlen := uint64(len(t))
		for idx1 := range len(t) {
			t := t[idx1]
			if t == nil {
				t = new(capella.SignedBLSToExecutionChange)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "BLSToExecutionChanges[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeProgressiveWithMixin(idx, vlen)
	}
	{ // Field #8 'SignedExecutionPayloadBid'
		t := t.SignedExecutionPayloadBid
		if t == nil {
			t = new(SignedExecutionPayloadBid)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "SignedExecutionPayloadBid")
		}
	}
	{ // Field #9 'PayloadAttestations'
		t := t.PayloadAttestations
		idx := hh.StartTree(sszutils.TreeTypeProgressive)
		vlen := uint64(len(t))
		for idx1 := range len(t) {
			t := t[idx1]
			if t == nil {
				t = new(gloas.PayloadAttestation)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "PayloadAttestations[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeProgressiveWithMixin(idx, vlen)
	}
	{ // Field #10 'ParentExecutionRequests'
		t := t.ParentExecutionRequests
		if t == nil {
			t = new(gloas.ExecutionRequests)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "ParentExecutionRequests")
		}
	}
	hh.MerkleizeProgressiveWithActiveFields(idx, []byte{0xbd, 0x1f})
	return nil
}
