// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: ab4e65d29fd0bec6ad58b87a33dfab3171dcc6ef32b98ee09d85f88edf5d8aa7
// Version: v1.4.0-pre.3 (https://github.com/pk910/dynamic-ssz)

package heze

import (
	"encoding/binary"
	"math"

	"github.com/ethpandaops/go-eth2-client/spec/altair"
	"github.com/ethpandaops/go-eth2-client/spec/capella"
	"github.com/ethpandaops/go-eth2-client/spec/electra"
	"github.com/ethpandaops/go-eth2-client/spec/gloas"
	"github.com/ethpandaops/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[BeaconState](`ssz-static:"false"`)

// MarshalSSZ marshals the *BeaconState to SSZ-encoded bytes.
func (t *BeaconState) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *BeaconState to SSZ-encoded bytes, appending to the provided buffer.
func (t *BeaconState) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	zeroBytes := sszutils.ZeroBytes()
	if t == nil {
		t = new(BeaconState)
	}
	dstlen := len(dst)
	{ // Static Field #0 'GenesisTime'
		dst = binary.LittleEndian.AppendUint64(dst, t.GenesisTime)
	}
	{ // Static Field #1 'GenesisValidatorsRoot'
		dst = append(dst, t.GenesisValidatorsRoot[:32]...)
	}
	{ // Static Field #2 'Slot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Slot))
	}
	{ // Static Field #3 'Fork'
		t := t.Fork
		if t == nil {
			t = new(phase0.Fork)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Fork")
		}
	}
	{ // Static Field #4 'LatestBlockHeader'
		t := t.LatestBlockHeader
		if t == nil {
			t = new(phase0.BeaconBlockHeader)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "LatestBlockHeader")
		}
	}
	{ // Static Field #5 'BlockRoots'
		t := t.BlockRoots
		vlen := len(t)
		if vlen > 8192 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 8192), "BlockRoots")
		}
		dst = sszutils.MarshalFixedBytesSlice(dst, t[:vlen])
		if vlen < 8192 {
			dst = sszutils.AppendZeroPadding(dst, (8192-vlen)*32)
		}
	}
	{ // Static Field #6 'StateRoots'
		t := t.StateRoots
		vlen := len(t)
		if vlen > 8192 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 8192), "StateRoots")
		}
		dst = sszutils.MarshalFixedBytesSlice(dst, t[:vlen])
		if vlen < 8192 {
			dst = sszutils.AppendZeroPadding(dst, (8192-vlen)*32)
		}
	}
	// Offset Field #7 'HistoricalRoots'
	// Offset Field #8 'Validators'
	// Offset Field #9 'Balances'
	dst = append(dst, zeroBytes[:12]...)
	{ // Static Field #10 'RANDAOMixes'
		t := t.RANDAOMixes
		vlen := len(t)
		if vlen > 65536 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 65536), "RANDAOMixes")
		}
		dst = sszutils.MarshalFixedBytesSlice(dst, t[:vlen])
		if vlen < 65536 {
			dst = sszutils.AppendZeroPadding(dst, (65536-vlen)*32)
		}
	}
	{ // Static Field #11 'Slashings'
		t := t.Slashings
		vlen := len(t)
		if vlen > 8192 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 8192), "Slashings")
		}
		dst = sszutils.MarshalUint64Slice(dst, t[:vlen])
		if vlen < 8192 {
			dst = sszutils.AppendZeroPadding(dst, (8192-vlen)*8)
		}
	}
	// Offset Field #12 'PreviousEpochParticipation'
	// Offset Field #13 'CurrentEpochParticipation'
	dst = append(dst, 0, 0, 0, 0, 0, 0, 0, 0)
	{ // Static Field #14 'JustificationBits'
		vlen := len(t.JustificationBits)
		if vlen > 1 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 1), "JustificationBits")
		}
		dst = append(dst, t.JustificationBits[:vlen]...)
		if vlen < 1 {
			dst = sszutils.AppendZeroPadding(dst, (1-vlen)*1)
		}
	}
	{ // Static Field #15 'PreviousJustifiedCheckpoint'
		t := t.PreviousJustifiedCheckpoint
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "PreviousJustifiedCheckpoint")
		}
	}
	{ // Static Field #16 'CurrentJustifiedCheckpoint'
		t := t.CurrentJustifiedCheckpoint
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "CurrentJustifiedCheckpoint")
		}
	}
	{ // Static Field #17 'FinalizedCheckpoint'
		t := t.FinalizedCheckpoint
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "FinalizedCheckpoint")
		}
	}
	// Offset Field #18 'InactivityScores'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #19 'CurrentSyncCommittee'
		t := t.CurrentSyncCommittee
		if t == nil {
			t = new(altair.SyncCommittee)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "CurrentSyncCommittee")
		}
	}
	{ // Static Field #20 'NextSyncCommittee'
		t := t.NextSyncCommittee
		if t == nil {
			t = new(altair.SyncCommittee)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "NextSyncCommittee")
		}
	}
	{ // Static Field #21 'LatestBlockHash'
		dst = append(dst, t.LatestBlockHash[:32]...)
	}
	{ // Static Field #22 'NextWithdrawalIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.NextWithdrawalIndex))
	}
	{ // Static Field #23 'NextWithdrawalValidatorIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.NextWithdrawalValidatorIndex))
	}
	// Offset Field #24 'HistoricalSummaries'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #25 'DepositBalanceToConsume'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.DepositBalanceToConsume))
	}
	{ // Static Field #26 'ExitBalanceToConsume'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ExitBalanceToConsume))
	}
	{ // Static Field #27 'EarliestExitEpoch'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.EarliestExitEpoch))
	}
	{ // Static Field #28 'ConsolidationBalanceToConsume'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ConsolidationBalanceToConsume))
	}
	{ // Static Field #29 'EarliestConsolidationEpoch'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.EarliestConsolidationEpoch))
	}
	// Offset Field #30 'PendingDeposits'
	// Offset Field #31 'PendingPartialWithdrawals'
	// Offset Field #32 'PendingConsolidations'
	dst = append(dst, zeroBytes[:12]...)
	{ // Static Field #33 'ProposerLookahead'
		t := t.ProposerLookahead
		vlen := len(t)
		if vlen > 64 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 64), "ProposerLookahead")
		}
		dst = sszutils.MarshalUint64Slice(dst, t[:vlen])
		if vlen < 64 {
			dst = sszutils.AppendZeroPadding(dst, (64-vlen)*8)
		}
	}
	// Offset Field #34 'Builders'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #35 'NextWithdrawalBuilderIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.NextWithdrawalBuilderIndex))
	}
	{ // Static Field #36 'ExecutionPayloadAvailability'
		vlen := len(t.ExecutionPayloadAvailability)
		if vlen > 1024 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 1024), "ExecutionPayloadAvailability")
		}
		dst = append(dst, t.ExecutionPayloadAvailability[:vlen]...)
		if vlen < 1024 {
			dst = sszutils.AppendZeroPadding(dst, (1024-vlen)*1)
		}
	}
	{ // Static Field #37 'BuilderPendingPayments'
		t := t.BuilderPendingPayments
		vlen := len(t)
		if vlen > 64 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 64), "BuilderPendingPayments")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(gloas.BuilderPendingPayment)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "BuilderPendingPayments[%d]", idx1)
			}
		}
		if vlen < 64 {
			dst = sszutils.AppendZeroPadding(dst, (64-vlen)*52)
		}
	}
	// Offset Field #38 'BuilderPendingWithdrawals'
	// Offset Field #39 'LatestExecutionPayloadBid'
	// Offset Field #40 'PayloadExpectedWithdrawals'
	dst = append(dst, zeroBytes[:12]...)
	{ // Static Field #41 'PTCWindow'
		t := t.PTCWindow
		vlen := len(t)
		if vlen > 96 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 96), "PTCWindow")
		}
		for idx1 := range vlen {
			t := t[idx1]
			vlen := len(t)
			if vlen > 512 {
				return nil, sszutils.ErrorWithPathf(sszutils.ErrVectorLengthFn(vlen, 512), "PTCWindow[%d]", idx1)
			}
			dst = sszutils.MarshalUint64Slice(dst, t[:vlen])
			if vlen < 512 {
				dst = sszutils.AppendZeroPadding(dst, (512-vlen)*8)
			}
		}
		if vlen < 96 {
			dst = sszutils.AppendZeroPadding(dst, (96-vlen)*4096)
		}
	}
	{ // Dynamic Field #7 'HistoricalRoots'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+524464:], uint32(off))
		}
		t := t.HistoricalRoots
		vlen := len(t)
		if vlen > 16777216 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 16777216), "HistoricalRoots")
		}
		dst = sszutils.MarshalFixedBytesSlice(dst, t[:vlen])
	}
	{ // Dynamic Field #8 'Validators'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+524468:], uint32(off))
		}
		t := t.Validators
		vlen := len(t)
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(phase0.Validator)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Validators[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #9 'Balances'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+524472:], uint32(off))
		}
		t := t.Balances
		vlen := len(t)
		dst = sszutils.MarshalUint64Slice(dst, t[:vlen])
	}
	{ // Dynamic Field #12 'PreviousEpochParticipation'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+2687164:], uint32(off))
		}
		t := t.PreviousEpochParticipation
		vlen := len(t)
		for idx1 := range vlen {
			dst = append(dst, byte(t[idx1]))
		}
	}
	{ // Dynamic Field #13 'CurrentEpochParticipation'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+2687168:], uint32(off))
		}
		t := t.CurrentEpochParticipation
		vlen := len(t)
		for idx1 := range vlen {
			dst = append(dst, byte(t[idx1]))
		}
	}
	{ // Dynamic Field #18 'InactivityScores'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+2687293:], uint32(off))
		}
		t := t.InactivityScores
		vlen := len(t)
		dst = sszutils.MarshalUint64Slice(dst, t[:vlen])
	}
	{ // Dynamic Field #24 'HistoricalSummaries'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+2736593:], uint32(off))
		}
		t := t.HistoricalSummaries
		vlen := len(t)
		if vlen > 16777216 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 16777216), "HistoricalSummaries")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(capella.HistoricalSummary)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "HistoricalSummaries[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #30 'PendingDeposits'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+2736637:], uint32(off))
		}
		t := t.PendingDeposits
		vlen := len(t)
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(electra.PendingDeposit)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "PendingDeposits[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #31 'PendingPartialWithdrawals'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+2736641:], uint32(off))
		}
		t := t.PendingPartialWithdrawals
		vlen := len(t)
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(electra.PendingPartialWithdrawal)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "PendingPartialWithdrawals[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #32 'PendingConsolidations'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+2736645:], uint32(off))
		}
		t := t.PendingConsolidations
		vlen := len(t)
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(electra.PendingConsolidation)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "PendingConsolidations[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #34 'Builders'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+2737161:], uint32(off))
		}
		t := t.Builders
		vlen := len(t)
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(gloas.Builder)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Builders[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #38 'BuilderPendingWithdrawals'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+2741525:], uint32(off))
		}
		t := t.BuilderPendingWithdrawals
		vlen := len(t)
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(gloas.BuilderPendingWithdrawal)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "BuilderPendingWithdrawals[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #39 'LatestExecutionPayloadBid'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+2741529:], uint32(off))
		}
		t := t.LatestExecutionPayloadBid
		if t == nil {
			t = new(ExecutionPayloadBid)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "LatestExecutionPayloadBid")
		}
	}
	{ // Dynamic Field #40 'PayloadExpectedWithdrawals'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+2741533:], uint32(off))
		}
		t := t.PayloadExpectedWithdrawals
		vlen := len(t)
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(capella.Withdrawal)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "PayloadExpectedWithdrawals[%d]", idx1)
			}
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *BeaconState from SSZ-encoded bytes.
func (t *BeaconState) UnmarshalSSZ(buf []byte) (err error) {
	buflen := uint64(len(buf))
	if buflen < 3134753 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 3134753)
	}
	maxOffset := uint32(sszutils.Min(buflen, math.MaxUint32))
	{ // Field #0 'GenesisTime' (static)
		buf := buf[0:8]
		t.GenesisTime = binary.LittleEndian.Uint64(buf)
	}
	{ // Field #1 'GenesisValidatorsRoot' (static)
		buf := buf[8:40]
		copy(t.GenesisValidatorsRoot[:], buf)
	}
	{ // Field #2 'Slot' (static)
		buf := buf[40:48]
		t.Slot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #3 'Fork' (static)
		buf := buf[48:64]
		if t.Fork == nil {
			t.Fork = new(phase0.Fork)
		}
		if err = t.Fork.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Fork")
		}
	}
	{ // Field #4 'LatestBlockHeader' (static)
		buf := buf[64:176]
		if t.LatestBlockHeader == nil {
			t.LatestBlockHeader = new(phase0.BeaconBlockHeader)
		}
		if err = t.LatestBlockHeader.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "LatestBlockHeader")
		}
	}
	{ // Field #5 'BlockRoots' (static)
		buf := buf[176:262320]
		val1 := t.BlockRoots
		val1 = sszutils.ExpandSlice(val1, 8192)
		sszutils.UnmarshalFixedBytesSlice(val1[:8192], buf)
		t.BlockRoots = val1
	}
	{ // Field #6 'StateRoots' (static)
		buf := buf[262320:524464]
		val2 := t.StateRoots
		val2 = sszutils.ExpandSlice(val2, 8192)
		sszutils.UnmarshalFixedBytesSlice(val2[:8192], buf)
		t.StateRoots = val2
	}
	// Field #7 'HistoricalRoots' (offset)
	offset7 := binary.LittleEndian.Uint32(buf[524464:524468])
	if offset7 != 3134753 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset7, 3134753), "HistoricalRoots:o")
	}
	// Field #8 'Validators' (offset)
	offset8 := binary.LittleEndian.Uint32(buf[524468:524472])
	if offset8 < offset7 || offset8 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset8, offset7, buflen), "Validators:o")
	}
	// Field #9 'Balances' (offset)
	offset9 := binary.LittleEndian.Uint32(buf[524472:524476])
	if offset9 < offset8 || offset9 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset9, offset8, buflen), "Balances:o")
	}
	{ // Field #10 'RANDAOMixes' (static)
		buf := buf[524476:2621628]
		val3 := t.RANDAOMixes
		val3 = sszutils.ExpandSlice(val3, 65536)
		sszutils.UnmarshalFixedBytesSlice(val3[:65536], buf)
		t.RANDAOMixes = val3
	}
	{ // Field #11 'Slashings' (static)
		buf := buf[2621628:2687164]
		val4 := t.Slashings
		val4 = sszutils.ExpandSlice(val4, 8192)
		sszutils.UnmarshalUint64Slice(val4[:8192], buf)
		t.Slashings = val4
	}
	// Field #12 'PreviousEpochParticipation' (offset)
	offset12 := binary.LittleEndian.Uint32(buf[2687164:2687168])
	if offset12 < offset9 || offset12 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset12, offset9, buflen), "PreviousEpochParticipation:o")
	}
	// Field #13 'CurrentEpochParticipation' (offset)
	offset13 := binary.LittleEndian.Uint32(buf[2687168:2687172])
	if offset13 < offset12 || offset13 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset13, offset12, buflen), "CurrentEpochParticipation:o")
	}
	{ // Field #14 'JustificationBits' (static)
		buf := buf[2687172:2687173]
		t.JustificationBits = sszutils.ExpandSlice(t.JustificationBits, 1)
		copy(t.JustificationBits[:], buf)
	}
	{ // Field #15 'PreviousJustifiedCheckpoint' (static)
		buf := buf[2687173:2687213]
		if t.PreviousJustifiedCheckpoint == nil {
			t.PreviousJustifiedCheckpoint = new(phase0.Checkpoint)
		}
		if err = t.PreviousJustifiedCheckpoint.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "PreviousJustifiedCheckpoint")
		}
	}
	{ // Field #16 'CurrentJustifiedCheckpoint' (static)
		buf := buf[2687213:2687253]
		if t.CurrentJustifiedCheckpoint == nil {
			t.CurrentJustifiedCheckpoint = new(phase0.Checkpoint)
		}
		if err = t.CurrentJustifiedCheckpoint.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "CurrentJustifiedCheckpoint")
		}
	}
	{ // Field #17 'FinalizedCheckpoint' (static)
		buf := buf[2687253:2687293]
		if t.FinalizedCheckpoint == nil {
			t.FinalizedCheckpoint = new(phase0.Checkpoint)
		}
		if err = t.FinalizedCheckpoint.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "FinalizedCheckpoint")
		}
	}
	// Field #18 'InactivityScores' (offset)
	offset18 := binary.LittleEndian.Uint32(buf[2687293:2687297])
	if offset18 < offset13 || offset18 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset18, offset13, buflen), "InactivityScores:o")
	}
	{ // Field #19 'CurrentSyncCommittee' (static)
		buf := buf[2687297:2711921]
		if t.CurrentSyncCommittee == nil {
			t.CurrentSyncCommittee = new(altair.SyncCommittee)
		}
		if err = t.CurrentSyncCommittee.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "CurrentSyncCommittee")
		}
	}
	{ // Field #20 'NextSyncCommittee' (static)
		buf := buf[2711921:2736545]
		if t.NextSyncCommittee == nil {
			t.NextSyncCommittee = new(altair.SyncCommittee)
		}
		if err = t.NextSyncCommittee.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "NextSyncCommittee")
		}
	}
	{ // Field #21 'LatestBlockHash' (static)
		buf := buf[2736545:2736577]
		copy(t.LatestBlockHash[:], buf)
	}
	{ // Field #22 'NextWithdrawalIndex' (static)
		buf := buf[2736577:2736585]
		t.NextWithdrawalIndex = capella.WithdrawalIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #23 'NextWithdrawalValidatorIndex' (static)
		buf := buf[2736585:2736593]
		t.NextWithdrawalValidatorIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	// Field #24 'HistoricalSummaries' (offset)
	offset24 := binary.LittleEndian.Uint32(buf[2736593:2736597])
	if offset24 < offset18 || offset24 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset24, offset18, buflen), "HistoricalSummaries:o")
	}
	{ // Field #25 'DepositBalanceToConsume' (static)
		buf := buf[2736597:2736605]
		t.DepositBalanceToConsume = phase0.Gwei(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #26 'ExitBalanceToConsume' (static)
		buf := buf[2736605:2736613]
		t.ExitBalanceToConsume = phase0.Gwei(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #27 'EarliestExitEpoch' (static)
		buf := buf[2736613:2736621]
		t.EarliestExitEpoch = phase0.Epoch(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #28 'ConsolidationBalanceToConsume' (static)
		buf := buf[2736621:2736629]
		t.ConsolidationBalanceToConsume = phase0.Gwei(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #29 'EarliestConsolidationEpoch' (static)
		buf := buf[2736629:2736637]
		t.EarliestConsolidationEpoch = phase0.Epoch(binary.LittleEndian.Uint64(buf))
	}
	// Field #30 'PendingDeposits' (offset)
	offset30 := binary.LittleEndian.Uint32(buf[2736637:2736641])
	if offset30 < offset24 || offset30 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset30, offset24, buflen), "PendingDeposits:o")
	}
	// Field #31 'PendingPartialWithdrawals' (offset)
	offset31 := binary.LittleEndian.Uint32(buf[2736641:2736645])
	if offset31 < offset30 || offset31 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset31, offset30, buflen), "PendingPartialWithdrawals:o")
	}
	// Field #32 'PendingConsolidations' (offset)
	offset32 := binary.LittleEndian.Uint32(buf[2736645:2736649])
	if offset32 < offset31 || offset32 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset32, offset31, buflen), "PendingConsolidations:o")
	}
	{ // Field #33 'ProposerLookahead' (static)
		buf := buf[2736649:2737161]
		val5 := t.ProposerLookahead
		val5 = sszutils.ExpandSlice(val5, 64)
		sszutils.UnmarshalUint64Slice(val5[:64], buf)
		t.ProposerLookahead = val5
	}
	// Field #34 'Builders' (offset)
	offset34 := binary.LittleEndian.Uint32(buf[2737161:2737165])
	if offset34 < offset32 || offset34 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset34, offset32, buflen), "Builders:o")
	}
	{ // Field #35 'NextWithdrawalBuilderIndex' (static)
		buf := buf[2737165:2737173]
		t.NextWithdrawalBuilderIndex = gloas.BuilderIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #36 'ExecutionPayloadAvailability' (static)
		buf := buf[2737173:2738197]
		t.ExecutionPayloadAvailability = sszutils.ExpandSlice(t.ExecutionPayloadAvailability, 1024)
		copy(t.ExecutionPayloadAvailability[:], buf)
	}
	{ // Field #37 'BuilderPendingPayments' (static)
		buf := buf[2738197:2741525]
		val6 := t.BuilderPendingPayments
		val6 = sszutils.ExpandSlice(val6, 64)
		for idx1 := range 64 {
			if val6[idx1] == nil {
				val6[idx1] = new(gloas.BuilderPendingPayment)
			}
			buf := buf[52*idx1 : 52*(idx1+1)]
			if err = val6[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "BuilderPendingPayments[%d]", idx1)
			}
		}
		t.BuilderPendingPayments = val6
	}
	// Field #38 'BuilderPendingWithdrawals' (offset)
	offset38 := binary.LittleEndian.Uint32(buf[2741525:2741529])
	if offset38 < offset34 || offset38 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset38, offset34, buflen), "BuilderPendingWithdrawals:o")
	}
	// Field #39 'LatestExecutionPayloadBid' (offset)
	offset39 := binary.LittleEndian.Uint32(buf[2741529:2741533])
	if offset39 < offset38 || offset39 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset39, offset38, buflen), "LatestExecutionPayloadBid:o")
	}
	// Field #40 'PayloadExpectedWithdrawals' (offset)
	offset40 := binary.LittleEndian.Uint32(buf[2741533:2741537])
	if offset40 < offset39 || offset40 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset40, offset39, buflen), "PayloadExpectedWithdrawals:o")
	}
	{ // Field #41 'PTCWindow' (static)
		buf := buf[2741537:3134753]
		val7 := t.PTCWindow
		val7 = sszutils.ExpandSlice(val7, 96)
		for idx1 := range 96 {
			val8 := val7[idx1]
			buf := buf[4096*idx1 : 4096*(idx1+1)]
			val8 = sszutils.ExpandSlice(val8, 512)
			sszutils.UnmarshalUint64Slice(val8[:512], buf)
			val7[idx1] = val8
		}
		t.PTCWindow = val7
	}
	{ // Field #7 'HistoricalRoots' (dynamic)
		buf := buf[offset7:offset8]
		val9 := t.HistoricalRoots
		itemCount := len(buf) / 32
		if len(buf)%32 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 32), "HistoricalRoots")
		}
		if itemCount > 16777216 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 16777216), "HistoricalRoots")
		}
		val9 = sszutils.ExpandSlice(val9, itemCount)
		sszutils.UnmarshalFixedBytesSlice(val9[:itemCount], buf)
		t.HistoricalRoots = val9
	}
	{ // Field #8 'Validators' (dynamic)
		buf := buf[offset8:offset9]
		val10 := t.Validators
		itemCount := len(buf) / 121
		if len(buf)%121 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 121), "Validators")
		}
		val10 = sszutils.ExpandSlice(val10, itemCount)
		for idx1 := range itemCount {
			if val10[idx1] == nil {
				val10[idx1] = new(phase0.Validator)
			}
			buf := buf[121*idx1 : 121*(idx1+1)]
			if err = val10[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Validators[%d]", idx1)
			}
		}
		t.Validators = val10
	}
	{ // Field #9 'Balances' (dynamic)
		buf := buf[offset9:offset12]
		val11 := t.Balances
		itemCount := len(buf) / 8
		if len(buf)%8 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 8), "Balances")
		}
		val11 = sszutils.ExpandSlice(val11, itemCount)
		sszutils.UnmarshalUint64Slice(val11, buf)
		t.Balances = val11
	}
	{ // Field #12 'PreviousEpochParticipation' (dynamic)
		buf := buf[offset12:offset13]
		val12 := t.PreviousEpochParticipation
		itemCount := len(buf)
		val12 = sszutils.ExpandSlice(val12, itemCount)
		for idx1 := range itemCount {
			buf := buf[1*idx1 : 1*(idx1+1)]
			val12[idx1] = altair.ParticipationFlags(buf[0])
		}
		t.PreviousEpochParticipation = val12
	}
	{ // Field #13 'CurrentEpochParticipation' (dynamic)
		buf := buf[offset13:offset18]
		val13 := t.CurrentEpochParticipation
		itemCount := len(buf)
		val13 = sszutils.ExpandSlice(val13, itemCount)
		for idx1 := range itemCount {
			buf := buf[1*idx1 : 1*(idx1+1)]
			val13[idx1] = altair.ParticipationFlags(buf[0])
		}
		t.CurrentEpochParticipation = val13
	}
	{ // Field #18 'InactivityScores' (dynamic)
		buf := buf[offset18:offset24]
		val14 := t.InactivityScores
		itemCount := len(buf) / 8
		if len(buf)%8 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 8), "InactivityScores")
		}
		val14 = sszutils.ExpandSlice(val14, itemCount)
		sszutils.UnmarshalUint64Slice(val14, buf)
		t.InactivityScores = val14
	}
	{ // Field #24 'HistoricalSummaries' (dynamic)
		buf := buf[offset24:offset30]
		val15 := t.HistoricalSummaries
		itemCount := len(buf) / 64
		if len(buf)%64 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 64), "HistoricalSummaries")
		}
		if itemCount > 16777216 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, 16777216), "HistoricalSummaries")
		}
		val15 = sszutils.ExpandSlice(val15, itemCount)
		for idx1 := range itemCount {
			if val15[idx1] == nil {
				val15[idx1] = new(capella.HistoricalSummary)
			}
			buf := buf[64*idx1 : 64*(idx1+1)]
			if err = val15[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "HistoricalSummaries[%d]", idx1)
			}
		}
		t.HistoricalSummaries = val15
	}
	{ // Field #30 'PendingDeposits' (dynamic)
		buf := buf[offset30:offset31]
		val16 := t.PendingDeposits
		itemCount := len(buf) / 192
		if len(buf)%192 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 192), "PendingDeposits")
		}
		val16 = sszutils.ExpandSlice(val16, itemCount)
		for idx1 := range itemCount {
			if val16[idx1] == nil {
				val16[idx1] = new(electra.PendingDeposit)
			}
			buf := buf[192*idx1 : 192*(idx1+1)]
			if err = val16[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "PendingDeposits[%d]", idx1)
			}
		}
		t.PendingDeposits = val16
	}
	{ // Field #31 'PendingPartialWithdrawals' (dynamic)
		buf := buf[offset31:offset32]
		val17 := t.PendingPartialWithdrawals
		itemCount := len(buf) / 24
		if len(buf)%24 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 24), "PendingPartialWithdrawals")
		}
		val17 = sszutils.ExpandSlice(val17, itemCount)
		for idx1 := range itemCount {
			if val17[idx1] == nil {
				val17[idx1] = new(electra.PendingPartialWithdrawal)
			}
			buf := buf[24*idx1 : 24*(idx1+1)]
			if err = val17[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "PendingPartialWithdrawals[%d]", idx1)
			}
		}
		t.PendingPartialWithdrawals = val17
	}
	{ // Field #32 'PendingConsolidations' (dynamic)
		buf := buf[offset32:offset34]
		val18 := t.PendingConsolidations
		itemCount := len(buf) / 16
		if len(buf)%16 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 16), "PendingConsolidations")
		}
		val18 = sszutils.ExpandSlice(val18, itemCount)
		for idx1 := range itemCount {
			if val18[idx1] == nil {
				val18[idx1] = new(electra.PendingConsolidation)
			}
			buf := buf[16*idx1 : 16*(idx1+1)]
			if err = val18[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "PendingConsolidations[%d]", idx1)
			}
		}
		t.PendingConsolidations = val18
	}
	{ // Field #34 'Builders' (dynamic)
		buf := buf[offset34:offset38]
		val19 := t.Builders
		itemCount := len(buf) / 93
		if len(buf)%93 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 93), "Builders")
		}
		val19 = sszutils.ExpandSlice(val19, itemCount)
		for idx1 := range itemCount {
			if val19[idx1] == nil {
				val19[idx1] = new(gloas.Builder)
			}
			buf := buf[93*idx1 : 93*(idx1+1)]
			if err = val19[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Builders[%d]", idx1)
			}
		}
		t.Builders = val19
	}
	{ // Field #38 'BuilderPendingWithdrawals' (dynamic)
		buf := buf[offset38:offset39]
		val20 := t.BuilderPendingWithdrawals
		itemCount := len(buf) / 36
		if len(buf)%36 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 36), "BuilderPendingWithdrawals")
		}
		val20 = sszutils.ExpandSlice(val20, itemCount)
		for idx1 := range itemCount {
			if val20[idx1] == nil {
				val20[idx1] = new(gloas.BuilderPendingWithdrawal)
			}
			buf := buf[36*idx1 : 36*(idx1+1)]
			if err = val20[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "BuilderPendingWithdrawals[%d]", idx1)
			}
		}
		t.BuilderPendingWithdrawals = val20
	}
	{ // Field #39 'LatestExecutionPayloadBid' (dynamic)
		buf := buf[offset39:offset40]
		if t.LatestExecutionPayloadBid == nil {
			t.LatestExecutionPayloadBid = new(ExecutionPayloadBid)
		}
		if err = t.LatestExecutionPayloadBid.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "LatestExecutionPayloadBid")
		}
	}
	{ // Field #40 'PayloadExpectedWithdrawals' (dynamic)
		buf := buf[offset40:]
		val21 := t.PayloadExpectedWithdrawals
		itemCount := len(buf) / 44
		if len(buf)%44 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 44), "PayloadExpectedWithdrawals")
		}
		val21 = sszutils.ExpandSlice(val21, itemCount)
		for idx1 := range itemCount {
			if val21[idx1] == nil {
				val21[idx1] = new(capella.Withdrawal)
			}
			buf := buf[44*idx1 : 44*(idx1+1)]
			if err = val21[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "PayloadExpectedWithdrawals[%d]", idx1)
			}
		}
		t.PayloadExpectedWithdrawals = val21
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *BeaconState.
func (t *BeaconState) SizeSSZ() int {
	var size int64
	if t == nil {
		t = new(BeaconState)
	}
	// Field #0 'GenesisTime' static (8 bytes)
	// Field #1 'GenesisValidatorsRoot' static (32 bytes)
	// Field #2 'Slot' static (8 bytes)
	// Field #3 'Fork' static (16 bytes)
	// Field #4 'LatestBlockHeader' static (112 bytes)
	// Field #5 'BlockRoots' static (262144 bytes)
	// Field #6 'StateRoots' static (262144 bytes)
	// Field #7 'HistoricalRoots' offset (4 bytes)
	// Field #8 'Validators' offset (4 bytes)
	// Field #9 'Balances' offset (4 bytes)
	// Field #10 'RANDAOMixes' static (2097152 bytes)
	// Field #11 'Slashings' static (65536 bytes)
	// Field #12 'PreviousEpochParticipation' offset (4 bytes)
	// Field #13 'CurrentEpochParticipation' offset (4 bytes)
	// Field #14 'JustificationBits' static (1 bytes)
	// Field #15 'PreviousJustifiedCheckpoint' static (40 bytes)
	// Field #16 'CurrentJustifiedCheckpoint' static (40 bytes)
	// Field #17 'FinalizedCheckpoint' static (40 bytes)
	// Field #18 'InactivityScores' offset (4 bytes)
	// Field #19 'CurrentSyncCommittee' static (24624 bytes)
	// Field #20 'NextSyncCommittee' static (24624 bytes)
	// Field #21 'LatestBlockHash' static (32 bytes)
	// Field #22 'NextWithdrawalIndex' static (8 bytes)
	// Field #23 'NextWithdrawalValidatorIndex' static (8 bytes)
	// Field #24 'HistoricalSummaries' offset (4 bytes)
	// Field #25 'DepositBalanceToConsume' static (8 bytes)
	// Field #26 'ExitBalanceToConsume' static (8 bytes)
	// Field #27 'EarliestExitEpoch' static (8 bytes)
	// Field #28 'ConsolidationBalanceToConsume' static (8 bytes)
	// Field #29 'EarliestConsolidationEpoch' static (8 bytes)
	// Field #30 'PendingDeposits' offset (4 bytes)
	// Field #31 'PendingPartialWithdrawals' offset (4 bytes)
	// Field #32 'PendingConsolidations' offset (4 bytes)
	// Field #33 'ProposerLookahead' static (512 bytes)
	// Field #34 'Builders' offset (4 bytes)
	// Field #35 'NextWithdrawalBuilderIndex' static (8 bytes)
	// Field #36 'ExecutionPayloadAvailability' static (1024 bytes)
	// Field #37 'BuilderPendingPayments' static (3328 bytes)
	// Field #38 'BuilderPendingWithdrawals' offset (4 bytes)
	// Field #39 'LatestExecutionPayloadBid' offset (4 bytes)
	// Field #40 'PayloadExpectedWithdrawals' offset (4 bytes)
	// Field #41 'PTCWindow' static (393216 bytes)
	size += 3134753
	{ // Dynamic field #7 'HistoricalRoots'
		size += int64(len(t.HistoricalRoots)) * 32
	}
	{ // Dynamic field #8 'Validators'
		size += int64(len(t.Validators)) * 121
	}
	{ // Dynamic field #9 'Balances'
		size += int64(len(t.Balances)) * 8
	}
	{ // Dynamic field #12 'PreviousEpochParticipation'
		size += int64(len(t.PreviousEpochParticipation))
	}
	{ // Dynamic field #13 'CurrentEpochParticipation'
		size += int64(len(t.CurrentEpochParticipation))
	}
	{ // Dynamic field #18 'InactivityScores'
		size += int64(len(t.InactivityScores)) * 8
	}
	{ // Dynamic field #24 'HistoricalSummaries'
		size += int64(len(t.HistoricalSummaries)) * 64
	}
	{ // Dynamic field #30 'PendingDeposits'
		size += int64(len(t.PendingDeposits)) * 192
	}
	{ // Dynamic field #31 'PendingPartialWithdrawals'
		size += int64(len(t.PendingPartialWithdrawals)) * 24
	}
	{ // Dynamic field #32 'PendingConsolidations'
		size += int64(len(t.PendingConsolidations)) * 16
	}
	{ // Dynamic field #34 'Builders'
		size += int64(len(t.Builders)) * 93
	}
	{ // Dynamic field #38 'BuilderPendingWithdrawals'
		size += int64(len(t.BuilderPendingWithdrawals)) * 36
	}
	{ // Dynamic field #39 'LatestExecutionPayloadBid'
		s1 := int64(t.LatestExecutionPayloadBid.SizeSSZ())
		if s1 < 0 {
			return -1
		}
		size += s1
	}
	{ // Dynamic field #40 'PayloadExpectedWithdrawals'
		size += int64(len(t.PayloadExpectedWithdrawals)) * 44
	}
	if uint64(size) > sszutils.MaxSszSize {
		return -1
	}
	return int(size)
}

// HashTreeRoot computes the SSZ hash tree root of the *BeaconState.
func (t *BeaconState) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *BeaconState using the given hash walker.
func (t *BeaconState) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(BeaconState)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'GenesisTime'
		hh.PutUint64(t.GenesisTime)
	}
	{ // Field #1 'GenesisValidatorsRoot'
		hh.PutBytes(t.GenesisValidatorsRoot[:32])
	}
	{ // Field #2 'Slot'
		hh.PutUint64(uint64(t.Slot))
	}
	{ // Field #3 'Fork'
		t := t.Fork
		if t == nil {
			t = new(phase0.Fork)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Fork")
		}
	}
	{ // Field #4 'LatestBlockHeader'
		t := t.LatestBlockHeader
		if t == nil {
			t = new(phase0.BeaconBlockHeader)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "LatestBlockHeader")
		}
	}
	{ // Field #5 'BlockRoots'
		t := t.BlockRoots
		vlen := len(t)
		if vlen > 8192 {
			return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 8192), "BlockRoots")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		var val1 *phase0.Root
		for idx1 := range 8192 {
			if idx1 < vlen {
				val1 = &t[idx1]
			} else if idx1 == vlen {
				val1 = new(phase0.Root)
			}
			hh.PutBytes(val1[:32])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.Merkleize(idx)
	}
	{ // Field #6 'StateRoots'
		t := t.StateRoots
		vlen := len(t)
		if vlen > 8192 {
			return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 8192), "StateRoots")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		var val2 *phase0.Root
		for idx1 := range 8192 {
			if idx1 < vlen {
				val2 = &t[idx1]
			} else if idx1 == vlen {
				val2 = new(phase0.Root)
			}
			hh.PutBytes(val2[:32])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.Merkleize(idx)
	}
	{ // Field #7 'HistoricalRoots'
		t := t.HistoricalRoots
		vlen := uint64(len(t))
		if vlen > 16777216 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 16777216), "HistoricalRoots")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range len(t) {
			hh.PutBytes(t[idx1][:32])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(16777216, vlen, 32))
	}
	// Inactive field #8
	hh.PutUint8(0)
	// Inactive field #9
	hh.PutUint8(0)
	// Inactive field #10
	hh.PutUint8(0)
	{ // Field #8 'Validators'
		t := t.Validators
		idx := hh.StartTree(sszutils.TreeTypeProgressive)
		vlen := uint64(len(t))
		for idx1 := range len(t) {
			t := t[idx1]
			if t == nil {
				t = new(phase0.Validator)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Validators[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeProgressiveWithMixin(idx, vlen)
	}
	{ // Field #9 'Balances'
		t := t.Balances
		idx := hh.StartTree(sszutils.TreeTypeProgressive | sszutils.TreeTypePacked)
		sszutils.HashUint64Slice(hh, t)
		vlen := uint64(len(t))
		hh.MerkleizeProgressiveWithMixin(idx, vlen)
	}
	{ // Field #10 'RANDAOMixes'
		t := t.RANDAOMixes
		vlen := len(t)
		if vlen > 65536 {
			return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 65536), "RANDAOMixes")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		var val3 *phase0.Root
		for idx1 := range 65536 {
			if idx1 < vlen {
				val3 = &t[idx1]
			} else if idx1 == vlen {
				val3 = new(phase0.Root)
			}
			hh.PutBytes(val3[:32])
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.Merkleize(idx)
	}
	{ // Field #11 'Slashings'
		t := t.Slashings
		vlen := len(t)
		if vlen > 8192 {
			return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 8192), "Slashings")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary | sszutils.TreeTypePacked)
		var val4, val4Empty phase0.Gwei
		for idx1 := range 8192 {
			if idx1 < vlen {
				val4 = t[idx1]
			} else if idx1 == vlen {
				val4 = val4Empty
			}
			hh.AppendUint64(uint64(val4))
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.Merkleize(idx)
	}
	{ // Field #12 'PreviousEpochParticipation'
		t := t.PreviousEpochParticipation
		idx := hh.StartTree(sszutils.TreeTypeProgressive | sszutils.TreeTypePacked)
		vlen := uint64(len(t))
		for idx1 := range len(t) {
			hh.AppendUint8(uint8(t[idx1]))
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeProgressiveWithMixin(idx, vlen)
	}
	{ // Field #13 'CurrentEpochParticipation'
		t := t.CurrentEpochParticipation
		idx := hh.StartTree(sszutils.TreeTypeProgressive | sszutils.TreeTypePacked)
		vlen := uint64(len(t))
		for idx1 := range len(t) {
			hh.AppendUint8(uint8(t[idx1]))
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeProgressiveWithMixin(idx, vlen)
	}
	{ // Field #14 'JustificationBits'
		vlen := len(t.JustificationBits)
		if vlen > 1 {
			return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 1), "JustificationBits")
		}
		val := t.JustificationBits[:vlen:vlen]
		if vlen < 1 {
			val = sszutils.AppendZeroPadding(val, (1-vlen)*1)
		}
		hh.PutBytes(val[:1])
	}
	{ // Field #15 'PreviousJustifiedCheckpoint'
		t := t.PreviousJustifiedCheckpoint
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "PreviousJustifiedCheckpoint")
		}
	}
	{ // Field #16 'CurrentJustifiedCheckpoint'
		t := t.CurrentJustifiedCheckpoint
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "CurrentJustifiedCheckpoint")
		}
	}
	{ // Field #17 'FinalizedCheckpoint'
		t := t.FinalizedCheckpoint
		if t == nil {
			t = new(phase0.Checkpoint)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "FinalizedCheckpoint")
		}
	}
	{ // Field #18 'InactivityScores'
		t := t.InactivityScores
		idx := hh.StartTree(sszutils.TreeTypeProgressive | sszutils.TreeTypePacked)
		sszutils.HashUint64Slice(hh, t)
		vlen := uint64(len(t))
		hh.MerkleizeProgressiveWithMixin(idx, vlen)
	}
	{ // Field #19 'CurrentSyncCommittee'
		t := t.CurrentSyncCommittee
		if t == nil {
			t = new(altair.SyncCommittee)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "CurrentSyncCommittee")
		}
	}
	{ // Field #20 'NextSyncCommittee'
		t := t.NextSyncCommittee
		if t == nil {
			t = new(altair.SyncCommittee)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "NextSyncCommittee")
		}
	}
	{ // Field #21 'LatestBlockHash'
		hh.PutBytes(t.LatestBlockHash[:32])
	}
	{ // Field #22 'NextWithdrawalIndex'
		hh.PutUint64(uint64(t.NextWithdrawalIndex))
	}
	{ // Field #23 'NextWithdrawalValidatorIndex'
		hh.PutUint64(uint64(t.NextWithdrawalValidatorIndex))
	}
	{ // Field #24 'HistoricalSummaries'
		t := t.HistoricalSummaries
		vlen := uint64(len(t))
		if vlen > 16777216 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, 16777216), "HistoricalSummaries")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range len(t) {
			t := t[idx1]
			if t == nil {
				t = new(capella.HistoricalSummary)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "HistoricalSummaries[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(16777216, vlen, 32))
	}
	// Inactive field #28
	hh.PutUint8(0)
	{ // Field #25 'DepositBalanceToConsume'
		hh.PutUint64(uint64(t.DepositBalanceToConsume))
	}
	{ // Field #26 'ExitBalanceToConsume'
		hh.PutUint64(uint64(t.ExitBalanceToConsume))
	}
	{ // Field #27 'EarliestExitEpoch'
		hh.PutUint64(uint64(t.EarliestExitEpoch))
	}
	{ // Field #28 'ConsolidationBalanceToConsume'
		hh.PutUint64(uint64(t.ConsolidationBalanceToConsume))
	}
	{ // Field #29 'EarliestConsolidationEpoch'
		hh.PutUint64(uint64(t.EarliestConsolidationEpoch))
	}
	{ // Field #30 'PendingDeposits'
		t := t.PendingDeposits
		idx := hh.StartTree(sszutils.TreeTypeProgressive)
		vlen := uint64(len(t))
		for idx1 := range len(t) {
			t := t[idx1]
			if t == nil {
				t = new(electra.PendingDeposit)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "PendingDeposits[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeProgressiveWithMixin(idx, vlen)
	}
	{ // Field #31 'PendingPartialWithdrawals'
		t := t.PendingPartialWithdrawals
		idx := hh.StartTree(sszutils.TreeTypeProgressive)
		vlen := uint64(len(t))
		for idx1 := range len(t) {
			t := t[idx1]
			if t == nil {
				t = new(electra.PendingPartialWithdrawal)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "PendingPartialWithdrawals[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeProgressiveWithMixin(idx, vlen)
	}
	{ // Field #32 'PendingConsolidations'
		t := t.PendingConsolidations
		idx := hh.StartTree(sszutils.TreeTypeProgressive)
		vlen := uint64(len(t))
		for idx1 := range len(t) {
			t := t[idx1]
			if t == nil {
				t = new(electra.PendingConsolidation)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "PendingConsolidations[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeProgressiveWithMixin(idx, vlen)
	}
	{ // Field #33 'ProposerLookahead'
		t := t.ProposerLookahead
		vlen := len(t)
		if vlen > 64 {
			return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 64), "ProposerLookahead")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary | sszutils.TreeTypePacked)
		var val5, val5Empty phase0.ValidatorIndex
		for idx1 := range 64 {
			if idx1 < vlen {
				val5 = t[idx1]
			} else if idx1 == vlen {
				val5 = val5Empty
			}
			hh.AppendUint64(uint64(val5))
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.Merkleize(idx)
	}
	{ // Field #34 'Builders'
		t := t.Builders
		idx := hh.StartTree(sszutils.TreeTypeProgressive)
		vlen := uint64(len(t))
		for idx1 := range len(t) {
			t := t[idx1]
			if t == nil {
				t = new(gloas.Builder)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Builders[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeProgressiveWithMixin(idx, vlen)
	}
	{ // Field #35 'NextWithdrawalBuilderIndex'
		hh.PutUint64(uint64(t.NextWithdrawalBuilderIndex))
	}
	{ // Field #36 'ExecutionPayloadAvailability'
		vlen := len(t.ExecutionPayloadAvailability)
		if vlen > 1024 {
			return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 1024), "ExecutionPayloadAvailability")
		}
		val := t.ExecutionPayloadAvailability[:vlen:vlen]
		if vlen < 1024 {
			val = sszutils.AppendZeroPadding(val, (1024-vlen)*1)
		}
		hh.PutBytes(val[:1024])
	}
	{ // Field #37 'BuilderPendingPayments'
		t := t.BuilderPendingPayments
		vlen := len(t)
		if vlen > 64 {
			return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 64), "BuilderPendingPayments")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		var val6 *gloas.BuilderPendingPayment
		for idx1 := range 64 {
			if idx1 < vlen {
				val6 = t[idx1]
			} else if idx1 == vlen {
				val6 = new(gloas.BuilderPendingPayment)
			}
			if val6 == nil {
				val6 = new(gloas.BuilderPendingPayment)
			}
			if err := val6.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "BuilderPendingPayments[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.Merkleize(idx)
	}
	{ // Field #38 'BuilderPendingWithdrawals'
		t := t.BuilderPendingWithdrawals
		idx := hh.StartTree(sszutils.TreeTypeProgressive)
		vlen := uint64(len(t))
		for idx1 := range len(t) {
			t := t[idx1]
			if t == nil {
				t = new(gloas.BuilderPendingWithdrawal)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "BuilderPendingWithdrawals[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeProgressiveWithMixin(idx, vlen)
	}
	{ // Field #39 'LatestExecutionPayloadBid'
		t := t.LatestExecutionPayloadBid
		if t == nil {
			t = new(ExecutionPayloadBid)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "LatestExecutionPayloadBid")
		}
	}
	{ // Field #40 'PayloadExpectedWithdrawals'
		t := t.PayloadExpectedWithdrawals
		idx := hh.StartTree(sszutils.TreeTypeProgressive)
		vlen := uint64(len(t))
		for idx1 := range len(t) {
			t := t[idx1]
			if t == nil {
				t = new(capella.Withdrawal)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "PayloadExpectedWithdrawals[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeProgressiveWithMixin(idx, vlen)
	}
	{ // Field #41 'PTCWindow'
		t := t.PTCWindow
		vlen := len(t)
		if vlen > 96 {
			return sszutils.ErrorWithPath(sszutils.ErrVectorLengthFn(vlen, 96), "PTCWindow")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		var val7, val7Empty []phase0.ValidatorIndex
		for idx1 := range 96 {
			if idx1 < vlen {
				val7 = t[idx1]
			} else if idx1 == vlen {
				val7 = val7Empty
			}
			vlen := len(val7)
			if vlen > 512 {
				return sszutils.ErrorWithPathf(sszutils.ErrVectorLengthFn(vlen, 512), "PTCWindow[%d]", idx1)
			}
			idx := hh.StartTree(sszutils.TreeTypeBinary | sszutils.TreeTypePacked)
			var val8, val8Empty phase0.ValidatorIndex
			for idx2 := range 512 {
				if idx2 < vlen {
					val8 = val7[idx2]
				} else if idx2 == vlen {
					val8 = val8Empty
				}
				hh.AppendUint64(uint64(val8))
				if (idx2+1)%256 == 0 {
					hh.Collapse()
				}
			}
			hh.Merkleize(idx)
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.Merkleize(idx)
	}
	hh.MerkleizeProgressiveWithActiveFields(idx, []byte{0xff, 0xf8, 0xff, 0xef, 0xff, 0x3f})
	return nil
}
