// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: bec6ced012a06f8bf2adb2387397c37535f2d7a10dbd554cba9a5f651b8c6d10
// Version: v1.4.0-pre.2 (https://github.com/pk910/dynamic-ssz)
package heze

import (
	"encoding/binary"
	"math"

	"github.com/ethpandaops/go-eth2-client/spec/phase0"
	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[InclusionList](`ssz-static:"false"`)

// MarshalSSZ marshals the *InclusionList to SSZ-encoded bytes.
func (t *InclusionList) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *InclusionList to SSZ-encoded bytes, appending to the provided buffer.
func (t *InclusionList) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(InclusionList)
	}
	dstlen := len(dst)
	{ // Static Field #0 'Slot'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.Slot))
	}
	{ // Static Field #1 'ValidatorIndex'
		dst = binary.LittleEndian.AppendUint64(dst, uint64(t.ValidatorIndex))
	}
	{ // Static Field #2 'DependentRoot'
		dst = append(dst, t.DependentRoot[:32]...)
	}
	// Offset Field #3 'Transactions'
	dst = append(dst, 0, 0, 0, 0)
	{ // Dynamic Field #3 'Transactions'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+48:], uint32(off))
		}
		t := t.Transactions
		dstlen := len(dst)
		vlen := len(t)
		dst = sszutils.AppendZeroPadding(dst, vlen*4)
		for idx1 := range vlen {
			if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
				return nil, sszutils.ErrOffsetOverflowFn(off)
			} else {
				binary.LittleEndian.PutUint32(dst[dstlen+(idx1*4):], uint32(off))
			}
			t := t[idx1]
			dst = append(dst, t[:]...)
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *InclusionList from SSZ-encoded bytes.
func (t *InclusionList) UnmarshalSSZ(buf []byte) (err error) {
	buflen := uint64(len(buf))
	if buflen < 52 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 52)
	}
	{ // Field #0 'Slot' (static)
		buf := buf[0:8]
		t.Slot = phase0.Slot(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #1 'ValidatorIndex' (static)
		buf := buf[8:16]
		t.ValidatorIndex = phase0.ValidatorIndex(binary.LittleEndian.Uint64(buf))
	}
	{ // Field #2 'DependentRoot' (static)
		buf := buf[16:48]
		copy(t.DependentRoot[:], buf)
	}
	// Field #3 'Transactions' (offset)
	offset3 := binary.LittleEndian.Uint32(buf[48:52])
	if offset3 != 52 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset3, 52), "Transactions:o")
	}
	{ // Field #3 'Transactions' (dynamic)
		buf := buf[offset3:]
		val1 := t.Transactions
		startOffset := int(0)
		if len(buf) != 0 {
			if len(buf) < 4 {
				return sszutils.ErrorWithPath(sszutils.ErrListOffsetsEOFFn(len(buf), 4), "Transactions")
			}
			firstOffset := binary.LittleEndian.Uint32(buf[0:4])
			if firstOffset%4 != 0 || uint64(firstOffset) > uint64(len(buf)) || firstOffset == 0 {
				return sszutils.ErrorWithPath(sszutils.ErrInvalidListStartOffsetFn(firstOffset, len(buf)), "Transactions")
			}
			startOffset = int(firstOffset)
		}
		itemCount := startOffset / 4
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			var endOffset int
			if idx1 < itemCount-1 {
				endOffset = int(binary.LittleEndian.Uint32(buf[(idx1+1)*4 : (idx1+2)*4]))
			} else {
				endOffset = len(buf)
			}
			if endOffset < startOffset || endOffset > len(buf) {
				return sszutils.ErrorWithPathf(sszutils.ErrElementOffsetOutOfRangeFn(endOffset, startOffset, len(buf)), "Transactions[%d]", idx1)
			}
			buf := buf[startOffset:endOffset]
			startOffset = endOffset
			val2 := val1[idx1]
			val2 = sszutils.ExpandSlice(val2, len(buf))
			copy(val2[:], buf)
			val1[idx1] = val2
		}
		t.Transactions = val1
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *InclusionList.
func (t *InclusionList) SizeSSZ() (size int) {
	if t == nil {
		t = new(InclusionList)
	}
	// Field #0 'Slot' static (8 bytes)
	// Field #1 'ValidatorIndex' static (8 bytes)
	// Field #2 'DependentRoot' static (32 bytes)
	// Field #3 'Transactions' offset (4 bytes)
	size += 52
	{ // Dynamic field #3 'Transactions'
		t2 := t.Transactions
		vlen := len(t2)
		size += vlen * 4 // Offsets
		for i1 := range vlen {
			size += len(t2[i1])
		}
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *InclusionList.
func (t *InclusionList) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *InclusionList using the given hash walker.
func (t *InclusionList) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(InclusionList)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Slot'
		hh.PutUint64(uint64(t.Slot))
	}
	{ // Field #1 'ValidatorIndex'
		hh.PutUint64(uint64(t.ValidatorIndex))
	}
	{ // Field #2 'DependentRoot'
		hh.PutBytes(t.DependentRoot[:32])
	}
	{ // Field #3 'Transactions'
		t := t.Transactions
		idx := hh.StartTree(sszutils.TreeTypeProgressive)
		vlen := uint64(len(t))
		for idx1 := range len(t) {
			t := t[idx1]
			idx := hh.StartTree(sszutils.TreeTypeProgressive)
			hh.AppendBytes32(t[:])
			vlen := uint64(len(t))
			hh.MerkleizeProgressiveWithMixin(idx, vlen)
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeProgressiveWithMixin(idx, vlen)
	}
	hh.Merkleize(idx)
	return nil
}
