// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: fe6f97e2bd3dd6ef50c3cf8e0f0accbf7635815b40ae125350b6c01113d9aa29
// Version: v1.4.0-pre.2 (https://github.com/pk910/dynamic-ssz)
package heze

import (
	"encoding/binary"
	"math"

	dynssz "github.com/pk910/dynamic-ssz"
	"github.com/pk910/dynamic-ssz/hasher"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[SignedInclusionList](`ssz-static:"false"`)

// MarshalSSZ marshals the *SignedInclusionList to SSZ-encoded bytes.
func (t *SignedInclusionList) MarshalSSZ() ([]byte, error) {
	return dynssz.GetGlobalDynSsz().MarshalSSZ(t)
}

// MarshalSSZTo marshals the *SignedInclusionList to SSZ-encoded bytes, appending to the provided buffer.
func (t *SignedInclusionList) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedInclusionList)
	}
	dstlen := len(dst)
	// Offset Field #0 'Message'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'Message'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen:], uint32(off))
		}
		t := t.Message
		if t == nil {
			t = new(InclusionList)
		}
		if dst, err = t.MarshalSSZTo(dst); err != nil {
			return nil, sszutils.ErrorWithPath(err, "Message")
		}
	}
	return dst, nil
}

// UnmarshalSSZ unmarshals the *SignedInclusionList from SSZ-encoded bytes.
func (t *SignedInclusionList) UnmarshalSSZ(buf []byte) (err error) {
	buflen := uint64(len(buf))
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	// Field #0 'Message' (offset)
	offset0 := binary.LittleEndian.Uint32(buf[0:4])
	if offset0 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 100), "Message:o")
	}
	{ // Field #1 'Signature' (static)
		buf := buf[4:100]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'Message' (dynamic)
		buf := buf[offset0:]
		if t.Message == nil {
			t.Message = new(InclusionList)
		}
		if err = t.Message.UnmarshalSSZ(buf); err != nil {
			return sszutils.ErrorWithPath(err, "Message")
		}
	}
	return nil
}

// SizeSSZ returns the SSZ encoded size of the *SignedInclusionList.
func (t *SignedInclusionList) SizeSSZ() (size int) {
	if t == nil {
		t = new(SignedInclusionList)
	}
	// Field #0 'Message' offset (4 bytes)
	// Field #1 'Signature' static (96 bytes)
	size += 100
	{ // Dynamic field #0 'Message'
		size += t.Message.SizeSSZ()
	}
	return size
}

// HashTreeRoot computes the SSZ hash tree root of the *SignedInclusionList.
func (t *SignedInclusionList) HashTreeRoot() (root [32]byte, err error) {
	err = hasher.WithDefaultHasher(func(hh sszutils.HashWalker) (err error) {
		err = t.HashTreeRootWith(hh)
		if err == nil {
			root, err = hh.HashRoot()
		}
		return
	})
	return
}

// HashTreeRootWith computes the SSZ hash tree root of the *SignedInclusionList using the given hash walker.
func (t *SignedInclusionList) HashTreeRootWith(hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedInclusionList)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(InclusionList)
		}
		if err := t.HashTreeRootWith(hh); err != nil {
			return sszutils.ErrorWithPath(err, "Message")
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}
