// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: c13fff471715186308d871a4823ac3296092d35a9b694bd3f1685e2a0f1b4934
// Version: v1.4.0-pre.2 (https://github.com/pk910/dynamic-ssz)
package all

import (
	"encoding/binary"
	"math"

	"github.com/ethpandaops/go-eth2-client/spec/electra"
	"github.com/ethpandaops/go-eth2-client/spec/gloas"
	"github.com/ethpandaops/go-eth2-client/spec/phase0"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[*phase0.AttesterSlashing](`ssz-static:"false"`)
var _ = sszutils.Annotate[*electra.AttesterSlashing](`ssz-static:"false"`)
var _ = sszutils.Annotate[*gloas.AttesterSlashing](`ssz-static:"false"`)

func (t *AttesterSlashing) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *phase0.AttesterSlashing:
		return t.marshalSSZView_AttesterSlashing
	case *electra.AttesterSlashing:
		return t.marshalSSZView_AttesterSlashing_0
	case *gloas.AttesterSlashing:
		return t.marshalSSZView_AttesterSlashing_1
	}
	return nil
}
func (t *AttesterSlashing) marshalSSZView_AttesterSlashing(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(AttesterSlashing)
	}
	dstlen := len(dst)
	// Offset Field #0 'Attestation1'
	// Offset Field #1 'Attestation2'
	dst = append(dst, 0, 0, 0, 0, 0, 0, 0, 0)
	{ // Dynamic Field #0 'Attestation1'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen:], uint32(off))
		}
		t := t.Attestation1
		if t == nil {
			t = new(IndexedAttestation)
		}
		if viewFn := t.MarshalSSZDynView((*phase0.IndexedAttestation)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	{ // Dynamic Field #1 'Attestation2'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(off))
		}
		t := t.Attestation2
		if t == nil {
			t = new(IndexedAttestation)
		}
		if viewFn := t.MarshalSSZDynView((*phase0.IndexedAttestation)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *AttesterSlashing) marshalSSZView_AttesterSlashing_0(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(AttesterSlashing)
	}
	dstlen := len(dst)
	// Offset Field #0 'Attestation1'
	// Offset Field #1 'Attestation2'
	dst = append(dst, 0, 0, 0, 0, 0, 0, 0, 0)
	{ // Dynamic Field #0 'Attestation1'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen:], uint32(off))
		}
		t := t.Attestation1
		if t == nil {
			t = new(IndexedAttestation)
		}
		if viewFn := t.MarshalSSZDynView((*electra.IndexedAttestation)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	{ // Dynamic Field #1 'Attestation2'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(off))
		}
		t := t.Attestation2
		if t == nil {
			t = new(IndexedAttestation)
		}
		if viewFn := t.MarshalSSZDynView((*electra.IndexedAttestation)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *AttesterSlashing) marshalSSZView_AttesterSlashing_1(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(AttesterSlashing)
	}
	dstlen := len(dst)
	// Offset Field #0 'Attestation1'
	// Offset Field #1 'Attestation2'
	dst = append(dst, 0, 0, 0, 0, 0, 0, 0, 0)
	{ // Dynamic Field #0 'Attestation1'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen:], uint32(off))
		}
		t := t.Attestation1
		if t == nil {
			t = new(IndexedAttestation)
		}
		if viewFn := t.MarshalSSZDynView((*gloas.IndexedAttestation)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	{ // Dynamic Field #1 'Attestation2'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(off))
		}
		t := t.Attestation2
		if t == nil {
			t = new(IndexedAttestation)
		}
		if viewFn := t.MarshalSSZDynView((*gloas.IndexedAttestation)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *AttesterSlashing) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *phase0.AttesterSlashing:
		return t.unmarshalSSZView_AttesterSlashing
	case *electra.AttesterSlashing:
		return t.unmarshalSSZView_AttesterSlashing_0
	case *gloas.AttesterSlashing:
		return t.unmarshalSSZView_AttesterSlashing_1
	}
	return nil
}
func (t *AttesterSlashing) unmarshalSSZView_AttesterSlashing(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := uint64(len(buf))
	if buflen < 8 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 8)
	}
	maxOffset := uint32(sszutils.Min(buflen, math.MaxUint32))
	// Field #0 'Attestation1' (offset)
	offset0 := binary.LittleEndian.Uint32(buf[0:4])
	if offset0 != 8 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 8), "Attestation1:o")
	}
	// Field #1 'Attestation2' (offset)
	offset1 := binary.LittleEndian.Uint32(buf[4:8])
	if offset1 < offset0 || offset1 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "Attestation2:o")
	}
	{ // Field #0 'Attestation1' (dynamic)
		buf := buf[offset0:offset1]
		if t.Attestation1 == nil {
			t.Attestation1 = new(IndexedAttestation)
		}
		if viewFn := t.Attestation1.UnmarshalSSZDynView((*phase0.IndexedAttestation)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'Attestation2' (dynamic)
		buf := buf[offset1:]
		if t.Attestation2 == nil {
			t.Attestation2 = new(IndexedAttestation)
		}
		if viewFn := t.Attestation2.UnmarshalSSZDynView((*phase0.IndexedAttestation)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *AttesterSlashing) unmarshalSSZView_AttesterSlashing_0(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := uint64(len(buf))
	if buflen < 8 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 8)
	}
	maxOffset := uint32(sszutils.Min(buflen, math.MaxUint32))
	// Field #0 'Attestation1' (offset)
	offset0 := binary.LittleEndian.Uint32(buf[0:4])
	if offset0 != 8 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 8), "Attestation1:o")
	}
	// Field #1 'Attestation2' (offset)
	offset1 := binary.LittleEndian.Uint32(buf[4:8])
	if offset1 < offset0 || offset1 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "Attestation2:o")
	}
	{ // Field #0 'Attestation1' (dynamic)
		buf := buf[offset0:offset1]
		if t.Attestation1 == nil {
			t.Attestation1 = new(IndexedAttestation)
		}
		if viewFn := t.Attestation1.UnmarshalSSZDynView((*electra.IndexedAttestation)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'Attestation2' (dynamic)
		buf := buf[offset1:]
		if t.Attestation2 == nil {
			t.Attestation2 = new(IndexedAttestation)
		}
		if viewFn := t.Attestation2.UnmarshalSSZDynView((*electra.IndexedAttestation)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *AttesterSlashing) unmarshalSSZView_AttesterSlashing_1(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := uint64(len(buf))
	if buflen < 8 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 8)
	}
	maxOffset := uint32(sszutils.Min(buflen, math.MaxUint32))
	// Field #0 'Attestation1' (offset)
	offset0 := binary.LittleEndian.Uint32(buf[0:4])
	if offset0 != 8 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 8), "Attestation1:o")
	}
	// Field #1 'Attestation2' (offset)
	offset1 := binary.LittleEndian.Uint32(buf[4:8])
	if offset1 < offset0 || offset1 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "Attestation2:o")
	}
	{ // Field #0 'Attestation1' (dynamic)
		buf := buf[offset0:offset1]
		if t.Attestation1 == nil {
			t.Attestation1 = new(IndexedAttestation)
		}
		if viewFn := t.Attestation1.UnmarshalSSZDynView((*gloas.IndexedAttestation)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'Attestation2' (dynamic)
		buf := buf[offset1:]
		if t.Attestation2 == nil {
			t.Attestation2 = new(IndexedAttestation)
		}
		if viewFn := t.Attestation2.UnmarshalSSZDynView((*gloas.IndexedAttestation)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *AttesterSlashing) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *phase0.AttesterSlashing:
		return t.sizeSSZView_AttesterSlashing
	case *electra.AttesterSlashing:
		return t.sizeSSZView_AttesterSlashing_0
	case *gloas.AttesterSlashing:
		return t.sizeSSZView_AttesterSlashing_1
	}
	return nil
}
func (t *AttesterSlashing) sizeSSZView_AttesterSlashing(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(AttesterSlashing)
	}
	// Field #0 'Attestation1' offset (4 bytes)
	// Field #1 'Attestation2' offset (4 bytes)
	size += 8
	{ // Dynamic field #0 'Attestation1'
		if viewFn := t.Attestation1.SizeSSZDynView((*phase0.IndexedAttestation)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	{ // Dynamic field #1 'Attestation2'
		if viewFn := t.Attestation2.SizeSSZDynView((*phase0.IndexedAttestation)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *AttesterSlashing) sizeSSZView_AttesterSlashing_0(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(AttesterSlashing)
	}
	// Field #0 'Attestation1' offset (4 bytes)
	// Field #1 'Attestation2' offset (4 bytes)
	size += 8
	{ // Dynamic field #0 'Attestation1'
		if viewFn := t.Attestation1.SizeSSZDynView((*electra.IndexedAttestation)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	{ // Dynamic field #1 'Attestation2'
		if viewFn := t.Attestation2.SizeSSZDynView((*electra.IndexedAttestation)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *AttesterSlashing) sizeSSZView_AttesterSlashing_1(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(AttesterSlashing)
	}
	// Field #0 'Attestation1' offset (4 bytes)
	// Field #1 'Attestation2' offset (4 bytes)
	size += 8
	{ // Dynamic field #0 'Attestation1'
		if viewFn := t.Attestation1.SizeSSZDynView((*gloas.IndexedAttestation)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	{ // Dynamic field #1 'Attestation2'
		if viewFn := t.Attestation2.SizeSSZDynView((*gloas.IndexedAttestation)(nil)); viewFn != nil {
			size += viewFn(ds)
		}
	}
	return size
}

func (t *AttesterSlashing) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *phase0.AttesterSlashing:
		return t.hashTreeRootView_AttesterSlashing
	case *electra.AttesterSlashing:
		return t.hashTreeRootView_AttesterSlashing_0
	case *gloas.AttesterSlashing:
		return t.hashTreeRootView_AttesterSlashing_1
	}
	return nil
}
func (t *AttesterSlashing) hashTreeRootView_AttesterSlashing(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(AttesterSlashing)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Attestation1'
		t := t.Attestation1
		if t == nil {
			t = new(IndexedAttestation)
		}
		if viewFn := t.HashTreeRootWithDynView((*phase0.IndexedAttestation)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'Attestation2'
		t := t.Attestation2
		if t == nil {
			t = new(IndexedAttestation)
		}
		if viewFn := t.HashTreeRootWithDynView((*phase0.IndexedAttestation)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	hh.Merkleize(idx)
	return nil
}

func (t *AttesterSlashing) hashTreeRootView_AttesterSlashing_0(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(AttesterSlashing)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Attestation1'
		t := t.Attestation1
		if t == nil {
			t = new(IndexedAttestation)
		}
		if viewFn := t.HashTreeRootWithDynView((*electra.IndexedAttestation)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'Attestation2'
		t := t.Attestation2
		if t == nil {
			t = new(IndexedAttestation)
		}
		if viewFn := t.HashTreeRootWithDynView((*electra.IndexedAttestation)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	hh.Merkleize(idx)
	return nil
}

func (t *AttesterSlashing) hashTreeRootView_AttesterSlashing_1(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(AttesterSlashing)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Attestation1'
		t := t.Attestation1
		if t == nil {
			t = new(IndexedAttestation)
		}
		if viewFn := t.HashTreeRootWithDynView((*gloas.IndexedAttestation)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'Attestation2'
		t := t.Attestation2
		if t == nil {
			t = new(IndexedAttestation)
		}
		if viewFn := t.HashTreeRootWithDynView((*gloas.IndexedAttestation)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	hh.Merkleize(idx)
	return nil
}
