// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 8a5937db190e2bcbaa8cf9159b6cd7d0731f2363cd97eb57d5fc4996e2348e5b
// Version: v1.4.0-pre.2 (https://github.com/pk910/dynamic-ssz)
package all

import (
	"encoding/binary"
	"math"

	"github.com/ethpandaops/go-eth2-client/spec/electra"
	"github.com/ethpandaops/go-eth2-client/spec/gloas"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[*electra.ExecutionRequests](`ssz-static:"false"`)
var _ = sszutils.Annotate[*gloas.ExecutionRequests](`ssz-static:"false"`)

func (t *ExecutionRequests) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *electra.ExecutionRequests:
		return t.marshalSSZView_ExecutionRequests
	case *gloas.ExecutionRequests:
		return t.marshalSSZView_ExecutionRequests_0
	}
	return nil
}
func (t *ExecutionRequests) marshalSSZView_ExecutionRequests(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_DEPOSIT_REQUESTS_PER_PAYLOAD", 8192)
	if err != nil {
		return dst, err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWAL_REQUESTS_PER_PAYLOAD", 16)
	if err != nil {
		return dst, err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_CONSOLIDATION_REQUESTS_PER_PAYLOAD", 2)
	if err != nil {
		return dst, err
	}
	zeroBytes := sszutils.ZeroBytes()
	if t == nil {
		t = new(ExecutionRequests)
	}
	dstlen := len(dst)
	// Offset Field #0 'Deposits'
	// Offset Field #1 'Withdrawals'
	// Offset Field #2 'Consolidations'
	dst = append(dst, zeroBytes[:12]...)
	{ // Dynamic Field #0 'Deposits'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen:], uint32(off))
		}
		t := t.Deposits
		vlen := len(t)
		if uint64(vlen) > expr0 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "Deposits")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(electra.DepositRequest)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Deposits[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #1 'Withdrawals'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(off))
		}
		t := t.Withdrawals
		vlen := len(t)
		if uint64(vlen) > expr1 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr1), "Withdrawals")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(electra.WithdrawalRequest)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #2 'Consolidations'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+8:], uint32(off))
		}
		t := t.Consolidations
		vlen := len(t)
		if uint64(vlen) > expr2 {
			return nil, sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr2), "Consolidations")
		}
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(electra.ConsolidationRequest)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Consolidations[%d]", idx1)
			}
		}
	}
	return dst, nil
}

func (t *ExecutionRequests) marshalSSZView_ExecutionRequests_0(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	zeroBytes := sszutils.ZeroBytes()
	if t == nil {
		t = new(ExecutionRequests)
	}
	dstlen := len(dst)
	// Offset Field #0 'Deposits'
	// Offset Field #1 'Withdrawals'
	// Offset Field #2 'Consolidations'
	// Offset Field #3 'BuilderDeposits'
	// Offset Field #4 'BuilderExits'
	dst = append(dst, zeroBytes[:20]...)
	{ // Dynamic Field #0 'Deposits'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen:], uint32(off))
		}
		t := t.Deposits
		vlen := len(t)
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(electra.DepositRequest)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Deposits[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #1 'Withdrawals'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+4:], uint32(off))
		}
		t := t.Withdrawals
		vlen := len(t)
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(electra.WithdrawalRequest)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #2 'Consolidations'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+8:], uint32(off))
		}
		t := t.Consolidations
		vlen := len(t)
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(electra.ConsolidationRequest)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "Consolidations[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #3 'BuilderDeposits'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+12:], uint32(off))
		}
		t := t.BuilderDeposits
		vlen := len(t)
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(gloas.BuilderDepositRequest)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "BuilderDeposits[%d]", idx1)
			}
		}
	}
	{ // Dynamic Field #4 'BuilderExits'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen+16:], uint32(off))
		}
		t := t.BuilderExits
		vlen := len(t)
		for idx1 := range vlen {
			t := t[idx1]
			if t == nil {
				t = new(gloas.BuilderExitRequest)
			}
			if dst, err = t.MarshalSSZTo(dst); err != nil {
				return nil, sszutils.ErrorWithPathf(err, "BuilderExits[%d]", idx1)
			}
		}
	}
	return dst, nil
}

func (t *ExecutionRequests) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *electra.ExecutionRequests:
		return t.unmarshalSSZView_ExecutionRequests
	case *gloas.ExecutionRequests:
		return t.unmarshalSSZView_ExecutionRequests_0
	}
	return nil
}
func (t *ExecutionRequests) unmarshalSSZView_ExecutionRequests(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_DEPOSIT_REQUESTS_PER_PAYLOAD", 8192)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWAL_REQUESTS_PER_PAYLOAD", 16)
	if err != nil {
		return err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_CONSOLIDATION_REQUESTS_PER_PAYLOAD", 2)
	if err != nil {
		return err
	}
	buflen := uint64(len(buf))
	if buflen < 12 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 12)
	}
	maxOffset := uint32(sszutils.Min(buflen, math.MaxUint32))
	// Field #0 'Deposits' (offset)
	offset0 := binary.LittleEndian.Uint32(buf[0:4])
	if offset0 != 12 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 12), "Deposits:o")
	}
	// Field #1 'Withdrawals' (offset)
	offset1 := binary.LittleEndian.Uint32(buf[4:8])
	if offset1 < offset0 || offset1 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "Withdrawals:o")
	}
	// Field #2 'Consolidations' (offset)
	offset2 := binary.LittleEndian.Uint32(buf[8:12])
	if offset2 < offset1 || offset2 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset2, offset1, buflen), "Consolidations:o")
	}
	{ // Field #0 'Deposits' (dynamic)
		buf := buf[offset0:offset1]
		val1 := t.Deposits
		itemCount := len(buf) / 192
		if len(buf)%192 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 192), "Deposits")
		}
		if uint64(itemCount) > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, expr0), "Deposits")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			if val1[idx1] == nil {
				val1[idx1] = new(electra.DepositRequest)
			}
			buf := buf[192*idx1 : 192*(idx1+1)]
			if err = val1[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Deposits[%d]", idx1)
			}
		}
		t.Deposits = val1
	}
	{ // Field #1 'Withdrawals' (dynamic)
		buf := buf[offset1:offset2]
		val2 := t.Withdrawals
		itemCount := len(buf) / 76
		if len(buf)%76 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 76), "Withdrawals")
		}
		if uint64(itemCount) > expr1 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, expr1), "Withdrawals")
		}
		val2 = sszutils.ExpandSlice(val2, itemCount)
		for idx1 := range itemCount {
			if val2[idx1] == nil {
				val2[idx1] = new(electra.WithdrawalRequest)
			}
			buf := buf[76*idx1 : 76*(idx1+1)]
			if err = val2[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
		}
		t.Withdrawals = val2
	}
	{ // Field #2 'Consolidations' (dynamic)
		buf := buf[offset2:]
		val3 := t.Consolidations
		itemCount := len(buf) / 116
		if len(buf)%116 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 116), "Consolidations")
		}
		if uint64(itemCount) > expr2 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(itemCount, expr2), "Consolidations")
		}
		val3 = sszutils.ExpandSlice(val3, itemCount)
		for idx1 := range itemCount {
			if val3[idx1] == nil {
				val3[idx1] = new(electra.ConsolidationRequest)
			}
			buf := buf[116*idx1 : 116*(idx1+1)]
			if err = val3[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Consolidations[%d]", idx1)
			}
		}
		t.Consolidations = val3
	}
	return nil
}

func (t *ExecutionRequests) unmarshalSSZView_ExecutionRequests_0(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := uint64(len(buf))
	if buflen < 20 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 20)
	}
	maxOffset := uint32(sszutils.Min(buflen, math.MaxUint32))
	// Field #0 'Deposits' (offset)
	offset0 := binary.LittleEndian.Uint32(buf[0:4])
	if offset0 != 20 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 20), "Deposits:o")
	}
	// Field #1 'Withdrawals' (offset)
	offset1 := binary.LittleEndian.Uint32(buf[4:8])
	if offset1 < offset0 || offset1 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset1, offset0, buflen), "Withdrawals:o")
	}
	// Field #2 'Consolidations' (offset)
	offset2 := binary.LittleEndian.Uint32(buf[8:12])
	if offset2 < offset1 || offset2 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset2, offset1, buflen), "Consolidations:o")
	}
	// Field #3 'BuilderDeposits' (offset)
	offset3 := binary.LittleEndian.Uint32(buf[12:16])
	if offset3 < offset2 || offset3 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset3, offset2, buflen), "BuilderDeposits:o")
	}
	// Field #4 'BuilderExits' (offset)
	offset4 := binary.LittleEndian.Uint32(buf[16:20])
	if offset4 < offset3 || offset4 > maxOffset {
		return sszutils.ErrorWithPath(sszutils.ErrOffsetOutOfRangeFn(offset4, offset3, buflen), "BuilderExits:o")
	}
	{ // Field #0 'Deposits' (dynamic)
		buf := buf[offset0:offset1]
		val1 := t.Deposits
		itemCount := len(buf) / 192
		if len(buf)%192 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 192), "Deposits")
		}
		val1 = sszutils.ExpandSlice(val1, itemCount)
		for idx1 := range itemCount {
			if val1[idx1] == nil {
				val1[idx1] = new(electra.DepositRequest)
			}
			buf := buf[192*idx1 : 192*(idx1+1)]
			if err = val1[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Deposits[%d]", idx1)
			}
		}
		t.Deposits = val1
	}
	{ // Field #1 'Withdrawals' (dynamic)
		buf := buf[offset1:offset2]
		val2 := t.Withdrawals
		itemCount := len(buf) / 76
		if len(buf)%76 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 76), "Withdrawals")
		}
		val2 = sszutils.ExpandSlice(val2, itemCount)
		for idx1 := range itemCount {
			if val2[idx1] == nil {
				val2[idx1] = new(electra.WithdrawalRequest)
			}
			buf := buf[76*idx1 : 76*(idx1+1)]
			if err = val2[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
		}
		t.Withdrawals = val2
	}
	{ // Field #2 'Consolidations' (dynamic)
		buf := buf[offset2:offset3]
		val3 := t.Consolidations
		itemCount := len(buf) / 116
		if len(buf)%116 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 116), "Consolidations")
		}
		val3 = sszutils.ExpandSlice(val3, itemCount)
		for idx1 := range itemCount {
			if val3[idx1] == nil {
				val3[idx1] = new(electra.ConsolidationRequest)
			}
			buf := buf[116*idx1 : 116*(idx1+1)]
			if err = val3[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "Consolidations[%d]", idx1)
			}
		}
		t.Consolidations = val3
	}
	{ // Field #3 'BuilderDeposits' (dynamic)
		buf := buf[offset3:offset4]
		val4 := t.BuilderDeposits
		itemCount := len(buf) / 184
		if len(buf)%184 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 184), "BuilderDeposits")
		}
		val4 = sszutils.ExpandSlice(val4, itemCount)
		for idx1 := range itemCount {
			if val4[idx1] == nil {
				val4[idx1] = new(gloas.BuilderDepositRequest)
			}
			buf := buf[184*idx1 : 184*(idx1+1)]
			if err = val4[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "BuilderDeposits[%d]", idx1)
			}
		}
		t.BuilderDeposits = val4
	}
	{ // Field #4 'BuilderExits' (dynamic)
		buf := buf[offset4:]
		val5 := t.BuilderExits
		itemCount := len(buf) / 68
		if len(buf)%68 != 0 {
			return sszutils.ErrorWithPath(sszutils.ErrListNotAlignedFn(len(buf), 68), "BuilderExits")
		}
		val5 = sszutils.ExpandSlice(val5, itemCount)
		for idx1 := range itemCount {
			if val5[idx1] == nil {
				val5[idx1] = new(gloas.BuilderExitRequest)
			}
			buf := buf[68*idx1 : 68*(idx1+1)]
			if err = val5[idx1].UnmarshalSSZ(buf); err != nil {
				return sszutils.ErrorWithPathf(err, "BuilderExits[%d]", idx1)
			}
		}
		t.BuilderExits = val5
	}
	return nil
}

func (t *ExecutionRequests) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *electra.ExecutionRequests:
		return t.sizeSSZView_ExecutionRequests
	case *gloas.ExecutionRequests:
		return t.sizeSSZView_ExecutionRequests_0
	}
	return nil
}
func (t *ExecutionRequests) sizeSSZView_ExecutionRequests(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(ExecutionRequests)
	}
	// Field #0 'Deposits' offset (4 bytes)
	// Field #1 'Withdrawals' offset (4 bytes)
	// Field #2 'Consolidations' offset (4 bytes)
	size += 12
	{ // Dynamic field #0 'Deposits'
		size += len(t.Deposits) * 192
	}
	{ // Dynamic field #1 'Withdrawals'
		size += len(t.Withdrawals) * 76
	}
	{ // Dynamic field #2 'Consolidations'
		size += len(t.Consolidations) * 116
	}
	return size
}

func (t *ExecutionRequests) sizeSSZView_ExecutionRequests_0(ds sszutils.DynamicSpecs) (size int) {
	if t == nil {
		t = new(ExecutionRequests)
	}
	// Field #0 'Deposits' offset (4 bytes)
	// Field #1 'Withdrawals' offset (4 bytes)
	// Field #2 'Consolidations' offset (4 bytes)
	// Field #3 'BuilderDeposits' offset (4 bytes)
	// Field #4 'BuilderExits' offset (4 bytes)
	size += 20
	{ // Dynamic field #0 'Deposits'
		size += len(t.Deposits) * 192
	}
	{ // Dynamic field #1 'Withdrawals'
		size += len(t.Withdrawals) * 76
	}
	{ // Dynamic field #2 'Consolidations'
		size += len(t.Consolidations) * 116
	}
	{ // Dynamic field #3 'BuilderDeposits'
		size += len(t.BuilderDeposits) * 184
	}
	{ // Dynamic field #4 'BuilderExits'
		size += len(t.BuilderExits) * 68
	}
	return size
}

func (t *ExecutionRequests) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *electra.ExecutionRequests:
		return t.hashTreeRootView_ExecutionRequests
	case *gloas.ExecutionRequests:
		return t.hashTreeRootView_ExecutionRequests_0
	}
	return nil
}
func (t *ExecutionRequests) hashTreeRootView_ExecutionRequests(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	expr0, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_DEPOSIT_REQUESTS_PER_PAYLOAD", 8192)
	if err != nil {
		return err
	}
	expr1, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_WITHDRAWAL_REQUESTS_PER_PAYLOAD", 16)
	if err != nil {
		return err
	}
	expr2, err := sszutils.ResolveSpecValueWithDefault(ds, "MAX_CONSOLIDATION_REQUESTS_PER_PAYLOAD", 2)
	if err != nil {
		return err
	}
	if t == nil {
		t = new(ExecutionRequests)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Deposits'
		t := t.Deposits
		vlen := uint64(len(t))
		if vlen > expr0 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr0), "Deposits")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range len(t) {
			t := t[idx1]
			if t == nil {
				t = new(electra.DepositRequest)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Deposits[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr0, vlen, 32))
	}
	{ // Field #1 'Withdrawals'
		t := t.Withdrawals
		vlen := uint64(len(t))
		if vlen > expr1 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr1), "Withdrawals")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range len(t) {
			t := t[idx1]
			if t == nil {
				t = new(electra.WithdrawalRequest)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr1, vlen, 32))
	}
	{ // Field #2 'Consolidations'
		t := t.Consolidations
		vlen := uint64(len(t))
		if vlen > expr2 {
			return sszutils.ErrorWithPath(sszutils.ErrListLengthFn(vlen, expr2), "Consolidations")
		}
		idx := hh.StartTree(sszutils.TreeTypeBinary)
		for idx1 := range len(t) {
			t := t[idx1]
			if t == nil {
				t = new(electra.ConsolidationRequest)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Consolidations[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeWithMixin(idx, vlen, sszutils.CalculateLimit(expr2, vlen, 32))
	}
	hh.Merkleize(idx)
	return nil
}

func (t *ExecutionRequests) hashTreeRootView_ExecutionRequests_0(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(ExecutionRequests)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Deposits'
		t := t.Deposits
		idx := hh.StartTree(sszutils.TreeTypeProgressive)
		vlen := uint64(len(t))
		for idx1 := range len(t) {
			t := t[idx1]
			if t == nil {
				t = new(electra.DepositRequest)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Deposits[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeProgressiveWithMixin(idx, vlen)
	}
	{ // Field #1 'Withdrawals'
		t := t.Withdrawals
		idx := hh.StartTree(sszutils.TreeTypeProgressive)
		vlen := uint64(len(t))
		for idx1 := range len(t) {
			t := t[idx1]
			if t == nil {
				t = new(electra.WithdrawalRequest)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Withdrawals[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeProgressiveWithMixin(idx, vlen)
	}
	{ // Field #2 'Consolidations'
		t := t.Consolidations
		idx := hh.StartTree(sszutils.TreeTypeProgressive)
		vlen := uint64(len(t))
		for idx1 := range len(t) {
			t := t[idx1]
			if t == nil {
				t = new(electra.ConsolidationRequest)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "Consolidations[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeProgressiveWithMixin(idx, vlen)
	}
	{ // Field #3 'BuilderDeposits'
		t := t.BuilderDeposits
		idx := hh.StartTree(sszutils.TreeTypeProgressive)
		vlen := uint64(len(t))
		for idx1 := range len(t) {
			t := t[idx1]
			if t == nil {
				t = new(gloas.BuilderDepositRequest)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "BuilderDeposits[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeProgressiveWithMixin(idx, vlen)
	}
	{ // Field #4 'BuilderExits'
		t := t.BuilderExits
		idx := hh.StartTree(sszutils.TreeTypeProgressive)
		vlen := uint64(len(t))
		for idx1 := range len(t) {
			t := t[idx1]
			if t == nil {
				t = new(gloas.BuilderExitRequest)
			}
			if err := t.HashTreeRootWith(hh); err != nil {
				return sszutils.ErrorWithPathf(err, "BuilderExits[%d]", idx1)
			}
			if (idx1+1)%256 == 0 {
				hh.Collapse()
			}
		}
		hh.MerkleizeProgressiveWithMixin(idx, vlen)
	}
	hh.MerkleizeProgressiveWithActiveFields(idx, []byte{0x1f})
	return nil
}
