// Code generated by dynamic-ssz. DO NOT EDIT.
// Hash: 8cd234164638bae0272f5abde990c8aa3b388be62a78a8ba856943bc323887ee
// Version: v1.4.0-pre.3 (https://github.com/pk910/dynamic-ssz)

package all

import (
	"encoding/binary"
	"math"

	"github.com/ethpandaops/go-eth2-client/spec/gloas"
	"github.com/pk910/dynamic-ssz/sszutils"
)

var _ = sszutils.ErrListTooBig

var _ = sszutils.Annotate[*gloas.SignedExecutionPayloadEnvelope](`ssz-static:"false"`)

func (t *SignedExecutionPayloadEnvelope) MarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) ([]byte, error) {
	switch view.(type) {
	case *gloas.SignedExecutionPayloadEnvelope:
		return t.marshalSSZView_SignedExecutionPayloadEnvelope
	}
	return nil
}
func (t *SignedExecutionPayloadEnvelope) marshalSSZView_SignedExecutionPayloadEnvelope(ds sszutils.DynamicSpecs, buf []byte) (dst []byte, err error) {
	dst = buf
	if t == nil {
		t = new(SignedExecutionPayloadEnvelope)
	}
	dstlen := len(dst)
	// Offset Field #0 'Message'
	dst = append(dst, 0, 0, 0, 0)
	{ // Static Field #1 'Signature'
		dst = append(dst, t.Signature[:96]...)
	}
	{ // Dynamic Field #0 'Message'
		if off := uint64(len(dst)) - uint64(dstlen); off > math.MaxUint32 {
			return nil, sszutils.ErrOffsetOverflowFn(off)
		} else {
			binary.LittleEndian.PutUint32(dst[dstlen:], uint32(off))
		}
		t := t.Message
		if t == nil {
			t = new(ExecutionPayloadEnvelope)
		}
		if viewFn := t.MarshalSSZDynView((*gloas.ExecutionPayloadEnvelope)(nil)); viewFn != nil {
			if dst, err = viewFn(ds, dst); err != nil {
				return nil, err
			}
		} else {
			return nil, sszutils.ErrNotImplemented
		}
	}
	return dst, nil
}

func (t *SignedExecutionPayloadEnvelope) UnmarshalSSZDynView(view any) func(ds sszutils.DynamicSpecs, buf []byte) error {
	switch view.(type) {
	case *gloas.SignedExecutionPayloadEnvelope:
		return t.unmarshalSSZView_SignedExecutionPayloadEnvelope
	}
	return nil
}
func (t *SignedExecutionPayloadEnvelope) unmarshalSSZView_SignedExecutionPayloadEnvelope(ds sszutils.DynamicSpecs, buf []byte) (err error) {
	buflen := uint64(len(buf))
	if buflen < 100 {
		return sszutils.ErrFixedFieldsEOFFn(buflen, 100)
	}
	// Field #0 'Message' (offset)
	offset0 := binary.LittleEndian.Uint32(buf[0:4])
	if offset0 != 100 {
		return sszutils.ErrorWithPath(sszutils.ErrFirstOffsetMismatchFn(offset0, 100), "Message:o")
	}
	{ // Field #1 'Signature' (static)
		buf := buf[4:100]
		copy(t.Signature[:], buf)
	}
	{ // Field #0 'Message' (dynamic)
		buf := buf[offset0:]
		if t.Message == nil {
			t.Message = new(ExecutionPayloadEnvelope)
		}
		if viewFn := t.Message.UnmarshalSSZDynView((*gloas.ExecutionPayloadEnvelope)(nil)); viewFn != nil {
			if err = viewFn(ds, buf); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	return nil
}

func (t *SignedExecutionPayloadEnvelope) SizeSSZDynView(view any) func(ds sszutils.DynamicSpecs) int {
	switch view.(type) {
	case *gloas.SignedExecutionPayloadEnvelope:
		return t.sizeSSZView_SignedExecutionPayloadEnvelope
	}
	return nil
}
func (t *SignedExecutionPayloadEnvelope) sizeSSZView_SignedExecutionPayloadEnvelope(ds sszutils.DynamicSpecs) int {
	var size int64
	if t == nil {
		t = new(SignedExecutionPayloadEnvelope)
	}
	// Field #0 'Message' offset (4 bytes)
	// Field #1 'Signature' static (96 bytes)
	size += 100
	{ // Dynamic field #0 'Message'
		if viewFn := t.Message.SizeSSZDynView((*gloas.ExecutionPayloadEnvelope)(nil)); viewFn != nil {
			s1 := int64(viewFn(ds))
			if s1 < 0 {
				return -1
			}
			size += s1
		}
	}
	if uint64(size) > sszutils.MaxSszSize {
		return -1
	}
	return int(size)
}

func (t *SignedExecutionPayloadEnvelope) HashTreeRootWithDynView(view any) func(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	switch view.(type) {
	case *gloas.SignedExecutionPayloadEnvelope:
		return t.hashTreeRootView_SignedExecutionPayloadEnvelope
	}
	return nil
}
func (t *SignedExecutionPayloadEnvelope) hashTreeRootView_SignedExecutionPayloadEnvelope(ds sszutils.DynamicSpecs, hh sszutils.HashWalker) error {
	if t == nil {
		t = new(SignedExecutionPayloadEnvelope)
	}
	idx := hh.StartTree(sszutils.TreeTypeNone)
	{ // Field #0 'Message'
		t := t.Message
		if t == nil {
			t = new(ExecutionPayloadEnvelope)
		}
		if viewFn := t.HashTreeRootWithDynView((*gloas.ExecutionPayloadEnvelope)(nil)); viewFn != nil {
			if err := viewFn(ds, hh); err != nil {
				return err
			}
		} else {
			return sszutils.ErrNotImplemented
		}
	}
	{ // Field #1 'Signature'
		hh.PutBytes(t.Signature[:96])
	}
	hh.Merkleize(idx)
	return nil
}
